import type { CityData } from '../../data/types';

export const aveiro: CityData = {
  name: 'Aveiro',
  slug: 'aveiro',
  dates: 'Sep 2 – 5, 2026',
  nights: 3,
  tagline: 'Painted canals, moliceiro boats & ovos moles',
  accentColor: '#B5560A',
  transport: 'Sep 5 — 8:30 AM private van pickup → Porto Airport by 9:45 AM → 12 PM flight back to Vancouver.',
  mapCenter: { lat: 40.6405, lng: -8.6538 },
  mapZoom: 14,

  venue: {
    name: 'Universidade de Aveiro (DETI)',
    eventName: 'PyCon Portugal 2026',
    address: 'DETI, Campus Universitário de Santiago, 3810-193 Aveiro — about 15-min walk south of the old town, or a quick Bolt',
    neighbourhood: 'University campus',
    dates: 'Sep 3 – 4, 2026 (Thu – Fri)',
    hours: 'Typically 9:00 AM – 6:00 PM daily — confirm final schedule with organisers',
    website: 'https://2026.pycon.pt',
    mapUrl: 'https://www.google.com/maps/search/?api=1&query=DETI+Universidade+de+Aveiro',
    nearestTransit: 'Aveiro train station (~15 min walk to old town, then ~15 min walk to DETI) · Bolt is ~5 min from town · flat enough to cycle',
    accessNotes: 'Bring government-issued photo ID for badge pickup. Registration desk typically opens before first session — arrive 30 minutes early on day one.',
    contact: 'Conference info at <a href="https://2026.pycon.pt" target="_blank" rel="noopener">2026.pycon.pt</a> · follow <a href="https://fosstodon.org/@pyconpt" target="_blank" rel="noopener">@pyconpt</a> for updates',
    lat: 40.6305,
    lng: -8.6570,
  },

  iceCreamSpots: [
    {
      name: 'Gelados de Portugal',
      address: 'Rua João Mendonça, near Canal Central, Aveiro',
      signatureFlavors: 'Ovos moles, pastel de nata, Portuguese-inspired flavours',
      photoWorthy: 'Canal-side setting with moliceiro boats in the background — perfect PyCon selfie spot',
      mapUrl: 'https://www.google.com/maps/search/?api=1&query=Gelados+de+Portugal+Aveiro',
      lat: 40.6412,
      lng: -8.6537,
    },
    {
      name: 'Gelataria Italiana',
      address: 'Rua de Coimbra, Aveiro',
      signatureFlavors: 'Classic Italian-style gelato, pistachio, stracciatella',
      photoWorthy: 'Walking distance from the canal — great for a group selfie with PyCon friends',
      mapUrl: 'https://www.google.com/maps/search/?api=1&query=Gelataria+Italiana+Aveiro+Portugal',
      lat: 40.6418,
      lng: -8.6525,
    },
    {
      name: 'Gelataria Portuguesa Aveiro',
      address: 'Aveiro city centre — check for exact location',
      signatureFlavors: 'Seasonal Portuguese fruit sorbets, tart cherry, fig',
      photoWorthy: 'Colourful storefront — bold backdrop for a post-session photo',
      mapUrl: 'https://www.google.com/maps/search/?api=1&query=Gelataria+Portuguesa+Aveiro',
      lat: 40.6402,
      lng: -8.6545,
    },
  ],

  mapPoints: [
    { name: 'Canal Central', type: 'attraction', lat: 40.6405, lng: -8.6530 },
    { name: 'Aveiro Museum', type: 'attraction', lat: 40.6387, lng: -8.6510 },
    { name: 'Ria de Aveiro', type: 'attraction', lat: 40.6450, lng: -8.6600 },
    { name: 'Costa Nova', type: 'attraction', lat: 40.6203, lng: -8.7503 },
    { name: 'Praia da Barra & Farol de Aveiro', type: 'attraction', lat: 40.6428, lng: -8.7466 },
    { name: 'Salinas de Aveiro', type: 'attraction', lat: 40.6510, lng: -8.6680 },
    { name: 'São Jacinto Dunes', type: 'attraction', lat: 40.6730, lng: -8.7290 },
    { name: 'Coimbra (day trip)', type: 'attraction', lat: 40.2110, lng: -8.4290 },
    { name: 'Joanina Library, Coimbra', type: 'attraction', lat: 40.2076, lng: -8.4257 },
    { name: 'Gelados de Portugal', type: 'ice-cream', lat: 40.6412, lng: -8.6537 },
    { name: 'Gelataria Italiana', type: 'ice-cream', lat: 40.6418, lng: -8.6525 },
    { name: 'Gelataria Portuguesa Aveiro', type: 'ice-cream', lat: 40.6402, lng: -8.6545 },
    { name: 'Hotel Moliceiro', type: 'hotel', lat: 40.6413, lng: -8.6530 },
    { name: 'Hotel Aveiro Center', type: 'hotel', lat: 40.6400, lng: -8.6520 },
    { name: 'Hotel Aveiro Palace', type: 'hotel', lat: 40.6410, lng: -8.6525 },
    { name: 'Veneza Hotel', type: 'hotel', lat: 40.6430, lng: -8.6500 },
    { name: 'Salpoente', type: 'restaurant', lat: 40.6430, lng: -8.6560 },
    { name: 'Restaurante O Bairro', type: 'restaurant', lat: 40.6390, lng: -8.6490 },
    { name: 'Mercado do Peixe', type: 'restaurant', lat: 40.6418, lng: -8.6555 },
    { name: 'Tasquinha do Lagar', type: 'restaurant', lat: 40.6395, lng: -8.6492 },
    { name: 'Maré Cheia', type: 'restaurant', lat: 40.6410, lng: -8.6500 },
    { name: 'A Nossa Casa', type: 'restaurant', lat: 40.6362, lng: -8.6475 },
    { name: 'Han Table Barbecue', type: 'restaurant', lat: 40.6400, lng: -8.6510 },
    { name: "António's Spot", type: 'restaurant', lat: 40.6395, lng: -8.6505 },
  ],

  days: [
    {
      dayNum: 11, date: 'Sep 2 (Wed)', title: 'Train to Aveiro & canals',
      activities: [
        { description: 'Alfa Pendular Lisbon → Aveiro (~2 hrs 20 min), arrive mid-morning. Drop bags, grab lunch.' },
        { description: 'Moliceiro boat ride on the canals — €13 adult, €6 kids, 45 min — Aveiro\'s "Little Venice" claim', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Moliceiro+boat+tour+Aveiro+Portugal' },
        { description: 'Wander the old town, buy ovos moles — the local egg-yolk-and-rice-paper sweet, shaped like little white shells' },
        { description: 'Optional late-afternoon escape to Costa Nova (15-min bus or Bolt) for the candy-striped houses and a first look at the Atlantic strand', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Costa+Nova+Aveiro+Portugal' },
        { description: 'Dinner at Mercado do Peixe for fresh seafood. Early night — conference starts tomorrow.', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Mercado+do+Peixe+Aveiro+Portugal' },
      ],
    },
    {
      dayNum: 12, date: 'Sep 3 (Thu)', title: 'PyCon Day 1 + 20th Anniversary 💛',
      activities: [
        { description: 'PyCon Portugal Day 1 at DETI, Universidade de Aveiro (~15-min walk south of old town, or quick Bolt) — Mariatta\'s talk is accepted; check the schedule for the exact slot', url: 'https://2026.pycon.pt/talks/schedule/' },
        { description: 'Family day trip option: Coimbra (~30 min train each way, €5 pp) — Joanina Library, Sé Velha, lunch in the old town. Perfect for teenagers.', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Joanina+Library+Coimbra+Portugal' },
        { description: 'Ice cream selfie: Gelados de Portugal — try the ovos moles flavour by the canal, perfect PyCon selfie backdrop', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Gelados+de+Portugal+Aveiro' },
        { description: '5:30 PM — pre-dinner sunset at Costa Nova (15-min Bolt). Walk along the striped houses, watch the Atlantic light go gold.' },
        { description: '8:00 PM — Anniversary dinner at Salpoente — converted salt warehouse on the canal, modern Portuguese, regularly Aveiro\'s #1 restaurant for occasions. Tasting menu ~€70 pp + wine. Tell them in advance it\'s your 20th — Portuguese restaurants take care of these things sweetly.', url: 'https://salpoente.pt/en/', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Salpoente+Aveiro+Portugal' },
        { description: 'Backup if Salpoente is booked: O Bairro (modern Portuguese, intimate) or Ramona (creative, smaller)' },
        { description: 'Rest of the family: Tasquinha do Lagar (traditional, fun, casual) — different place so the evening is properly yours', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Tasquinha+do+Lagar+Aveiro+Portugal' },
      ],
    },
    {
      dayNum: 13, date: 'Sep 4 (Fri)', title: 'PyCon Day 2 + more beach',
      activities: [
        { description: 'PyCon Portugal Day 2 at DETI', url: 'https://2026.pycon.pt/talks/schedule/' },
        { description: 'Family beach option A: São Jacinto Dunes nature reserve — ferry across the lagoon + walk through wild dune beaches, the quietest beach near Aveiro', mapUrl: 'https://www.google.com/maps/search/?api=1&query=S%C3%A3o+Jacinto+Dunes+Aveiro+Portugal' },
        { description: 'Family beach option B: longer day at Costa Nova / Praia da Barra if everyone loved it', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Praia+da+Barra+Portugal' },
        { description: 'Non-beach option: Salinas de Aveiro working salt pans — kids can do a guided tour and learn how flor de sal is harvested', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Salinas+de+Aveiro+Portugal' },
        { description: 'Or BUGA bikes — Aveiro\'s free city bike system, perfect for flat canal paths', mapUrl: 'https://www.google.com/maps/search/?api=1&query=BUGA+Aveiro+Portugal' },
        { description: 'Ice cream selfie: Gelataria Italiana on Rua de Coimbra — group selfie with PyCon friends', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Gelataria+Italiana+Aveiro+Portugal' },
        { description: 'Conference ends Friday — pack tonight, light dinner, early bed' },
      ],
    },
    {
      dayNum: 14, date: 'Sep 5 (Sat)', title: 'Aveiro → Porto Airport',
      activities: [
        { description: '8:30 AM private van pickup from the hotel', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Aveiro+Portugal' },
        { description: 'Arrive Porto Airport by 9:45 AM', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Porto+Airport+OPO' },
        { description: 'Easy 12 PM flight back to Vancouver' },
      ],
    },
  ],

  hotels: [
    {
      name: 'Hotel Moliceiro',
      rating: 4.5,
      ratingCount: '900',
      price: '€€',
      priceLabel: 'Mid-range',
      tags: ['Canal-front', 'Top pick', 'Spacious rooms'],
      description: 'Right on the canal — you can watch moliceiro boats glide past from your window. Spacious rooms, excellent and varied breakfast, and a knowledgeable and helpful staff. The most atmospheric hotel in Aveiro, named after the iconic painted boats.',
      tip: 'Best for: Families wanting the quintessential Aveiro canal experience',
      website: 'http://www.hotelmoliceiro.pt',
    },
    {
      name: 'Hotel Aveiro Center',
      rating: 4.5,
      ratingCount: '647',
      price: '€',
      priceLabel: 'Budget-friendly',
      tags: ['Canal view rooms', 'Fresh breakfast', 'Great staff'],
      description: 'Charming, traditionally renovated hotel with canal-view rooms and a lovely breakfast featuring fresh pastries, honeycombs, fruit, and olive oil. Staff go above and beyond with local tips. Shares facilities with its 4-star neighbour.',
      tip: 'Best for: Budget-conscious families wanting canal charm and character',
      website: 'http://www.hotelaveirocenter.com',
    },
    {
      name: 'Hotel Aveiro Palace',
      rating: 4.3,
      ratingCount: '1.3k',
      price: '€€',
      priceLabel: 'Mid-range',
      tags: ['Historic', 'Waterfront balcony suites', 'Character'],
      description: 'The oldest hotel in Aveiro, tastefully modernised. First-floor suites have a narrow balcony overlooking the canal — perfect for watching the city wake up. Solid continental breakfast. Rooms are cozy rather than large, but full of character.',
      tip: 'Best for: Families who enjoy staying in a historic property with soul',
      website: 'https://turim-hotels.com',
    },
    {
      name: 'Veneza Hotel',
      rating: 4.4,
      ratingCount: '1.5k',
      price: '€',
      priceLabel: 'Budget-friendly',
      tags: ['Near train station', 'Garden view', 'Easy access'],
      description: 'Elegant, old-fashioned décor in a spotlessly clean property. Rooms overlook a peaceful garden pond. A very short walk to the train station — ideal for arrival and departure days. Book parking in advance as the hotel lot fills quickly.',
      tip: 'Best for: Easy train connections and a tranquil garden setting',
      website: 'https://www.venezahotel.pt',
    },
  ],

  restaurants: [
    {
      name: 'Salpoente',
      rating: 4.7,
      ratingCount: '3.8k',
      price: '€€€',
      tags: ['Anniversary-worthy', 'Salt warehouse setting', 'Modern Portuguese'],
      description: 'Aveiro\'s finest dining experience, set inside two beautifully converted 19th-century salt warehouses on the canal. Modern Portuguese tasting menus built around estuary ingredients — octopus confit, salt cod with creamy corn, and a signature ovos moles dessert. The candlelit interior, exposed stone walls, and waterside setting make it ideal for a milestone celebration. Tasting menu ~€70 pp + wine.',
      mustTry: 'Octopus confit, salt cod with creamy corn, signature ovos moles dessert',
      hours: 'Tue–Sat lunch & dinner. Closed Sun & Mon.',
      bookAhead: true,
    },
    {
      name: 'Restaurante O Bairro',
      rating: 4.7,
      ratingCount: '2.3k',
      price: '€€',
      tags: ['Best in Aveiro', 'Legendary risottos', 'Reserve ahead'],
      description: 'The best restaurant in Aveiro by a significant margin. Their five risottos — fish, duck, meat, mushroom, and more — are legendary. Prices are remarkably low for the quality. People drive from Porto just to eat here. Closed Wednesdays. Book via Facebook or email. Also a strong backup for the anniversary night.',
      mustTry: 'Any of the five risotto specialties — they are all exceptional',
      hours: 'Mon–Tue, Thu–Sun lunch & dinner. Closed Wed.',
      bookAhead: true,
    },
    {
      name: 'Mercado do Peixe',
      rating: 4.4,
      ratingCount: '2.1k',
      price: '€€',
      tags: ['Fresh seafood', 'Above the fish market', 'Casual'],
      description: 'Perched right above the city\'s working fish market — the catch comes upstairs the same morning. Charcoal-grilled sardines, sea bream, and octopus done simply and beautifully. A relaxed, generous spot for the first night in Aveiro.',
      mustTry: 'Grilled sardines, charcoal sea bream, octopus salad',
      hours: 'Tue–Sun lunch & dinner. Closed Mon.',
    },
    {
      name: 'Tasquinha do Lagar',
      rating: 4.5,
      ratingCount: '1.4k',
      price: '€€',
      tags: ['Traditional', 'Fun & casual', 'Great for kids'],
      description: 'A lively traditional tasca — exactly the right "everybody\'s welcome, lots of plates on the table" energy for the rest of the family on anniversary night. Generous portions of bacalhau à brás, picanha, and chouriço assado. Kids love the staff and the bread.',
      mustTry: 'Bacalhau à brás, picanha steak, flame-grilled chouriço',
      hours: 'Mon–Sat lunch & dinner. Closed Sun.',
    },
    {
      name: 'Maré Cheia',
      rating: 4.6,
      ratingCount: '3.3k',
      price: '€€',
      tags: ['Seafood specialist', 'Fresh daily catch', 'Family classic'],
      description: 'Outstanding fresh seafood — stuffed crab (sapateira), mixed seafood platters, clams, and grilled sole. The mixed platter for two is actually enough for 3–4. A classic Aveiro seafood experience. Closed Mondays. Arrive early or book ahead.',
      mustTry: 'Stuffed crab (sapateira) and the seafood rice',
      hours: 'Tue–Sun lunch & dinner. Closed Mon.',
    },
    {
      name: 'A Nossa Casa',
      rating: 4.1,
      ratingCount: '900',
      price: '€€',
      tags: ['Local favourite', 'Fresh seafood', 'Generous portions'],
      description: 'A no-frills neighbourhood tasca that locals pack out for honest, generously portioned Portuguese seafood. Clams, garlic prawns, seafood rice, eel stew, and simply grilled fresh fish — excellent value for the quality. Not fancy, and it can get a long wait at peak times, so arrive early or be ready to queue.',
      mustTry: 'Arroz de marisco (seafood rice), clams, and the grilled fresh fish of the day',
      hours: 'Lunch & dinner — popular with locals, expect a wait at peak times',
    },
    {
      name: 'Han Table Barbecue',
      rating: 4.9,
      ratingCount: '1.1k',
      price: '€€',
      tags: ['Korean BBQ', 'Kids absolutely love it', 'Interactive'],
      description: 'An unexpected gem — Korean BBQ cooked at your own table. Kids love the interactive experience of grilling their own meat. Exceptional quality and service. A fantastic option for a fun, different family dinner. Open daily for lunch and dinner.',
      mustTry: 'Marinated beef, kimchi rice, and the spicy seafood starter',
      hours: 'Daily lunch & dinner',
    },
    {
      name: 'António\'s Spot',
      rating: 4.5,
      ratingCount: '670',
      price: '€',
      tags: ['Casual & cozy', 'Budget', 'Great coffee'],
      description: 'A cozy neighbourhood pub-restaurant perfect for a relaxed family lunch or late breakfast. Excellent grilled octopus, beef steak with egg and fries, and great coffee. Warm, welcoming staff. Open from 9am — works well for late risers.',
      mustTry: 'Grilled octopus and the pepper steak with egg',
      hours: 'Mon–Sat 9am–11pm, Sun 9am–6pm',
    },
  ],
};