import type { ChecklistCategory } from '../../data/types';

export const checklistData: ChecklistCategory[] = [
  {
    id: 'flights',
    title: 'Flights & Transport',
    emoji: '✈️',
    items: [
      { id: 'flights-book-yvr-opo', label: 'Book YVR to OPO flights (family of 4)', dueBy: 'ASAP' },
      { id: 'flights-book-return', label: 'Book OPO to YVR return flights (Sep 5, 12 PM)', dueBy: 'ASAP' },
      { id: 'flights-train-porto-lisbon', label: 'Book Alfa Pendular train Porto → Lisbon (Aug 28, pre-9 AM)', note: 'Family-leg discounts disappear last — book on the 60-day window', dueBy: 'Jun 2026', url: 'https://www.cp.pt' },
      { id: 'flights-train-lisbon-aveiro', label: 'Book Alfa Pendular Lisbon → Aveiro (Sep 2 morning)', dueBy: 'Jun 2026', url: 'https://www.cp.pt' },
      { id: 'flights-van-aveiro-opo', label: 'Book Sep 5 private van Aveiro → Porto Airport (8:30 AM pickup)', note: 'Earlier and more flexible than train + transfer for a 12 PM flight', dueBy: 'Jul 2026' },
      { id: 'flights-airport-transport', label: 'Research Porto airport → Porto hotel transport on arrival (taxi, Bolt, or metro)', dueBy: 'Jul 2026' },
    ],
  },
  {
    id: 'accommodation',
    title: 'Accommodation',
    emoji: '🏨',
    items: [
      { id: 'hotel-porto', label: 'Porto hotel (5 nights, Aug 23–28) — arranged ✓' },
      { id: 'hotel-lisbon', label: 'Lisbon hotel (5 nights, Aug 28 – Sep 2) — re-book +1 night', note: 'Added Sep 1 (Cascais day). Príncipe Real or Chiado for central; Alfama for medieval romance' },
      { id: 'hotel-aveiro', label: 'Aveiro hotel (3 nights, Sep 2–5) — re-book −1 night', note: 'Dropped one night. Historic centre near canals — easy walk to old town and Bolt to DETI' },
      { id: 'hotel-confirm', label: 'Confirm all hotel reservations 2 weeks before departure', dueBy: 'Aug 9' },
    ],
  },
  {
    id: 'documents',
    title: 'Documents & Insurance',
    emoji: '🛂',
    items: [
      { id: 'docs-passports', label: 'Check passport validity for all 4 family members', note: 'Must be valid 6+ months past Sep 5, 2026' },
      { id: 'docs-insurance', label: 'Arrange travel insurance (medical, trip cancellation)', dueBy: 'Jul 2026' },
      { id: 'docs-entry-reqs', label: 'Check Canada–Portugal entry requirements', note: 'No visa needed for stays under 90 days, but verify before travel' },
      { id: 'docs-hotel-pdfs', label: 'Print or save hotel confirmation PDFs' },
      { id: 'docs-train-pdfs', label: 'Print or save train ticket PDFs' },
      { id: 'docs-flight-pdfs', label: 'Print or save flight confirmation PDFs' },
      { id: 'docs-van-pdf', label: 'Print or save Sep 5 private van booking confirmation' },
      { id: 'docs-idp', label: 'Get an International Driving Permit for the Gerês rental day', note: 'CAA issues them in person, valid 1 year. Portugal will usually take a Canadian licence alone, but rental desks vary and the IDP removes the argument. Bring the plastic licence too.', dueBy: 'Jul 2026' },
      { id: 'docs-bank-notify', label: 'Notify bank and credit card company of Portugal travel dates', dueBy: 'Aug 2026' },
    ],
  },
  {
    id: 'pycon',
    title: 'PyCon Portugal',
    emoji: '🐍',
    items: [
      { id: 'pycon-register', label: 'Register for PyCon Portugal (Sep 3–4, DETI Aveiro)', url: 'https://pycon.pt/' },
      { id: 'pycon-schedule', label: 'Check PyCon schedule and plan which sessions to attend' },
      { id: 'pycon-talk', label: 'Prepare talk or materials (if presenting)' },
      { id: 'pycon-social', label: 'Book any PyCon social events or sprints' },
      { id: 'pycon-ice-cream', label: 'Scout ice cream selfie spot near PyCon venue 🍦', note: 'Gelados de Portugal by the canal, or Gelataria Italiana on Rua de Coimbra' },
    ],
  },
  {
    id: 'bookings',
    title: 'Activities & Bookings',
    emoji: '🎫',
    items: [
      { id: 'book-salpoente', label: 'Reserve 20th anniversary dinner at Salpoente, Aveiro (Sep 3, 8 PM)', note: 'Books up weeks ahead — flag the anniversary when reserving', dueBy: 'Jun 2026', url: 'https://salpoente.pt/en/' },
      { id: 'book-tasquinha-lagar', label: 'Book Tasquinha do Lagar dinner for the rest of the family (Sep 3)', note: 'Different place from Salpoente so the anniversary evening is properly yours' },
      { id: 'book-livraria-lello', label: 'Book Livraria Lello timed entry online (Aug 24)', note: '€12 pp, refunded against book purchase — skips the long line', dueBy: 'Aug 2026', url: 'https://www.livrarialello.pt/' },
      { id: 'book-geres-car', label: 'Book a 1-day car rental in Porto for the Peneda-Gerês day (Aug 26)', note: 'Pick up in the city, not the airport. Request the Via Verde toll transponder and confirm automatic transmission — automatics sell out early for August.', dueBy: 'Jun 2026' },
      { id: 'book-sintra-pena', label: 'Buy Pena Palace tickets online (Aug 31)', note: 'Same-day tickets sell out in August. Mondays are the least crowded day at Sintra.', dueBy: 'Jul 2026', url: 'https://www.parquesdesintra.pt/en/' },
      { id: 'book-sintra-regaleira', label: 'Buy Quinta da Regaleira tickets (Aug 31)', dueBy: 'Jul 2026', url: 'https://www.regaleira.pt/' },
      { id: 'book-sintra-driver', label: 'Decide on Sintra: book a private driver (~€180–220) or take train + 434 bus' },
      { id: 'book-douro', label: 'Book Douro Valley day trip (Aug 25)', note: 'Train + boat option (~€60 pp) OR private guided tour (~€150 pp). Quinta do Bomfim in Pinhão for tastings.', dueBy: 'Jul 2026' },
      { id: 'book-wine-cellar', label: 'Pick & book a port wine cellar tour in Vila Nova de Gaia (Aug 24)', note: 'Graham\'s (best tour & views), Taylor\'s (gardens & peacocks), or Ferreira (Portuguese-owned)' },
      { id: 'book-cascais', label: 'Plan Cascais coast day (Sep 1)', note: 'Coastal train from Cais do Sodré (~40 min, turn-up). Boca do Inferno + Mar do Inferno cliffside lunch; optional Cabo da Roca by taxi.' },
      { id: 'book-seasickness', label: 'Pack seasickness tablets for the charter (Aug 30)', note: 'Taken an hour before boarding, so at lunch. Enough doses for all four in case the bar is choppy.' },
      { id: 'book-fado', label: 'Plan a Fado night in Alfama (Aug 30 evening)', note: 'Mesa de Frades or Tasca do Chico (casual, no reservation needed)' },
      { id: 'book-charter', label: 'Book the Tagus fishing charter — afternoon slot, ~2 PM (Aug 30)', note: 'Half-day private boat out of Doca de Santo Amaro / Doca de Alcântara. Ask for the afternoon departure so the morning stays free, and confirm rods, bait, tackle and licence cover are included and under-18s are allowed aboard. Sundays in August book out.', dueBy: 'Jun 2026' },
      { id: 'book-castelo', label: 'Reserve Castelo de São Jorge tickets (Aug 29)', dueBy: 'Jul 2026', url: 'https://castelodesaojorge.pt/en/' },
      { id: 'book-coimbra-library', label: 'Book Joanina Library tickets at University of Coimbra (Sep 3)', note: 'Photos not allowed but unforgettable. Book online in advance.' },
      { id: 'book-o-bairro', label: 'Reserve Restaurante O Bairro, Aveiro (anniversary backup)', note: 'Book via Facebook or email. Closed Wednesdays.' },
    ],
  },
  {
    id: 'money-tech',
    title: 'Money & Connectivity',
    emoji: '💳',
    items: [
      { id: 'tech-esim', label: 'Order or activate an eSIM or local SIM for data', dueBy: 'Aug 2026' },
      { id: 'tech-adapter', label: 'Get at least one Type F power adapter (EU round 2-pin, 230V)' },
      { id: 'tech-rideshare', label: 'Set up Bolt and Uber apps with payment method' },
      { id: 'money-euros', label: 'Plan Euro cash — bring small amount or use ATM on arrival', note: 'Multibanco ATMs are everywhere. Decline the ATM conversion offer.' },
      { id: 'money-andante', label: 'Get Andante transit card on arrival in Porto', note: '€0.50 for the card, load with trips or day passes' },
      { id: 'money-viva', label: 'Get Viva Viagem transit card on arrival in Lisbon', note: '€0.50 for the card, works on metro, buses, trams, and ferries' },
    ],
  },
  {
    id: 'packing',
    title: 'Packing',
    emoji: '🧳',
    items: [
      { id: 'pack-shoes', label: 'Comfortable walking shoes (cobblestones and hills!)' },
      { id: 'pack-sunscreen', label: 'Sunscreen SPF 50 for the whole family' },
      { id: 'pack-hats', label: 'Sun hats and sunglasses' },
      { id: 'pack-swimwear', label: 'Swimwear (Matosinhos, Foz do Douro, Costa Nova, Praia da Barra)' },
      { id: 'pack-rain-jacket', label: 'Light rain jacket or layer for cooler evenings' },
      { id: 'pack-adapter', label: 'Universal power adapter (Type F)' },
      { id: 'pack-charger', label: 'Portable charger / power bank' },
      { id: 'pack-water-bottles', label: 'Refillable water bottles (tap water is safe)' },
      { id: 'pack-daypack', label: 'Day backpack' },
      { id: 'pack-kids-flight', label: 'Kids\' entertainment for flights (tablets, books, snacks)' },
      { id: 'pack-meds', label: 'Medications and first-aid kit' },
      { id: 'pack-anniversary-outfit', label: 'Outfit for Salpoente anniversary dinner (Sep 3)' },
    ],
  },
  {
    id: 'before-departure',
    title: 'Before Departure',
    emoji: '🏠',
    items: [
      { id: 'pre-fish-fill', label: 'Fill both fish feeders 🐟' },
      { id: 'pre-fish-charge', label: 'Charge both fish feeders (or fresh batteries)' },
      { id: 'pre-fish-test', label: 'Test-fire both fish feeders before leaving' },
      { id: 'pre-fish-water', label: 'Top up tank water / run a water change' },
      { id: 'pre-lights', label: 'Set home lights on timers' },
      { id: 'pre-itinerary', label: 'Share itinerary with an emergency contact' },
      { id: 'pre-offline-maps', label: 'Download offline maps for Porto, Lisbon, and Aveiro' },
      { id: 'pre-cp-app', label: 'Download CP (train) app', url: 'https://www.cp.pt' },
      { id: 'pre-confirm-48h', label: 'Confirm all bookings 48 hours before departure', dueBy: 'Aug 21' },
    ],
  },
];