import type { CityData } from '../../data/types';

export const lisbon: CityData = {
  name: 'Lisbon',
  country: 'Portugal',
  slug: 'lisbon',
  dates: 'Aug 28 – Sep 2, 2026',
  nights: 5,
  tagline: 'Hilltop castles, tram rides & pastéis de Belém',
  accentColor: '#2D6A4F',
  transport: 'Sep 2 — Alfa Pendular train to Aveiro (~2 hrs 20 min). Arrive mid-morning.',
  mapCenter: { lat: 38.7223, lng: -9.1393 },
  mapZoom: 12,
  mapPoints: [
    { name: 'Praça do Comércio', type: 'attraction', lat: 38.7075, lng: -9.1364 },
    { name: 'Chiado', type: 'attraction', lat: 38.7105, lng: -9.1430 },
    { name: 'Livraria Bertrand', type: 'attraction', lat: 38.7106, lng: -9.1418 },
    { name: 'Castelo de São Jorge', type: 'attraction', lat: 38.7139, lng: -9.1335 },
    { name: 'Lisbon Cathedral (Sé)', type: 'attraction', lat: 38.7098, lng: -9.1326 },
    { name: 'Alfama', type: 'attraction', lat: 38.7120, lng: -9.1300 },
    { name: 'Feira da Ladra', type: 'attraction', lat: 38.7156, lng: -9.1262 },
    { name: 'LX Factory', type: 'attraction', lat: 38.7038, lng: -9.1779 },
    { name: 'Time Out Market', type: 'attraction', lat: 38.7066, lng: -9.1455 },
    { name: 'Oceanário de Lisboa', type: 'attraction', lat: 38.7636, lng: -9.0939 },
    { name: 'Gulbenkian Museum', type: 'attraction', lat: 38.7370, lng: -9.1538 },
    { name: 'Basílica da Estrela', type: 'attraction', lat: 38.7137, lng: -9.1601 },
    { name: 'Jardim da Estrela', type: 'attraction', lat: 38.7145, lng: -9.1608 },
    { name: 'Museu Nacional de Arte Antiga', type: 'attraction', lat: 38.7043, lng: -9.1614 },
    { name: 'Pilar 7 Bridge Experience', type: 'attraction', lat: 38.6996, lng: -9.1772 },
    { name: 'Doca de Santo Amaro (charter dock)', type: 'attraction', lat: 38.7031, lng: -9.1735 },
    { name: '25 de Abril Bridge', type: 'attraction', lat: 38.6913, lng: -9.1774 },
    { name: 'Cristo Rei', type: 'attraction', lat: 38.6785, lng: -9.1706 },
    { name: 'Tower of Belém', type: 'attraction', lat: 38.6916, lng: -9.2160 },
    { name: 'Monument to the Discoveries', type: 'attraction', lat: 38.6936, lng: -9.2057 },
    { name: 'Pena Palace (Sintra)', type: 'attraction', lat: 38.7876, lng: -9.3907 },
    { name: 'Quinta da Regaleira (Sintra)', type: 'attraction', lat: 38.7965, lng: -9.3963 },
    { name: 'Cabo da Roca', type: 'attraction', lat: 38.7805, lng: -9.4989 },
    { name: 'Cascais', type: 'attraction', lat: 38.6979, lng: -9.4215 },
    { name: 'Martinhal Lisbon Chiado', type: 'hotel', lat: 38.7105, lng: -9.1430 },
    { name: 'Vincci Alfama', type: 'hotel', lat: 38.7120, lng: -9.1290 },
    { name: 'My Story Hotel Tejo', type: 'hotel', lat: 38.7110, lng: -9.1330 },
    { name: 'Pestana CR7 Lisboa', type: 'hotel', lat: 38.7080, lng: -9.1370 },
    { name: 'Manteigaria', type: 'restaurant', lat: 38.7099, lng: -9.1432 },
    { name: 'Doca Peixe', type: 'restaurant', lat: 38.7029, lng: -9.1741 },
    { name: 'Tasca do Chico', type: 'restaurant', lat: 38.7126, lng: -9.1303 },
    { name: 'Mar do Inferno (Cascais)', type: 'restaurant', lat: 38.6927, lng: -9.4287 },
    { name: 'El Clan', type: 'restaurant', lat: 38.7100, lng: -9.1330 },
    { name: 'Floresta das Escadinhas', type: 'restaurant', lat: 38.7120, lng: -9.1310 },
    { name: 'Come Prima', type: 'restaurant', lat: 38.7270, lng: -9.1500 },
    { name: "LUDO'S", type: 'restaurant', lat: 38.7130, lng: -9.1280 },
    { name: 'World of Heroes', type: 'restaurant', lat: 38.7200, lng: -9.1400 },
  ],

  days: [
    {
      dayNum: 6, date: 'Aug 28 (Fri)', title: 'Train to Lisbon & Chiado',
      activities: [
        { description: 'Pre-9 AM Alfa Pendular Porto → Lisbon, arrive by lunch. Drop bags.' },
        { description: 'Walk to Praça do Comércio — the grand riverfront square', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Pra%C3%A7a+do+Com%C3%A9rcio+Lisbon+Portugal' },
        { description: 'Tram up to Chiado, browse Livraria Bertrand — officially the world\'s oldest bookstore', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Livraria+Bertrand+Chiado+Lisbon+Portugal' },
        { description: 'Pastel de nata at Manteigaria', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Manteigaria+Chiado+Lisbon+Portugal' },
        { description: 'Light dinner at Time Out Market — everyone picks their own thing. It fills the south half of the historic 1892 Mercado da Ribeira; the north half is still a working morning fruit, veg & fish market (Lisbon\'s Bolhão equivalent) if you swing by earlier in the day.', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Mercado+da+Ribeira+Time+Out+Market+Lisbon+Portugal' },
      ],
    },
    {
      dayNum: 7, date: 'Aug 29 (Sat)', title: 'Old Lisbon climb',
      activities: [
        { description: 'Morning: ride iconic Tram 28 end-to-end early (impossibly packed by 10 AM)', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Tram+28+Lisbon+Portugal' },
        { description: 'Castelo de São Jorge — Moorish hilltop fortress, panoramic views, and resident peacocks the teens will photograph endlessly', url: 'https://castelodesaojorge.pt/en/', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Castelo+de+S%C3%A3o+Jorge+Lisbon+Portugal' },
        { description: 'Lunch in Alfama\'s tangled lanes', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Alfama+Lisbon+Portugal' },
        { description: 'Sé Cathedral, then wander down to Feira da Ladra flea market — Saturdays only, in Campo de Santa Clara', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Feira+da+Ladra+Lisbon+Portugal' },
        { description: 'Evening: LX Factory — converted industrial complex turned creative quarter, with murals, indie shops, and great casual food', mapUrl: 'https://www.google.com/maps/search/?api=1&query=LX+Factory+Lisbon+Portugal' },
      ],
    },
    {
      dayNum: 8, date: 'Aug 30 (Sun)', title: 'Slow Lisbon morning + afternoon fishing charter 🎣 + Fado',
      activities: [
        { description: 'Sleep in and take a proper hotel breakfast — the boat is not until the afternoon, and this is the one unhurried morning of the Lisbon stretch' },
        { description: 'Tram 25 or 28 west to Estrela. Basílica da Estrela — the white dome is climbable for a rooftop view almost no visitor bothers with, and Sunday morning mass is in full voice below you.', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Bas%C3%ADlica+da+Estrela+Lisbon+Portugal' },
        { description: 'Jardim da Estrela across the road — a real neighbourhood park with a duck pond, a playground and a kiosk café under the trees. The most un-touristy hour of the whole trip.', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Jardim+da+Estrela+Lisbon+Portugal' },
        { description: 'Downhill through Lapa to the Museu Nacional de Arte Antiga — Bosch\'s Temptation of St Anthony alone earns the stop, and the garden terrace café looks straight out over the docks you are about to sail from. Open Sun 10–6, closed Mondays.', url: 'https://www.museudearteantiga.pt/', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Museu+Nacional+de+Arte+Antiga+Lisbon+Portugal' },
        { description: 'Bolt down to Alcântara (~10 min) and ride up Pilar 7 — the lift inside the pillar of the 25 de Abril bridge opens onto a glass-floored platform 80 m above the water. Doing it an hour before passing underneath by boat is the whole point.', url: 'https://www.visitlisboa.com/', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Pilar+7+Bridge+Experience+Lisbon+Portugal' },
        { description: 'Early light lunch on the terrace at Doca Peixe, right where the charters tie up — keep it light, you are getting on a boat', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Doca+Peixe+Lisbon+Portugal' },
        { description: 'Around 2 PM: half-day (~4 hr) private charter out onto the Tagus from Doca de Santo Amaro. The skipper supplies rods, bait, tackle and the licence cover — bring hats, sunscreen and a layer each; it is windier on the water than on shore.', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Doca+de+Santo+Amaro+Lisbon+Portugal' },
        { description: 'Late August catch on the estuary: seabass, mackerel and horse mackerel, seabream, the odd meagre. Ask the skipper to run out past the bar toward Cascais bay if the swell is calm and the teens want something bigger on the line.' },
        { description: 'The view is half the trip — the 25 de Abril bridge from underneath, Cristo Rei on the south bank, and Belém Tower and the Padrão dos Descobrimentos from the river, which is the side they were built to be seen from', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Torre+de+Bel%C3%A9m+Lisbon+Portugal' },
        { description: 'Seasickness: take a tablet an hour before boarding, so at lunch. The estuary itself is flat, but the mouth gets choppy on an ebbing tide.' },
        { description: 'Back at the dock around 6 PM. Rinse off at the hotel, then out to Alfama.' },
        { description: 'Evening Fado in Alfama: Mesa de Frades or Tasca do Chico (casual, no reservation needed) — dinner is petiscos as the singing goes on, and even teens get into it', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Tasca+do+Chico+Alfama+Lisbon+Portugal' },
      ],
    },
    {
      dayNum: 9, date: 'Aug 31 (Mon)', title: 'Sintra day trip ⭐',
      activities: [
        { description: 'Train from Rossio Station (~40 min). Buy palace tickets online in advance — Sintra sells out same-day in August.' },
        { description: 'Mondays are noticeably less crowded at Sintra than weekends — a real win for this slot' },
        { description: 'Pena Palace — the candy-coloured fairytale on the hill (morning)', url: 'https://www.parquesdesintra.pt/en/parks-and-monuments/park-and-national-palace-of-pena/', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Pena+Palace+Sintra+Portugal' },
        { description: 'Quinta da Regaleira — mystical gardens and the 9-storey spiral Initiation Well (afternoon). Teens think it\'s the coolest thing in Portugal.', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Quinta+da+Regaleira+Sintra+Portugal' },
        { description: 'Pro tip: a Lisbon-based driver for the day (~€180–220) avoids Sintra\'s parking nightmares and the long 434 bus queues' },
      ],
    },
    {
      dayNum: 10, date: 'Sep 1 (Tue)', title: 'Cascais & the Atlantic coast',
      activities: [
        { description: 'Morning train from Cais do Sodré along the coast to Cascais (~40 min, frequent & cheap). Sit on the right for ocean views the whole way.', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Cascais+Portugal' },
        { description: 'Wander Cascais old town — the marina, the fishing harbour, and tiny Praia da Rainha tucked between the buildings', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Cascais+old+town+Portugal' },
        { description: 'Boca do Inferno — the dramatic "Hell\'s Mouth" sea cliffs and blowhole, a ~20-min walk or quick tuk-tuk west of the centre', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Boca+do+Inferno+Cascais+Portugal' },
        { description: 'Lunch on the cliffs at Mar do Inferno — pick your fish from the iced display and watch the Atlantic crash below', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Mar+do+Inferno+Cascais+Portugal' },
        { description: 'Afternoon beach time at the calm town beaches Praia da Conceição / Praia da Duquesa, or rent bikes on the seafront promenade toward Estoril', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Praia+da+Concei%C3%A7%C3%A3o+Cascais+Portugal' },
        { description: 'If energy allows: Uber/taxi out to Cabo da Roca for sunset — the westernmost point of mainland Europe, cliffs and Atlantic wind', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Cabo+da+Roca+Portugal' },
        { description: 'Late train back to Lisbon — last full night. Pack tonight; Alfa Pendular to Aveiro in the morning.' },
      ],
    },
  ],

  hotels: [
    {
      name: 'Martinhal Lisbon Chiado',
      rating: 4.7,
      ratingCount: '194',
      price: '€€€',
      priceLabel: 'Splurge',
      tags: ['Best for families', 'Kids\' club', 'Babysitting', 'Chiado'],
      description: 'The single best family hotel in Lisbon. Kids\' club, babysitting, child-sized robes and flip flops, training potty, step stools in bathrooms — they\'ve thought of everything. Complimentary breakfast, apartment-style suites, central Chiado location. Worth every cent for families with young children.',
      tip: 'Best for: Families with children under 10 — this is your pick, full stop',
      website: 'https://www.martinhal.com',
    },
    {
      name: 'Vincci Alfama',
      rating: 4.9,
      ratingCount: '363',
      price: '€€€',
      priceLabel: 'Splurge',
      tags: ['Alfama old town', 'Superb breakfast', 'Boutique'],
      description: 'Stylish boutique hotel deep in Alfama with one of Lisbon\'s best breakfasts. Authentic old-town experience with outstanding staff recommendations. Note: request a conventional room — some rooms have an open-plan shower not suited for family sharing.',
      tip: 'Best for: Families wanting an authentic Alfama neighbourhood feel',
      website: 'https://www.vinccihoteles.com',
    },
    {
      name: 'My Story Hotel Tejo',
      rating: 4.4,
      ratingCount: '1.7k',
      price: '€€',
      priceLabel: 'Mid-range',
      tags: ['Near Alfama', 'Tram 28', 'Blackout curtains'],
      description: 'Excellent value hotel steps from Alfama, Tram 28, and the Tagus waterfront. True blackout curtains make a big difference for kids\' sleep. Good breakfast variety and very helpful staff. Request a family room — standard rooms are on the smaller side.',
      tip: 'Best for: Families on a mid-range budget near the old town',
      website: 'https://www.mystoryhotels.com',
    },
    {
      name: 'Pestana CR7 Lisboa',
      rating: 4.5,
      ratingCount: '2.4k',
      price: '€€',
      priceLabel: 'Mid-range',
      tags: ['Praça do Comércio', 'River views', 'Gym'],
      description: 'Right by the Praça do Comércio with excellent river views from corner rooms. A fun pick if your kids are football fans. Good breakfast and central location. Request a family room and crib in advance when booking.',
      tip: 'Best for: Football-loving families wanting the waterfront address',
      website: 'https://www.pestana.com',
    },
  ],

  restaurants: [
    {
      name: 'Manteigaria',
      rating: 4.7,
      ratingCount: '12k',
      price: '€',
      tags: ['Pastel de nata', 'Quick stop', 'Counter only'],
      description: 'The other contender for best pastel de nata in Lisbon — many locals prefer it to Belém. Watch them being shaped through the window, eat them warm at the counter with a sprinkle of cinnamon and an espresso. Multiple locations; the Chiado branch is the original.',
      mustTry: 'Pastel de nata, fresh from the oven, with cinnamon',
      hours: 'Daily 8am–midnight',
    },
    {
      name: 'Time Out Market',
      rating: 4.4,
      ratingCount: '60k',
      price: '€€',
      tags: ['Food hall', 'Everyone picks their own', 'Late hours'],
      description: 'A converted market hall curated by Time Out — stalls from many of Lisbon\'s best chefs and bakers in one big shared dining room. Perfect for a family where everyone wants something different. Get there before 7pm to grab a table on busy nights.',
      mustTry: 'Henrique Sá Pessoa\'s steak, Marlene Vieira\'s seafood, Manteigaria\'s natas',
      hours: 'Daily 10am–midnight',
    },
    {
      name: 'Tasca do Chico',
      rating: 4.4,
      ratingCount: '5.2k',
      price: '€€',
      tags: ['Casual Fado', 'No reservations', 'Authentic'],
      description: 'A tiny, lived-in tasca in Alfama where locals and visitors squeeze in for spontaneous Fado nights. No reservations, no tasting menu — just petiscos, wine, and singers who walk in off the street. The teen-friendly Fado experience: short sets, no formality.',
      mustTry: 'Cheese & cured meat board, plus whatever\'s being grilled that night',
      hours: 'Daily 7pm–2am — Fado typically from 8pm',
    },
    {
      name: 'Mar do Inferno (Cascais)',
      rating: 4.5,
      ratingCount: '3.8k',
      price: '€€€',
      tags: ['Seafood', 'Cliffside terrace', 'Cascais day trip'],
      description: 'Set right on the dramatic Boca do Inferno cliffs in Cascais — pick your fish from the iced display, watch the Atlantic crash below while you eat. A long-running family favourite for the seafood-rice and grilled bass. Ideal lunch stop on the Cascais slack day.',
      mustTry: 'Seafood rice (arroz de marisco) and grilled sea bass',
      hours: 'Daily lunch & dinner',
    },
    {
      name: 'Doca Peixe',
      rating: 4.2,
      ratingCount: '3.1k',
      price: '€€€',
      tags: ['Seafood', 'Marina terrace', 'Pre-charter lunch'],
      description: 'A marina-side fish house on Doca de Santo Amaro, right where the charters tie up under the 25 de Abril bridge. Whole fish and shellfish sold by weight off the ice, eaten on a terrace with the bridge roaring overhead. Works either side of a charter: a light plate before boarding, or they will grill your own catch afterwards if the skipper has cleaned it.',
      mustTry: 'Whole grilled robalo (seabass) by weight, and the amêijoas à Bulhão Pato clams',
      hours: 'Daily noon–11pm — book the terrace for a Sunday lunch',
    },
    {
      name: 'El Clan - Restaurante Português',
      rating: 4.7,
      ratingCount: '4.3k',
      price: '€€',
      tags: ['Family-friendly', 'Open late', 'Big portions'],
      description: 'A lively, generous Portuguese restaurant near the cathedral. Big portions of seafood rice, picanha steak, and bacalhau. The padron peppers starter is exceptional. Open all day until midnight — one of the most family-friendly hours in Lisbon.',
      mustTry: 'Padron peppers starter and seafood rice',
      hours: 'Daily 11am–midnight',
    },
    {
      name: 'Floresta das Escadinhas',
      rating: 4.6,
      ratingCount: '3.3k',
      price: '€',
      tags: ['Lunch only', 'Budget gem', 'Best fish platters'],
      description: 'Exceptional value for lunch — the mixed fish and meat platters are enormous and beautifully fresh. One platter easily feeds two adults. The sardines and cod are outstanding. Arrive by 12:30 as it fills quickly. Closed Sundays.',
      mustTry: 'Mixed fish platter and white bean soup',
      hours: 'Mon–Sat, lunch only until 3:30pm',
    },
    {
      name: 'Come Prima',
      rating: 4.9,
      ratingCount: '10k',
      price: '€€',
      tags: ['Best Italian in Lisbon', 'Handmade pasta', 'Book 2 weeks ahead'],
      description: 'The finest Italian restaurant in Lisbon. Handmade pasta, rustic candlelit ambiance, and impeccable service. A special occasion dinner for the family. The wood-fired mushroom starter and trio of pasta are exceptional. Closed Sundays.',
      mustTry: 'Trio of handmade pasta + wood-fired mushrooms starter',
      hours: 'Mon–Sat, dinner only from 6pm',
      bookAhead: true,
    },
    {
      name: 'LUDO\'S',
      rating: 4.9,
      ratingCount: '1.3k',
      price: '€€',
      tags: ['Brunch & café', 'Hidden gem', 'Beautiful food'],
      description: 'A tiny, charming café hidden in the Alfama lanes — perfect for a slow family breakfast or brunch. Beautifully plated food, legendary dragon fruit drinks, and top-quality coffee. Closes at 5pm. A lovely way to start a sightseeing day.',
      mustTry: 'Dragon fruit cocktail and the artisan pastry of the day',
      hours: 'Daily 9am–5pm',
    },
    {
      name: 'World of Heroes',
      rating: 4.2,
      ratingCount: '2k',
      price: '€€',
      tags: ['Kids love it', 'Marvel & anime', 'Fun dinner'],
      description: 'A Marvel and anime-themed restaurant with costumed characters, thousands of collectible figures, and an in-house shop. The food is solid casual fare — not a foodie destination — but the experience is a massive hit with children. Great for a relaxed, fun family dinner night.',
      mustTry: 'Let the kids choose — they\'ll be too excited to care',
      hours: 'Daily lunch & dinner',
    },
  ],
};