import type { PhraseBook } from '../../data/types';

export const phrases: PhraseBook = {
  language: 'European Portuguese',
  nativeName: 'Português',
  speechLang: 'pt-PT',
  intro:
    'European Portuguese swallows its vowels, so a word rarely sounds like it looks. The respellings below are written for an English speaker — read them out loud, CAPITALS take the stress.',
  englishNote:
    'English is widely spoken in Porto and Lisbon hotels, restaurants, and shops, less so in Aveiro markets and with older staff. Opening in Portuguese and then switching to English is always well received.',
  pronunciationKey: [
    { sound: 'final -s, -z', as: 'said "sh"', example: 'pastéis → "pash-TAYSH"' },
    { sound: 'ão', as: 'nasal "owng" — push it through your nose', example: 'não → "nowng"' },
    { sound: 'unstressed e', as: 'almost silent', example: 'verde → "VERD"' },
    { sound: 'final o', as: '"oo"', example: 'obrigado → "oh-bree-GAH-doo"' },
    { sound: 'lh', as: '"ly" as in million', example: 'filho → "FEE-lyoo"' },
    { sound: 'nh', as: '"ny" as in canyon', example: 'banho → "BAH-nyoo"' },
    { sound: 'j, g before e/i', as: '"zh", the s in measure', example: 'gelado → "zheh-LAH-doo"' },
    { sound: 'ç, c before e/i', as: '"s"', example: 'licença → "lee-SEN-sah"' },
    { sound: 'initial r, rr', as: 'throaty, close to a French r', example: 'Ribeira → "rrih-BAY-rah"' },
    { sound: 'ei / ou', as: '"ay" / "oh"', example: 'direita → "dee-RAY-tah"' },
  ],
  categories: [
    {
      id: 'greetings',
      title: 'Hello & goodbye',
      emoji: '👋',
      intro: 'Portuguese greetings switch with the clock, not the person. Use bom dia until lunch, boa tarde until dark, boa noite after.',
      phrases: [
        { en: 'Hello / hi', native: 'Olá', pronunciation: 'oh-LAH' },
        { en: 'Good morning', native: 'Bom dia', pronunciation: 'bong DEE-ah', note: 'Until roughly noon. The default greeting walking into any shop or café.' },
        { en: 'Good afternoon', native: 'Boa tarde', pronunciation: 'BOH-ah TARD', note: 'From lunch until dark.' },
        { en: 'Good evening / good night', native: 'Boa noite', pronunciation: 'BOH-ah NOYT', note: 'Both a greeting and a farewell after dark.' },
        { en: "How's it going?", native: 'Tudo bem?', pronunciation: 'TOO-doo BENG', literal: 'everything well?', note: 'Casual. Answer with the same words as a statement: "Tudo bem."' },
        { en: 'How are you? (polite)', native: 'Como está?', pronunciation: 'KOH-moo shTAH' },
        { en: 'Goodbye', native: 'Adeus', pronunciation: 'ah-DEH-oosh', note: 'A touch final. Até logo is friendlier for anywhere you might return.' },
        { en: 'See you later', native: 'Até logo', pronunciation: 'ah-TEH LOH-goo' },
        { en: 'Nice to meet you', native: 'Muito prazer', pronunciation: 'MOOY-too prah-ZEHR' },
      ],
    },
    {
      id: 'courtesy',
      title: 'Please, thank you & sorry',
      emoji: '🙏',
      phrases: [
        { en: 'Please', native: 'Por favor', pronunciation: 'poor fah-VOR' },
        {
          en: 'Thank you',
          native: 'Obrigada',
          pronunciation: 'oh-bree-GAH-dah',
          note: 'The ending matches the speaker, not the person being thanked: a woman says obrigada, a man says obrigado ("oh-bree-GAH-doo").',
        },
        { en: "You're welcome", native: 'De nada', pronunciation: 'de NAH-dah' },
        { en: 'Yes / no', native: 'Sim / Não', pronunciation: 'seeng / nowng', speak: 'Sim. Não.' },
        { en: 'Sorry / excuse me', native: 'Desculpe', pronunciation: 'dish-KOOLP', note: 'For apologising, and for getting a server or shopkeeper\'s attention.' },
        { en: 'Excuse me (squeezing past)', native: 'Com licença', pronunciation: 'kong lee-SEN-sah', note: 'On a packed tram or metro carriage.' },
        { en: 'No problem', native: 'Não faz mal', pronunciation: 'nowng fash MAL' },
        { en: 'Do you speak English?', native: 'Fala inglês?', pronunciation: 'FAH-lah eeng-GLESH' },
        { en: "I don't speak Portuguese", native: 'Não falo português', pronunciation: 'nowng FAH-loo poor-too-GESH' },
        { en: "I didn't catch that", native: 'Não percebi', pronunciation: 'nowng per-se-BEE', note: 'Percebeu? / percebi is the Portugal usage where Brazil says entendi.' },
        { en: 'Could you repeat that?', native: 'Pode repetir, por favor?', pronunciation: 'POHD rre-pe-TEER, poor fah-VOR' },
        { en: 'Slower, please', native: 'Mais devagar, por favor', pronunciation: 'mysh de-vah-GAR, poor fah-VOR' },
      ],
    },
    {
      id: 'directions',
      title: 'Where is…? What is…?',
      emoji: '🧭',
      intro: 'Onde é asks where something is in general; onde fica asks where it sits on the map. Either works.',
      phrases: [
        { en: 'Where is…?', native: 'Onde é…?', pronunciation: 'OND eh', speak: 'Onde é?' },
        { en: 'Where is the bathroom?', native: 'Onde é a casa de banho?', pronunciation: 'OND eh ah KAH-zah de BAH-nyoo', note: 'Casa de banho in Portugal. Banheiro is Brazilian and will get a puzzled look.' },
        { en: 'Where is the train station?', native: 'Onde fica a estação?', pronunciation: 'OND FEE-kah ah shtah-SOWNG' },
        { en: 'What is this?', native: 'O que é isto?', pronunciation: 'oo kee EH EESH-too', note: 'Useful over a pastry counter or a market stall.' },
        { en: 'What is this called?', native: 'Como se chama isto?', pronunciation: 'KOH-moo se SHAH-mah EESH-too' },
        { en: 'How do you say…?', native: 'Como se diz…?', pronunciation: 'KOH-moo se DEESH', speak: 'Como se diz?' },
        { en: 'Is it far?', native: 'Fica longe?', pronunciation: 'FEE-kah LONZH' },
        { en: 'Is it near here?', native: 'É aqui perto?', pronunciation: 'eh ah-KEE PEHR-too' },
        { en: 'Left / right / straight ahead', native: 'À esquerda / à direita / em frente', pronunciation: 'ah shKEHR-dah / ah dee-RAY-tah / eng FRENT', note: 'What you will hear back when you ask. Listen for these three.' },
        { en: "I'm lost", native: 'Estou perdida', pronunciation: 'shtoh per-DEE-dah', note: 'Perdida if you are a woman, perdido if a man.' },
        { en: 'One ticket to Lisbon, please', native: 'Um bilhete para Lisboa, por favor', pronunciation: 'oong bee-LYET pah-rah leezh-BOH-ah, poor fah-VOR' },
        { en: 'What time does the train leave?', native: 'A que horas parte o comboio?', pronunciation: 'ah kee OH-rash PART oo kong-BOY-oo', note: 'Comboio is the train in Portugal — trem is Brazilian.' },
        { en: 'Does this bus go to…?', native: 'Este autocarro vai para…?', pronunciation: 'ESHT ow-toh-KAH-rroo vye pah-rah', speak: 'Este autocarro vai para o centro?' },
      ],
    },
    {
      id: 'food',
      title: 'Eating out',
      emoji: '🍽️',
      phrases: [
        { en: 'A table for four, please', native: 'Uma mesa para quatro, por favor', pronunciation: 'OO-mah MEH-zah pah-rah KWAH-troo, poor fah-VOR' },
        { en: 'The menu, please', native: 'A ementa, por favor', pronunciation: 'ah ee-MEN-tah, poor fah-VOR', note: 'Ementa is the Portugal word for the menu. Menu usually means a set meal.' },
        { en: "I'd like…", native: 'Queria…', pronunciation: 'keh-REE-ah', literal: 'I would want', note: 'Softer than quero ("I want") and what locals actually say.', speak: 'Queria isto, por favor.' },
        { en: "We don't want the couvert", native: 'Não queremos o couvert', pronunciation: 'nowng keh-REH-moosh oo koo-VEHR', note: 'The bread and olives brought unasked are charged. Declining them is normal and not rude.' },
        { en: 'A half portion, please', native: 'Uma meia dose, por favor', pronunciation: 'OO-mah MAY-ah DOH-ze, poor fah-VOR', note: 'Portuguese portions are large. Meia dose is the standard fix for feeding kids.' },
        { en: 'Still / sparkling water', native: 'Água sem gás / com gás', pronunciation: 'AH-gwah seng GASH / kong GASH' },
        { en: "I'm allergic to…", native: 'Tenho alergia a…', pronunciation: 'TEH-nyoo ah-ler-ZHEE-ah ah', speak: 'Tenho alergia a amendoins.' },
        { en: 'Ice cream', native: 'Gelado', pronunciation: 'zheh-LAH-doo' },
        { en: 'Milky coffee in a glass', native: 'Um galão', pronunciation: 'oong gah-LOWNG', note: 'Order um café and you get an espresso — in Lisbon that is uma bica.' },
        { en: 'To take away', native: 'Para levar', pronunciation: 'pah-rah le-VAR' },
        { en: 'The bill, please', native: 'A conta, por favor', pronunciation: 'ah KON-tah, poor fah-VOR' },
        { en: 'It was delicious', native: 'Estava delicioso', pronunciation: 'shTAH-vah de-lee-see-OH-zoo' },
      ],
    },
    {
      id: 'money',
      title: 'Shopping & prices',
      emoji: '💶',
      intro: 'Portugal writes prices with a comma: €12,50 is twelve euros fifty. Spoken, the comma is just "e" (and).',
      phrases: [
        { en: 'How much is it?', native: 'Quanto custa?', pronunciation: 'KWAN-too KOOSH-tah' },
        { en: 'How much altogether?', native: 'Quanto é ao todo?', pronunciation: 'KWAN-too eh ow TOH-doo' },
        { en: "That's too expensive", native: 'É muito caro', pronunciation: 'eh MOOY-too KAH-roo' },
        { en: 'Do you have a cheaper one?', native: 'Tem mais barato?', pronunciation: 'teng mysh bah-RAH-too' },
        { en: 'Can I pay by card?', native: 'Posso pagar com cartão?', pronunciation: 'POH-soo pah-GAR kong kar-TOWNG' },
        { en: 'Do you have change?', native: 'Tem troco?', pronunciation: 'teng TROH-koo' },
        { en: "I'm just looking, thanks", native: 'Só estou a ver, obrigada', pronunciation: 'soh shtoh ah VER, oh-bree-GAH-dah', note: 'Estou a ver is the Portugal construction; Brazil would say estou vendo.' },
        { en: 'A receipt, please', native: 'A fatura, por favor', pronunciation: 'ah fah-TOO-rah, poor fah-VOR' },
        { en: '€1,50 — one euro fifty', native: 'Um euro e cinquenta', pronunciation: 'oong EH-oo-roo ee seen-KWEN-tah' },
        { en: '€12,50 — twelve fifty', native: 'Doze euros e cinquenta', pronunciation: 'DOHZ EH-oo-roosh ee seen-KWEN-tah' },
        { en: '€25 — twenty-five euros', native: 'Vinte e cinco euros', pronunciation: 'VEEN-tee SEEN-koo EH-oo-roosh' },
        { en: 'Cents', native: 'Cêntimos', pronunciation: 'SEN-tee-moosh' },
      ],
    },
    {
      id: 'numbers',
      title: 'Numbers',
      emoji: '🔢',
      intro: 'Enough to hear a price, a platform number, or a table time. Um/dois change to uma/duas before feminine nouns — duas horas, two hours.',
      layout: 'grid',
      phrases: [
        { en: '0', native: 'zero', pronunciation: 'ZEH-roo' },
        { en: '1', native: 'um / uma', pronunciation: 'oong / OO-mah', speak: 'um' },
        { en: '2', native: 'dois / duas', pronunciation: 'doysh / DOO-ash', speak: 'dois' },
        { en: '3', native: 'três', pronunciation: 'tresh' },
        { en: '4', native: 'quatro', pronunciation: 'KWAH-troo' },
        { en: '5', native: 'cinco', pronunciation: 'SEEN-koo' },
        { en: '6', native: 'seis', pronunciation: 'saysh' },
        { en: '7', native: 'sete', pronunciation: 'SET' },
        { en: '8', native: 'oito', pronunciation: 'OY-too' },
        { en: '9', native: 'nove', pronunciation: 'NOV' },
        { en: '10', native: 'dez', pronunciation: 'desh' },
        { en: '11', native: 'onze', pronunciation: 'ONZ' },
        { en: '12', native: 'doze', pronunciation: 'DOHZ' },
        { en: '13', native: 'treze', pronunciation: 'TREZ' },
        { en: '14', native: 'catorze', pronunciation: 'kah-TORZ' },
        { en: '15', native: 'quinze', pronunciation: 'KEENZ' },
        { en: '16', native: 'dezasseis', pronunciation: 'de-zah-SAYSH' },
        { en: '17', native: 'dezassete', pronunciation: 'de-zah-SET' },
        { en: '18', native: 'dezoito', pronunciation: 'de-ZOY-too' },
        { en: '19', native: 'dezanove', pronunciation: 'de-zah-NOV' },
        { en: '20', native: 'vinte', pronunciation: 'VEENT' },
        { en: '30', native: 'trinta', pronunciation: 'TREEN-tah' },
        { en: '40', native: 'quarenta', pronunciation: 'kwah-REN-tah' },
        { en: '50', native: 'cinquenta', pronunciation: 'seen-KWEN-tah' },
        { en: '60', native: 'sessenta', pronunciation: 'se-SEN-tah' },
        { en: '70', native: 'setenta', pronunciation: 'se-TEN-tah' },
        { en: '80', native: 'oitenta', pronunciation: 'oy-TEN-tah' },
        { en: '90', native: 'noventa', pronunciation: 'noo-VEN-tah' },
        { en: '100', native: 'cem', pronunciation: 'seng' },
        { en: '200', native: 'duzentos', pronunciation: 'doo-ZEN-toosh' },
        { en: '500', native: 'quinhentos', pronunciation: 'kee-NYEN-toosh' },
        { en: '1000', native: 'mil', pronunciation: 'meel' },
      ],
    },
    {
      id: 'family',
      title: 'With the kids',
      emoji: '👨‍👩‍👧‍👦',
      phrases: [
        { en: 'We are four — two adults, two children', native: 'Somos quatro — dois adultos e duas crianças', pronunciation: 'SOH-moosh KWAH-troo, doysh ah-DOOL-toosh ee DOO-ash kree-AN-sash' },
        { en: 'Do you have a high chair?', native: 'Tem cadeira de bebé?', pronunciation: 'teng kah-DAY-rah de be-BEH' },
        { en: 'Is it safe for children?', native: 'É seguro para crianças?', pronunciation: 'eh se-GOO-roo pah-rah kree-AN-sash' },
        { en: 'Is there a family discount?', native: 'Há desconto para famílias?', pronunciation: 'ah dish-KON-too pah-rah fah-MEE-lyash' },
        { en: 'My child is tired', native: 'A minha filha está cansada', pronunciation: 'ah MEE-nyah FEE-lyah shTAH kan-SAH-dah', note: 'O meu filho está cansado for a son.' },
      ],
    },
    {
      id: 'help',
      title: 'If something goes wrong',
      emoji: '🆘',
      intro: 'The emergency number across Portugal is 112 — cento e doze.',
      phrases: [
        { en: 'Help!', native: 'Ajuda!', pronunciation: 'ah-ZHOO-dah' },
        { en: 'I need a doctor', native: 'Preciso de um médico', pronunciation: 'pre-SEE-zoo doong MEH-dee-koo' },
        { en: 'Call the police', native: 'Chame a polícia', pronunciation: 'SHAH-me ah poo-LEE-see-ah' },
        { en: 'Where is the pharmacy?', native: 'Onde fica a farmácia?', pronunciation: 'OND FEE-kah ah far-MAH-see-ah', note: 'Look for the green cross. Pharmacists advise on minor problems without a doctor.' },
        { en: 'I lost my passport', native: 'Perdi o meu passaporte', pronunciation: 'per-DEE oo meu pah-sah-PORT' },
        { en: 'My phone was stolen', native: 'Roubaram-me o telemóvel', pronunciation: 'rroh-BAH-rowng-me oo te-le-MOH-vel', note: 'Telemóvel is the mobile phone in Portugal.' },
        { en: "I don't feel well", native: 'Não me sinto bem', pronunciation: 'nowng me SEEN-too beng' },
      ],
    },
  ],
};
