import type { CityData } from '../../data/types';

export const porto: CityData = {
  name: 'Porto',
  slug: 'porto',
  dates: 'Aug 23 – 28, 2026',
  nights: 5,
  tagline: 'Baroque towers, port wine cellars, the golden Douro & the cradle of Portugal',
  accentColor: '#1B3A6B',
  transport: 'Aug 28 — Pre-9 AM Alfa Pendular train to Lisbon (~3 hrs). Arrive by lunch.',
  mapCenter: { lat: 41.1496, lng: -8.6110 },
  mapZoom: 13,
  mapPoints: [
    { name: 'Praça dos Aliados', type: 'attraction', lat: 41.1496, lng: -8.6109 },
    { name: 'Clérigos Tower', type: 'attraction', lat: 41.1458, lng: -8.6146 },
    { name: 'Livraria Lello', type: 'attraction', lat: 41.1466, lng: -8.6149 },
    { name: 'Igreja do Carmo', type: 'attraction', lat: 41.1469, lng: -8.6164 },
    { name: 'Miradouro da Vitória', type: 'attraction', lat: 41.1437, lng: -8.6160 },
    { name: 'São Bento Station', type: 'attraction', lat: 41.1456, lng: -8.6100 },
    { name: 'Sé do Porto (Cathedral)', type: 'attraction', lat: 41.1431, lng: -8.6112 },
    { name: 'Cais da Ribeira', type: 'attraction', lat: 41.1404, lng: -8.6132 },
    { name: 'Dom Luís I Bridge', type: 'attraction', lat: 41.1398, lng: -8.6094 },
    { name: 'Vila Nova de Gaia Wine Cellars', type: 'attraction', lat: 41.1373, lng: -8.6129 },
    { name: 'Jardim do Morro', type: 'attraction', lat: 41.1380, lng: -8.6094 },
    { name: 'Mercado do Bolhão', type: 'attraction', lat: 41.1488, lng: -8.6080 },
    { name: 'Foz do Douro', type: 'attraction', lat: 41.1486, lng: -8.6726 },
    { name: 'Praia de Matosinhos', type: 'attraction', lat: 41.1852, lng: -8.6896 },
    { name: 'Mercado de Matosinhos', type: 'attraction', lat: 41.1832, lng: -8.6889 },
    { name: 'Castelo de Guimarães', type: 'attraction', lat: 41.4475, lng: -8.2912 },
    { name: 'Paço dos Duques de Bragança', type: 'attraction', lat: 41.4467, lng: -8.2917 },
    { name: 'Largo da Oliveira (Guimarães)', type: 'attraction', lat: 41.4423, lng: -8.2922 },
    { name: 'Penha (Guimarães)', type: 'attraction', lat: 41.4255, lng: -8.2670 },
    { name: 'Pestana Vintage Porto', type: 'hotel', lat: 41.1406, lng: -8.6130 },
    { name: 'Hotel Catalonia Porto', type: 'hotel', lat: 41.1520, lng: -8.5980 },
    { name: 'HF Fénix Porto', type: 'hotel', lat: 41.1540, lng: -8.6310 },
    { name: 'Holiday Inn Express Porto', type: 'hotel', lat: 41.1480, lng: -8.6060 },
    { name: 'Cervejaria Gazela', type: 'restaurant', lat: 41.1470, lng: -8.6080 },
    { name: 'Tito (Matosinhos grill)', type: 'restaurant', lat: 41.1830, lng: -8.6915 },
    { name: 'DAMA pé de cabra', type: 'restaurant', lat: 41.1460, lng: -8.6070 },
    { name: 'Brasão Aliados', type: 'restaurant', lat: 41.1480, lng: -8.6110 },
    { name: 'Restaurante Casa Dias', type: 'restaurant', lat: 41.1370, lng: -8.6120 },
    { name: 'A Tasquinha', type: 'restaurant', lat: 41.1460, lng: -8.6140 },
    { name: 'Restaurante Complô', type: 'restaurant', lat: 41.1450, lng: -8.6100 },
    { name: 'The Door', type: 'restaurant', lat: 41.1510, lng: -8.6240 },
    { name: 'Gelataria Sincelo', type: 'ice-cream', lat: 41.1492, lng: -8.6717 },
  ],

  days: [
    {
      dayNum: 1, date: 'Aug 23 (Sun)', title: 'Arrival & easy first day',
      activities: [
        { description: 'Drop bags at the hotel, grab lunch nearby' },
        { description: 'Walk the Aliados → Clérigos → Livraria Lello → Carmo loop (1–2 km, all flat-ish on top of the hill)', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Pra%C3%A7a+dos+Aliados+Porto+Portugal' },
        { description: 'Sunset at Miradouro da Vitória — free panoramic views over the river', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Miradouro+da+Vit%C3%B3ria+Porto+Portugal' },
        { description: 'Dinner at Cervejaria Gazela — try the famed cachorrinho (Portuguese hot dog) the kids will love', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Cervejaria+Gazela+Porto+Portugal' },
      ],
    },
    {
      dayNum: 2, date: 'Aug 24 (Mon)', title: 'Classic Porto',
      activities: [
        { description: 'Breakfast at Mercado do Bolhão — Mondays it\'s open and lively (closed Sundays)', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Mercado+do+Bolh%C3%A3o+Porto+Portugal' },
        { description: 'São Bento Station — azulejo tile murals (free, ~20 min)', mapUrl: 'https://www.google.com/maps/search/?api=1&query=S%C3%A3o+Bento+Railway+Station+Porto+Portugal' },
        { description: 'Livraria Lello — book a timed entry online to skip the line (€12 pp, refunded against book purchase)', url: 'https://www.livrarialello.pt/', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Livraria+Lello+Porto+Portugal' },
        { description: 'Sé do Porto — the cathedral and viewpoint', mapUrl: 'https://www.google.com/maps/search/?api=1&query=S%C3%A9+do+Porto+Portugal' },
        { description: 'Walk down medieval lanes to Cais da Ribeira for lunch by the water', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Cais+da+Ribeira+Porto+Portugal' },
        { description: 'Cross the lower deck of the Dom Luís I Bridge on foot (upper deck is the metro — kids will think it\'s wild)', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Dom+Lu%C3%ADs+I+Bridge+Porto+Portugal' },
        { description: 'Afternoon in Vila Nova de Gaia: port wine cellar — Graham\'s (best-in-class tour & views), Taylor\'s (gardens & peacocks), or Ferreira (Portuguese-owned). Adults taste, teens get juice or a sip.', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Vila+Nova+de+Gaia+Wine+Cellars+Portugal' },
        { description: 'Cable car ride for fun', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Gaia+Cable+Car+Portugal' },
        { description: 'Sunset picnic at Jardim do Morro in Gaia (top of the bridge) — the magic-hour Porto moment', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Jardim+do+Morro+Vila+Nova+de+Gaia+Portugal' },
      ],
    },
    {
      dayNum: 3, date: 'Aug 25 (Tue)', title: 'Douro Valley day trip ⭐',
      activities: [
        { description: 'Train + boat option: São Bento → Régua (~2 hr scenic), boat upriver to Pinhão, train back. ~€60 pp.', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Pinh%C3%A3o+Douro+Valley+Portugal' },
        { description: 'OR private guided tour with driver: pickup at hotel, 2 quintas, lunch with a view. ~€150 pp but zero logistics — worth it for a family of 4.' },
        { description: 'Quinta do Bomfim in Pinhão — excellent for tastings and a riverside stop', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Quinta+do+Bomfim+Pinh%C3%A3o+Portugal' },
      ],
    },
    {
      dayNum: 4, date: 'Aug 26 (Wed)', title: 'Guimarães day trip ⭐',
      activities: [
        { description: 'Morning train from Porto Campanhã → Guimarães (~1 hr, ~€8 pp). "Aqui Nasceu Portugal" — Portugal was literally founded here in the 12th century.', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Esta%C3%A7%C3%A3o+de+Guimar%C3%A3es+Portugal' },
        { description: 'Castelo de Guimarães — the 10th-century stone keep where Afonso Henriques was born; UNESCO-listed', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Castelo+de+Guimar%C3%A3es+Portugal' },
        { description: 'Paço dos Duques de Bragança — the 15th-century Ducal Palace next door, with Flemish tapestries and the great banqueting hall', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Pa%C3%A7o+dos+Duques+de+Bragan%C3%A7a+Guimar%C3%A3es+Portugal' },
        { description: 'Lunch in the medieval old town around Largo da Oliveira (UNESCO heart) — try Restaurante Cor de Tangerina or a tasca on Rua de Santa Maria', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Largo+da+Oliveira+Guimar%C3%A3es+Portugal' },
        { description: 'Walk the historic centre — Igreja de São Gualter, Largo do Toural, narrow medieval lanes' },
        { description: 'Optional: cable car (Teleférico) up to Penha mountain park for huge views, ~10 min ride', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Penha+Guimar%C3%A3es+Portugal' },
        { description: 'Late afternoon train back to Porto. Easy dinner near hotel.' },
      ],
    },
    {
      dayNum: 5, date: 'Aug 27 (Thu)', title: 'Matosinhos beach + grilling streets ⭐',
      activities: [
        { description: 'Metro Linha A from Trindade → Matosinhos Sul (~25 min, easy with kids)', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Matosinhos+Sul+metro+Porto' },
        { description: 'Morning: Praia de Matosinhos — long Atlantic beach with manageable waves, lifeguards in August, full shower facilities', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Praia+de+Matosinhos+Portugal' },
        { description: 'Lunch on Rua Heróis de França — the legendary "grilling street" where every restaurant runs a charcoal grill on the sidewalk. Tito and Sebastião are local favourites. Arguably the best grilled fish/octopus in northern Portugal.', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Rua+Her%C3%B3is+de+Fran%C3%A7a+Matosinhos+Portugal' },
        { description: 'Afternoon: walk back along the boardwalk through Foz to central Porto (~1 hour) — or metro back if anyone\'s wiped' },
        { description: 'Evening: light dinner near hotel, pack for Lisbon (pre-9 AM Alfa Pendular tomorrow)' },
      ],
    },
  ],

  hotels: [
    {
      name: 'Pestana Vintage Porto',
      rating: 4.7,
      ratingCount: '2.6k',
      price: '€€€',
      priceLabel: 'Splurge',
      tags: ['Douro riverfront', 'Family rooms', 'Spa'],
      description: 'Right on Praça Ribeira with direct river views. The most iconic location in Porto — steps from the Ribeira waterfront, excellent service, and a gorgeous Baroque setting. Book early; rooms with river views sell out months ahead in August.',
      tip: 'Best for: Families who want the most memorable Porto address',
      website: 'https://www.pestana.com',
    },
    {
      name: 'Hotel Catalonia Porto',
      rating: 4.6,
      ratingCount: '995',
      price: '€€',
      priceLabel: 'Mid-range',
      tags: ['Spa & pool', 'Central Bonfim', 'Great breakfast'],
      description: 'Spacious rooms with an excellent breakfast buffet and in-house spa. Centrally located in Bonfim district, a 10-minute walk to the main sights. Hotel offers discounted parking at a nearby multi-storey garage — handy with luggage.',
      tip: 'Best for: Families wanting comfort + spa access at fair value',
      website: 'https://www.cataloniahotels.com',
    },
    {
      name: 'HF Fénix Porto',
      rating: 4.4,
      ratingCount: '2.2k',
      price: '€',
      priceLabel: 'Budget-friendly',
      tags: ['Near Bom Sucesso market', 'Spacious rooms', 'Great value'],
      description: 'Excellent value with consistently clean, spacious rooms and a strong breakfast. A 3-minute walk from the Bom Sucesso food market. Slightly further from the river but Bolt/Uber rides downtown cost around €4. Highly praised by families.',
      tip: 'Best for: Budget-conscious families who want space and quality',
      website: 'https://www.hfhotels.com',
    },
    {
      name: 'Holiday Inn Express Porto City Centre',
      rating: 4.4,
      ratingCount: '891',
      price: '€€',
      priceLabel: 'Mid-range',
      tags: ['Rua de Santa Catarina', 'IHG points', 'Reliable'],
      description: 'Reliable chain comfort on Porto\'s main shopping street. Solid breakfast, central access, and easy metro connections to the airport. Good option if you want the predictability of a well-known brand while being steps from top sights.',
      tip: 'Best for: Families who value a known brand and walkable location',
    },
  ],

  restaurants: [
    {
      name: 'Cervejaria Gazela',
      rating: 4.5,
      ratingCount: '7.2k',
      price: '€',
      tags: ['Cachorrinho', 'Kid-favourite', 'Quick & casual'],
      description: 'Tiny old-school cervejaria famous for the cachorrinho — Porto\'s spicy little hot dog, pressed and sliced into bite-size pieces. Cheap, fast, and a guaranteed kid hit. Pair with a cold imperial. Standing room often spills out the door at peak times.',
      mustTry: 'Cachorrinho special with fries and an imperial',
      hours: 'Daily lunch & dinner',
    },
    {
      name: 'DAMA pé de cabra',
      rating: 4.9,
      ratingCount: '1.4k',
      price: '€€',
      tags: ['Fine Portuguese', 'Tiny gem', 'Must-book'],
      description: 'The best meal most people ever have in Porto. A husband-and-wife team run just 6–8 tables. Owner Álvaro narrates every dish with genuine passion — octopus, tripes, chestnut bread, exceptional wines. An experience, not just a dinner.',
      mustTry: 'Traditional tripe dish, octopus, and the Terra-a-Terra wine',
      hours: 'Tue–Sat lunch & dinner. Closed Mon & Sun.',
      bookAhead: true,
    },
    {
      name: 'Brasão Aliados',
      rating: 4.6,
      ratingCount: '16k',
      price: '€€',
      tags: ['Francesinha', 'Kid-friendly', 'Classic Porto'],
      description: 'The go-to spot for Porto\'s iconic Francesinha — a hearty meat sandwich soaked in beer-tomato sauce, topped with cheese. Kids love the fries. A true Porto rite of passage. Order the half-portion unless you\'re very hungry.',
      mustTry: 'Francesinha (half-portion) + lemon pie dessert',
      hours: 'Daily lunch & dinner',
      bookAhead: true,
    },
    {
      name: 'Restaurante Casa Dias',
      rating: 4.7,
      ratingCount: '2.3k',
      price: '€',
      tags: ['Family-run', 'Riverside Gaia', 'Traditional fish'],
      description: 'A warm, family-run gem on the Gaia waterfront serving exceptional traditional grilled fish at remarkably affordable prices. The grilled sardines, bacalhau, and dourada are outstanding. No reservations — arrive early or prepare to queue.',
      mustTry: 'Grilled sardines and bacalhau (salted cod)',
      hours: 'Tue–Sun. Closed Mon.',
    },
    {
      name: 'A Tasquinha',
      rating: 4.3,
      ratingCount: '2.6k',
      price: '€€',
      tags: ['Traditional taberna', 'Octopus rice', 'Great terrace'],
      description: 'A proper family-run taberna near Rua do Carmo with a lovely outdoor terrace. The octopus and rice is among the best in Porto. Monkfish, seabass, and bacalhau à Braga are all excellent. Relaxed and very welcoming to families.',
      mustTry: 'Octopus rice and monkfish',
      hours: 'Mon–Sat. Closed Sun.',
    },
    {
      name: 'Restaurante Complô',
      rating: 4.4,
      ratingCount: '386',
      price: '€€',
      tags: ['Hidden gem', 'Set lunch menu', 'Creative cuisine'],
      description: 'A charming hidden gem on Praça D. Filipa with an excellent value daily set lunch menu. Bacalhau ao forno, creative salads, and great desserts. Cozy upstairs seating with candles and a relaxed neighbourhood feel.',
      mustTry: 'Bacalhau ao forno and chocolate gelato',
      hours: 'Daily from noon.',
    },
  ],
};