import type { ChecklistCategory } from '../../data/types';

export const checklistData: ChecklistCategory[] = [
  {
    id: 'flights',
    title: 'Flights & Transport',
    emoji: '✈️',
    items: [
      { id: 'flights-yvr-sfo', label: 'Book YVR → SFO one-way for Sun Oct 18', dueBy: 'ASAP', note: 'One-way, not round-trip — the trip ends in Seattle' },
      { id: 'flights-sfo-sea', label: 'Book SFO → SEA one-way for Thu Oct 22', dueBy: 'ASAP', note: 'Morning departure so you land with the afternoon free before SeaGL' },
      { id: 'flights-checkin', label: 'Check in online for both legs' },
      { id: 'flights-sfo-transfer', label: 'Plan SFO → hotel transport (BART or rideshare)' },
      { id: 'ride-home-confirm', label: 'Confirm the Sunday Oct 25 pickup in Seattle', dueBy: 'Oct 2026', note: 'Agree on a meeting point and time — no return flight is booked' },
      { id: 'ride-home-border', label: 'Check Peace Arch / Pacific Highway border wait times before setting off', url: 'https://www.cbsa-asfc.gc.ca/bwt-taf/menu-eng.html' },
      { id: 'ride-home-nexus', label: 'Bring passport (and NEXUS card if you have one) for the drive back' },
    ],
  },
  {
    id: 'accommodation',
    title: 'Accommodation',
    emoji: '🏨',
    items: [
      { id: 'hotel-sf', label: 'Book San Francisco hotel (4 nights, Oct 18–22)', dueBy: 'Aug 2026', note: 'Mission District near the OpenAI office preferred' },
      { id: 'hotel-sea', label: 'Book Seattle hotel (3 nights, Oct 22–25)', dueBy: 'Sep 2026', note: 'U District near the SeaGL venue' },
      { id: 'hotel-confirm', label: 'Confirm both reservations 1 week before departure', dueBy: 'Oct 11' },
    ],
  },
  {
    id: 'sprint',
    title: 'Python Core Dev Sprint (San Francisco)',
    emoji: '🐍',
    items: [
      { id: 'sprint-confirm', label: 'Confirm sprint attendance and logistics' },
      { id: 'sprint-partial', label: 'Tell the organizers you are attending Mon–Wed only', note: 'Flying to Seattle Thursday morning — say so early so they plan sessions around it' },
      { id: 'sprint-openai-access', label: 'Arrange OpenAI office access / badge' },
      { id: 'sprint-laptop', label: 'Ensure laptop and dev environment are set up for sprint work' },
      { id: 'sprint-issues', label: 'Review CPython issues to work on during sprint', url: 'https://github.com/python/cpython/issues' },
      { id: 'sprint-handoff', label: 'Plan a Wednesday wrap-up — hand off anything unfinished before you leave' },
      { id: 'sprint-social', label: 'Check for a sprint dinner or social in the first three days' },
      { id: 'sprint-ice-cream', label: 'Scout ice cream selfie spot near venue 🍦', note: 'Bi-Rite, Humphry Slocombe, Smitten, or Salt & Straw' },
    ],
  },
  {
    id: 'seagl',
    title: 'SeaGL 2026 (Seattle)',
    emoji: '🐧',
    items: [
      { id: 'seagl-cfp', label: 'CFP submitted — watch for the acceptance decision', url: 'https://seagl.org/', note: 'Dates confirmed Oct 23–24 per SeaGL news (Jun 1); CFP extended to Jun 30' },
      { id: 'seagl-talk-prep', label: 'If accepted: confirm room/time slot, then finalize & rehearse the talk' },
      { id: 'seagl-talk-onroad', label: 'Leave rehearsal time during the sprint week — you land in Seattle the day before SeaGL' },
      { id: 'seagl-register', label: 'Register (optional, free) and review the schedule', url: 'https://seagl.org/attend' },
      { id: 'seagl-both-days', label: 'Plan both conference days — Fri Oct 23 and Sat Oct 24' },
      { id: 'seagl-ice-cream', label: 'Scout ice cream selfie spot near venue 🍦', note: "Molly Moon's on The Ave, minutes from the HUB" },
    ],
  },
  {
    id: 'documents',
    title: 'Documents & Travel',
    emoji: '🛂',
    items: [
      { id: 'docs-passport', label: 'Check passport validity', note: 'Needed for US entry and again for the land border on the way home' },
      { id: 'docs-insurance', label: 'Arrange travel insurance (medical, 8 days)', dueBy: 'Sep 2026' },
      { id: 'docs-hotel-pdf', label: 'Save both hotel confirmation PDFs' },
      { id: 'docs-flight-pdf', label: 'Save both flight confirmation PDFs' },
      { id: 'docs-bank-notify', label: 'Notify bank and credit card company of US travel dates', dueBy: 'Oct 2026' },
    ],
  },
  {
    id: 'money-tech',
    title: 'Money & Connectivity',
    emoji: '💳',
    items: [
      { id: 'tech-roaming', label: 'Set up US roaming or eSIM for data (8 days)', dueBy: 'Oct 2026', note: 'Eight days makes an eSIM cheaper than daily carrier passes' },
      { id: 'tech-rideshare', label: 'Ensure Uber/Lyft apps are set up with payment' },
      { id: 'money-clipper', label: 'Get a Clipper card for BART/Muni in SF, or use Apple Pay', url: 'https://www.clippercard.com/' },
      { id: 'tech-orca', label: 'Set up ORCA or contactless tap for Link light rail in Seattle', url: 'https://www.soundtransit.org/ride-with-us/how-to-pay/orca-card' },
      { id: 'money-usd', label: 'Cards work everywhere — bring $50–100 cash for taco stands & tips', note: 'La Taqueria is cash only; a few birria spots are cash-friendly' },
    ],
  },
  {
    id: 'packing',
    title: 'Packing',
    emoji: '🧳',
    items: [
      { id: 'pack-layers', label: 'Layers for both cities — mild SF (15–22°C), cool damp Seattle (8–14°C)', note: 'Medium-weight jacket plus a packable rain shell for the UW campus' },
      { id: 'pack-laptop', label: 'Laptop + charger + peripherals for the sprint' },
      { id: 'pack-talk', label: 'Clicker and display adapters for the SeaGL talk (if the CFP is accepted)' },
      { id: 'pack-adapter', label: 'No plug adapter needed — same as Canada (Type A/B, 120V)' },
      { id: 'pack-shoes', label: 'Comfortable walking shoes (SF hills, then the UW campus)' },
      { id: 'pack-charger', label: 'Portable charger / power bank' },
      { id: 'pack-daypack', label: 'Day backpack for the sprint and the conference' },
      { id: 'pack-eight-days', label: 'Pack for 8 days, one bag — no hotel laundry stop between cities', note: 'Only one flight has a bag transfer, so a checked bag is workable if you need it' },
      { id: 'pack-meds', label: 'Medications and any essentials' },
    ],
  },
  {
    id: 'before-departure',
    title: 'Before Departure',
    emoji: '🏠',
    items: [
      { id: 'pre-fish-fill', label: 'Fill both fish feeders 🐟', note: '8 days away — make sure both hold enough' },
      { id: 'pre-fish-charge', label: 'Charge both fish feeders (or fresh batteries)' },
      { id: 'pre-fish-test', label: 'Test-fire both fish feeders before leaving' },
      { id: 'pre-fish-water', label: 'Top up tank water / run a water change' },
      { id: 'pre-itinerary', label: 'Share the full itinerary with an emergency contact', note: 'Two cities and no return flight — make sure someone has the whole shape of it' },
      { id: 'pre-offline-maps', label: 'Download offline maps for San Francisco and Seattle' },
      { id: 'pre-confirm-48h', label: 'Confirm all bookings 48 hours before departure', dueBy: 'Oct 16' },
    ],
  },
];
