import type { CityData } from '../../data/types';

export const seattle: CityData = {
  name: 'Seattle',
  slug: 'seattle',
  dates: 'Oct 22 – 25, 2026',
  nights: 3,
  tagline: 'SeaGL 2026 — free software on the UW campus, then the drive home',
  accentColor: '#1E7D5F',
  transport: 'Sun Oct 25: getting picked up in Seattle and driving home to Vancouver (~2.5h plus the Peace Arch border crossing). No return flight to book.',
  mapCenter: { lat: 47.6560, lng: -122.3080 },
  mapZoom: 13,

  venue: {
    name: 'Husky Union Building (HUB), University of Washington',
    eventName: 'SeaGL 2026',
    address: 'Husky Union Building (HUB), 4001 E Stevens Way NE, Seattle, WA 98195',
    neighbourhood: 'University District (UW campus)',
    dates: 'Oct 23 – 24, 2026 (attending both days)',
    hours: 'Typically ~9:00 AM – 5:00 PM. Confirm the final schedule on the website.',
    website: 'https://seagl.org/',
    mapUrl: 'https://www.google.com/maps/search/?api=1&query=Husky+Union+Building+University+of+Washington',
    nearestTransit: 'Link light rail — U District or University of Washington station (~10–15 min walk to the HUB). Link also runs straight from SEA airport.',
    accessNotes: 'SeaGL is free to attend and registration is optional. CFP submitted — awaiting a decision. If the talk is accepted, check in at the speaker desk to confirm room and AV.',
    contact: '<a href="https://seagl.org/" target="_blank" rel="noopener">seagl.org</a> · @SeaGL on Mastodon',
    lat: 47.6553,
    lng: -122.3035,
  },

  iceCreamSpots: [
    {
      name: "Molly Moon's Homemade Ice Cream (U District)",
      address: '4555 University Way NE, Seattle, WA 98105',
      signatureFlavors: 'Salted caramel, Scout Mint, honey lavender — local, seasonal Pacific NW flavours',
      photoWorthy: 'Beloved Seattle scoop shop right on The Ave, minutes from the UW campus — easy SeaGL ice cream selfie 🍦',
      mapUrl: 'https://www.google.com/maps/search/?api=1&query=Molly+Moons+University+Way+Seattle',
      website: 'https://www.mollymoon.com',
      lat: 47.6622,
      lng: -122.3137,
    },
    {
      name: 'Frankie & Jo\'s (Capitol Hill)',
      address: '1010 E Pike St, Seattle, WA 98122',
      signatureFlavors: 'Plant-based scoops — Brown Sugar Vanilla, Salty Caramel Ash, Beet Strawberry Rose',
      photoWorthy: 'Cult-favourite vegan creamery with gorgeous swirls — colourful, photogenic cones',
      mapUrl: 'https://www.google.com/maps/search/?api=1&query=Frankie+and+Jos+Capitol+Hill+Seattle',
      website: 'https://www.frankieandjos.com',
      lat: 47.6142,
      lng: -122.3187,
    },
    {
      name: 'Salt & Straw (Capitol Hill)',
      address: '714 E Pike St, Seattle, WA 98122',
      signatureFlavors: 'Sea salt with caramel ribbons, honey lavender, inventive monthly specials',
      photoWorthy: 'Pacific-Northwest design with colourful scoops under glass — always Instagram-ready',
      mapUrl: 'https://www.google.com/maps/search/?api=1&query=Salt+and+Straw+Capitol+Hill+Seattle',
      website: 'https://saltandstraw.com',
      lat: 47.6141,
      lng: -122.3221,
    },
  ],

  mapPoints: [
    { name: 'Husky Union Building (SeaGL)', type: 'attraction', lat: 47.6553, lng: -122.3035 },
    { name: 'University of Washington Quad', type: 'attraction', lat: 47.6571, lng: -122.3080 },
    { name: 'The Ave (University Way NE)', type: 'attraction', lat: 47.6610, lng: -122.3137 },
    { name: 'Washington Park Arboretum', type: 'attraction', lat: 47.6398, lng: -122.2940 },
    { name: 'Gas Works Park', type: 'attraction', lat: 47.6456, lng: -122.3344 },
    { name: 'Pike Place Market', type: 'attraction', lat: 47.6097, lng: -122.3422 },
    { name: "Molly Moon's (U District)", type: 'ice-cream', lat: 47.6622, lng: -122.3137 },
    { name: "Frankie & Jo's (Capitol Hill)", type: 'ice-cream', lat: 47.6142, lng: -122.3187 },
    { name: 'Salt & Straw (Capitol Hill)', type: 'ice-cream', lat: 47.6141, lng: -122.3221 },
    { name: 'Graduate Seattle', type: 'hotel', lat: 47.6585, lng: -122.3138 },
    { name: 'University Inn (Staypineapple)', type: 'hotel', lat: 47.6608, lng: -122.3155 },
    { name: 'Watertown Hotel', type: 'hotel', lat: 47.6615, lng: -122.3156 },
    { name: 'Kizuki Ramen & Izakaya', type: 'restaurant', lat: 47.6612, lng: -122.3137 },
    { name: 'Pho Than Brothers (U District)', type: 'restaurant', lat: 47.6605, lng: -122.3137 },
    { name: "Carmelo's Tacos", type: 'restaurant', lat: 47.6577, lng: -122.3137 },
    { name: 'Portage Bay Cafe (U District)', type: 'restaurant', lat: 47.6533, lng: -122.3155 },
    { name: 'Din Tai Fung (University Village)', type: 'restaurant', lat: 47.6624, lng: -122.2987 },
  ],

  days: [
    {
      dayNum: 1, date: 'Oct 22 (Thu)', title: 'SFO → SEA, settle in',
      activities: [
        { description: 'Land at SEA from San Francisco, Link light rail straight to the U District (~45 min, no transfer)', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Seattle-Tacoma+International+Airport' },
        { description: 'Check in near the UW campus (University District)', mapUrl: 'https://www.google.com/maps/search/?api=1&query=University+District+Seattle' },
        { description: 'Casual dinner on The Ave — ramen at Kizuki Ramen & Izakaya', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Kizuki+Ramen+University+District+Seattle' },
        { description: 'Early night — two full SeaGL days ahead' },
      ],
    },
    {
      dayNum: 2, date: 'Oct 23 (Fri)', title: 'SeaGL 2026 — Day 1',
      activities: [
        { description: 'Pre-conference brunch at Portage Bay Cafe (PNW classic) — get there early to beat the queue', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Portage+Bay+Cafe+University+District+Seattle' },
        { description: 'SeaGL 2026 at the Husky Union Building (HUB) — talks all day (plus your own, if the CFP is accepted)', url: 'https://seagl.org/', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Husky+Union+Building+University+of+Washington' },
        { description: 'Lunch / hallway track — birria & quesabirria at Carmelo\'s Tacos on The Ave 🌮', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Carmelos+Tacos+University+Way+Seattle' },
        { description: "Ice cream selfie at Molly Moon's on The Ave 🍦", mapUrl: 'https://www.google.com/maps/search/?api=1&query=Molly+Moons+University+Way+Seattle' },
        { description: 'Evening: SeaGL social / hallway track dinner with attendees' },
      ],
    },
    {
      dayNum: 3, date: 'Oct 24 (Sat)', title: 'SeaGL 2026 — Day 2',
      activities: [
        { description: 'SeaGL 2026 day two at the HUB — full schedule, closing keynote and hallway track', url: 'https://seagl.org/', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Husky+Union+Building+University+of+Washington' },
        { description: 'Quick warming lunch at Pho Than Brothers on The Ave (free cream puff with every bowl)', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Pho+Than+Brothers+University+District+Seattle' },
        { description: 'Late afternoon: walk the UW Quad and Drumheller Fountain if the rain holds off', mapUrl: 'https://www.google.com/maps/search/?api=1&query=University+of+Washington+Quad' },
        { description: 'Farewell dinner at Din Tai Fung in University Village — xiao long bao after two conference days', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Din+Tai+Fung+University+Village+Seattle' },
        { description: 'Pack tonight — heading home in the morning' },
      ],
    },
    {
      dayNum: 4, date: 'Oct 25 (Sun)', title: 'Drive home to Vancouver',
      activities: [
        { description: 'Breakfast on The Ave, check out of the hotel' },
        { description: 'Optional detour before the highway: Pike Place Market or Gas Works Park', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Pike+Place+Market+Seattle' },
        { description: 'Meet your ride and drive Seattle → Vancouver on I-5 (~2.5h plus the border)', mapUrl: 'https://www.google.com/maps/dir/?api=1&origin=Seattle,WA&destination=Vancouver,BC' },
        { description: 'Peace Arch / Pacific Highway border crossing — check wait times before setting off', url: 'https://www.cbsa-asfc.gc.ca/bwt-taf/menu-eng.html' },
      ],
    },
  ],

  hotels: [
    {
      name: 'Graduate Seattle',
      rating: 4.4,
      ratingCount: '1.6k',
      price: '$$',
      priceLabel: 'Mid-range',
      tags: ['U District', 'Near UW', 'Rooftop bar'],
      description: 'A fun, collegiate-themed hotel right by the UW campus with the Mountaineering Club rooftop bar and skyline views. A short walk to the HUB and The Ave — the closest comfortable base for three SeaGL nights.',
      tip: 'Best for: Closest comfortable base to the SeaGL venue',
      website: 'https://www.graduatehotels.com/seattle',
    },
    {
      name: 'University Inn (Staypineapple)',
      rating: 4.4,
      ratingCount: '1.3k',
      price: '$$',
      priceLabel: 'Mid-range',
      tags: ['U District', 'Friendly', 'Free breakfast'],
      description: 'A cheerful, well-run hotel in the heart of the U District with included breakfast and a free campus-area shuttle. Easy walk to the UW campus and The Ave restaurants — the included breakfast pays off over three mornings.',
      tip: 'Best for: Comfortable, value stay walkable to campus',
      website: 'https://www.staypineapple.com/university-inn-seattle-wa',
    },
    {
      name: 'Watertown Hotel',
      rating: 4.3,
      ratingCount: '1.1k',
      price: '$$',
      priceLabel: 'Mid-range',
      tags: ['U District', 'Modern', 'Bikes available'],
      description: 'A modern boutique hotel a block from the University Inn with spacious rooms and complimentary bikes and shuttle. A solid, quiet option close to the SeaGL venue.',
      tip: 'Best for: A quieter modern room near campus',
      website: 'https://www.staypineapple.com/watertown-hotel-seattle-wa',
    },
  ],

  restaurants: [
    {
      name: 'Kizuki Ramen & Izakaya',
      rating: 4.4,
      ratingCount: '1.4k',
      price: '$$',
      tags: ['Japanese', 'Ramen', 'U District'],
      description: 'Authentic Tokyo-style ramen on The Ave, a short walk from campus. Rich, carefully built broths and izakaya small plates — the perfect warming arrival dinner the night before SeaGL.',
      mustTry: 'Tonkotsu shoyu ramen, spicy miso, karaage',
      hours: 'Daily 11am–10pm',
    },
    {
      name: 'Pho Than Brothers (U District)',
      rating: 4.4,
      ratingCount: '2.0k',
      price: '$',
      tags: ['Vietnamese', 'Pho', 'Cheap eats'],
      description: 'A Seattle pho institution famous for a free complimentary cream puff with every bowl. Fast, cheap, and comforting — great for a quick, warming lunch on a grey Seattle day.',
      mustTry: 'Large beef pho, spring rolls, the free cream puff',
      hours: 'Daily 9am–9pm',
    },
    {
      name: "Carmelo's Tacos",
      rating: 4.5,
      ratingCount: '1.7k',
      price: '$',
      tags: ['Mexican', 'Birria', 'Tacos'],
      description: 'A hugely popular taqueria on The Ave serving fresh tacos including birria and quesabirria — dip the cheesy beef tacos in rich consomé. A fast, satisfying U District lunch between SeaGL sessions.',
      mustTry: 'Birria quesatacos with consomé, al pastor, carne asada',
      hours: 'Daily 11am–9pm',
    },
    {
      name: 'Portage Bay Cafe (U District)',
      rating: 4.5,
      ratingCount: '3.2k',
      price: '$$',
      tags: ['PNW brunch', 'Breakfast', 'Local favourite'],
      description: 'Seattle\'s beloved sustainable brunch spot — organic, local, and famous for its build-your-own breakfast bar of fresh berries and toppings. Get there early before SeaGL to beat the queue.',
      mustTry: 'Buttermilk pancakes with the toppings bar, eggs Benedict',
      hours: 'Daily 7:30am–2pm',
      bookAhead: true,
    },
    {
      name: 'Din Tai Fung (University Village)',
      rating: 4.5,
      ratingCount: '4.1k',
      price: '$$',
      tags: ['Taiwanese', 'Dumplings', 'University Village'],
      description: 'The Taiwanese dumpling house in University Village, a 20-minute walk or short bus ride east of campus. Watch the kitchen pleat xiao long bao through the glass. A comforting sit-down dinner to close out the conference weekend.',
      mustTry: 'Pork xiao long bao, shrimp & pork wontons in chilli oil, garlic green beans',
      hours: 'Daily 11am–9:30pm',
      bookAhead: true,
    },
  ],
};
