import type { CityData } from '../../data/types';

export const cultusLake: CityData = {
  name: 'Cultus Lake',
  slug: 'cultus-lake',
  dates: 'July 10 – 12, 2026',
  nights: 2,
  tagline: 'Fraser Valley lake camping — swims, s\'mores, and alpine hikes',
  accentColor: '#2A7B6C',
  mapCenter: { lat: 49.0583, lng: -121.9853 },
  mapZoom: 12,

  mapPoints: [
    { name: 'Cultus Lake Provincial Park — Entrance Bay', type: 'attraction', lat: 49.0600, lng: -121.9830 },
    { name: 'Cultus Lake Provincial Park — Clear Creek', type: 'attraction', lat: 49.0400, lng: -121.9610 },
    { name: 'Cultus Lake Provincial Park — Maple Bay', type: 'attraction', lat: 49.0420, lng: -121.9680 },
    { name: 'Cultus Lake Provincial Park — Delta Grove', type: 'attraction', lat: 49.0545, lng: -121.9800 },
    { name: 'Cultus Lake Adventure Park', type: 'attraction', lat: 49.0590, lng: -121.9825 },
    { name: 'Cultus Lake Waterpark', type: 'attraction', lat: 49.0595, lng: -121.9830 },
    { name: 'Main Beach (day-use)', type: 'attraction', lat: 49.0605, lng: -121.9810 },
    { name: 'Teapot Hill trailhead', type: 'attraction', lat: 49.0311, lng: -121.9475 },
    { name: 'Bridal Veil Falls Provincial Park', type: 'attraction', lat: 49.1723, lng: -121.7396 },
    { name: 'Cultus Lake Thousand Trails Resort', type: 'hotel', lat: 49.0690, lng: -121.9815 },
    { name: 'Cultus Lake Provincial Park (camping)', type: 'hotel', lat: 49.0550, lng: -121.9780 },
    { name: 'Giggles Restaurant', type: 'restaurant', lat: 49.0596, lng: -121.9829 },
    { name: 'Stella Luna Gelato (Cultus Lake)', type: 'restaurant', lat: 49.0598, lng: -121.9822 },
    { name: 'Chilliwack Save-On-Foods (grocery run)', type: 'restaurant', lat: 49.1579, lng: -121.9519 },
  ],

  days: [
    {
      dayNum: 1, date: 'July 10 (Fri)', title: 'Arrival & Camp Setup',
      activities: [
        { description: 'Drive from home to Cultus Lake (~90 min via Hwy 1 East)', mapUrl: 'https://www.google.com/maps/dir/Vancouver+BC/Cultus+Lake+BC' },
        { description: 'Quick grocery stop in Chilliwack (Save-On-Foods or Real Canadian Superstore) for fresh food, ice, firewood', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Save-On-Foods+Chilliwack' },
        { description: 'Check in at the campground office; set up tent / tarp / kitchen', url: 'https://bcparks.ca/cultus-lake-park/' },
        { description: 'Late afternoon: first swim in the lake — Entrance Bay or Main Beach', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Cultus+Lake+Main+Beach' },
        { description: 'Campfire + dinner + s\'mores — early night after the setup' },
      ],
    },
    {
      dayNum: 2, date: 'July 11 (Sat)', title: 'Full Day — Lake & Play',
      activities: [
        { description: 'Morning swim at the campground beach before the heat' },
        { description: 'Hike Teapot Hill — easy 5 km loop with lake views from the top (park at trailhead early, lot fills up)', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Teapot+Hill+trailhead+Cultus+Lake' },
        { description: 'Lunch back at camp or a picnic on the trail' },
        { description: 'Afternoon at Cultus Lake Adventure Park — waterslides, go-karts, mini-golf (buy a wristband for the kids)', url: 'https://cultus.com/', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Cultus+Lake+Adventure+Park' },
        { description: 'Stella Luna Gelato for an afternoon treat', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Stella+Luna+Gelato+Cultus+Lake' },
        { description: 'Back to camp for dinner, board games, stargazing' },
      ],
    },
    {
      dayNum: 3, date: 'July 12 (Sun)', title: 'Morning Beach & Departure',
      activities: [
        { description: 'Leisurely breakfast at camp (bacon + campfire pancakes)' },
        { description: 'One last swim at Main Beach; paddleboard / kayak rental if the kids want', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Cultus+Lake+paddleboard+rental' },
        { description: 'Pack up camp — aim to check out by 11 AM' },
        { description: 'Optional stop at Bridal Veil Falls on the way home — 10 min easy walk to the falls', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Bridal+Veil+Falls+Provincial+Park' },
        { description: 'Late lunch in Chilliwack or back home; drive back to Vancouver' },
      ],
    },
  ],

  hotels: [
    {
      name: 'Cultus Lake Provincial Park — Entrance Bay Campground',
      rating: 4.4,
      ratingCount: '1.6k',
      price: '$',
      priceLabel: 'Budget-friendly',
      tags: ['Tent / RV camping', 'Walk to beach', 'Family-friendly', 'BC Parks reservation'],
      description: 'The closest BC Parks campground to the main beach and the Cultus Lake village. Popular with families — walk-in access to swimming, mini-golf, and the Adventure Park. Book on Discover Camping 4 months in advance; summer weekends sell out the morning bookings open.',
      tip: 'Best for: Families wanting to be steps from the beach and Adventure Park',
      website: 'https://bcparks.ca/cultus-lake-park/',
    },
    {
      name: 'Cultus Lake Provincial Park — Clear Creek Campground',
      rating: 4.5,
      ratingCount: '920',
      price: '$',
      priceLabel: 'Budget-friendly',
      tags: ['Tent / RV camping', 'Quieter', 'Forested sites', 'BC Parks reservation'],
      description: 'A quieter campground set back in the forest, with larger, more private sites than Entrance Bay. Short drive or bike ride to the main beach. Ideal for families who want the camping feel without the weekend crowd noise. Pit toilets; nearest flush toilet/showers at Maple Bay.',
      tip: 'Best for: Quieter nights and shaded, private sites',
      website: 'https://bcparks.ca/cultus-lake-park/',
    },
    {
      name: 'Cultus Lake Provincial Park — Maple Bay Campground',
      rating: 4.5,
      ratingCount: '1.1k',
      price: '$',
      priceLabel: 'Budget-friendly',
      tags: ['Tent / RV camping', 'Own beach', 'Flush toilets + showers', 'BC Parks reservation'],
      description: 'The largest Cultus Lake campground, with its own sandy beach, swimming area, flush toilets, and hot showers. Big family loops and good space between sites. 10 min drive to the main village and Adventure Park. The easiest option if you want creature comforts.',
      tip: 'Best for: Families who want flush toilets, showers, and their own beach',
      website: 'https://bcparks.ca/cultus-lake-park/',
    },
    {
      name: 'Cultus Lake Thousand Trails Resort',
      rating: 4.0,
      ratingCount: '780',
      price: '$$',
      priceLabel: 'Mid-range',
      tags: ['Private RV park', 'Pool', 'Membership or daily rate'],
      description: 'Private RV and camping resort at the north end of the lake with a pool, planned activities, and full hook-ups. Busier and more commercial than BC Parks — better for RVs or families who want on-site amenities. Membership is common, but daily rates are available for non-members.',
      tip: 'Best for: RV families who want amenities like a pool and activity programs',
      website: 'https://thousandtrails.com/british-columbia/cultus-lake-resort/',
    },
  ],

  restaurants: [
    {
      name: 'Giggles Restaurant',
      rating: 4.0,
      ratingCount: '520',
      price: '$$',
      tags: ['Casual', 'Family-friendly', 'In Cultus Lake village'],
      description: 'Casual, kid-friendly restaurant right in the Cultus Lake village — burgers, fish & chips, salads, and a patio with lake views. Good break from camp cooking if everyone is over the propane stove.',
      mustTry: 'Fish & chips, classic burgers, kids menu',
      hours: 'Seasonal — daily 11am–9pm in summer',
    },
    {
      name: 'Stella Luna Gelato',
      rating: 4.7,
      ratingCount: '680',
      price: '$',
      tags: ['Gelato', 'Village spot', 'After-lake treat'],
      description: 'Artisanal gelato cart / shop in the Cultus Lake village. The after-beach ice cream line is iconic on hot weekends. Rotating flavours — they usually have a dairy-free sorbetto or two.',
      mustTry: 'Pistachio, sea salt caramel, mango sorbetto',
      hours: 'Seasonal — summer afternoons and evenings',
    },
    {
      name: 'Bozzini\'s Restaurant (Chilliwack)',
      rating: 4.3,
      ratingCount: '1.9k',
      price: '$$',
      tags: ['Italian-American', 'Chilliwack', 'Family-friendly'],
      description: 'A Chilliwack classic on the drive home — spacious family restaurant with pasta, steaks, and pizza. Reliable and roomy after a weekend of camp food. About 15 min from Cultus Lake.',
      mustTry: 'Chicken parmesan, Caesar salad, pizza',
      hours: 'Daily 11am–10pm',
    },
  ],
};
