import type { CityData } from '../../data/types';

export const bellingham: CityData = {
  name: 'Bellingham',
  slug: 'bellingham',
  dates: 'Apr 24 – 26, 2026',
  nights: 2,
  tagline: 'Pacific Northwest charm, craft breweries & LinuxFest Northwest',
  accentColor: '#3C3B6E',
  mapCenter: { lat: 48.7519, lng: -122.4787 },
  mapZoom: 13,

  venue: {
    name: 'Bellingham Technical College',
    eventName: 'LinuxFest Northwest 2026',
    address: '3028 Lindbergh Ave, Bellingham, WA 98225, USA',
    neighbourhood: 'North Bellingham',
    dates: 'Apr 24 – 26, 2026 (Fri – Sun) — confirm final dates on the LFNW site',
    hours: 'Typically 9:00 AM – 6:00 PM · Friday often starts later · confirm session schedule closer to event',
    website: 'https://linuxfestnorthwest.org',
    mapUrl: 'https://www.google.com/maps/search/?api=1&query=Bellingham+Technical+College',
    nearestTransit: 'WTA bus route 232 stops near campus · free on-site parking lots for drivers',
    accessNotes: 'Community-run conference — registration is free or low-cost. Pick up your badge at the main entrance. Family-friendly; kids are welcome at most sessions.',
    contact: 'Schedule and announcements at <a href="https://linuxfestnorthwest.org" target="_blank" rel="noopener">linuxfestnorthwest.org</a>',
    lat: 48.7690,
    lng: -122.4850,
  },

  iceCreamSpots: [
    {
      name: 'Mallard Ice Cream',
      address: '1323 Railroad Ave, Bellingham, WA 98225',
      signatureFlavors: 'Lavender, Mexican chocolate, honey lavender, plus a rotating cast of creative seasonal scoops',
      photoWorthy: 'Iconic downtown Bellingham institution — colourful mural wall outside makes an unbeatable backdrop',
      mapUrl: 'https://www.google.com/maps/search/?api=1&query=Mallard+Ice+Cream+Bellingham',
      website: 'https://mallardicecream.com',
      lat: 48.7523,
      lng: -122.4770,
    },
    {
      name: 'Pure Bliss Desserts',
      address: '1424 Cornwall Ave, Bellingham, WA 98225',
      signatureFlavors: 'Homemade ice creams paired with their famous cakes — chocolate, salted caramel, berry',
      photoWorthy: 'Dessert-forward café vibe, warm lighting — great for a post-LFNW evening selfie',
      mapUrl: 'https://www.google.com/maps/search/?api=1&query=Pure+Bliss+Desserts+Bellingham',
      website: 'https://pureblissdesserts.com',
      lat: 48.7525,
      lng: -122.4785,
    },
    {
      name: 'Edaleen Dairy Store',
      address: '5910 Northwest Dr, Ferndale, WA 98248 — short drive from Bellingham',
      signatureFlavors: 'Farm-fresh ice cream made from their own cows — huckleberry, fresh strawberry, cookies & cream',
      photoWorthy: 'Classic red barn and pasture — rural PNW vibe, very different from a conference hall',
      mapUrl: 'https://www.google.com/maps/search/?api=1&query=Edaleen+Dairy+Store+Ferndale',
      website: 'https://edaleendairy.com',
      lat: 48.8490,
      lng: -122.5710,
    },
  ],

  mapPoints: [
    { name: 'Mallard Ice Cream', type: 'ice-cream', lat: 48.7523, lng: -122.4770 },
    { name: 'Pure Bliss Desserts', type: 'ice-cream', lat: 48.7525, lng: -122.4785 },
    { name: 'Whatcom Falls Park', type: 'attraction', lat: 48.7540, lng: -122.4410 },
    { name: 'Boulevard Park / Taylor Dock', type: 'attraction', lat: 48.7310, lng: -122.4980 },
    { name: 'Fairhaven Historic District', type: 'attraction', lat: 48.7210, lng: -122.5030 },
    { name: 'Bellingham Technical College (LFNW venue)', type: 'attraction', lat: 48.7690, lng: -122.4850 },
    { name: 'Bellingham Cruise Terminal', type: 'attraction', lat: 48.7570, lng: -122.5030 },
    { name: 'Downtown Bellingham', type: 'attraction', lat: 48.7519, lng: -122.4787 },
    { name: 'Hotel Bellwether', type: 'hotel', lat: 48.7582, lng: -122.5050 },
    { name: 'Fairhaven Village Inn', type: 'hotel', lat: 48.7215, lng: -122.5020 },
    { name: 'Home2 Suites by Hilton Bellingham', type: 'hotel', lat: 48.7880, lng: -122.4640 },
    { name: 'Hampton Inn Bellingham Airport', type: 'hotel', lat: 48.7920, lng: -122.4580 },
    { name: 'Boundary Bay Brewing', type: 'restaurant', lat: 48.7510, lng: -122.4790 },
    { name: 'Colophon Cafe', type: 'restaurant', lat: 48.7210, lng: -122.5035 },
    { name: 'Rock and Rye Oyster House', type: 'restaurant', lat: 48.7505, lng: -122.4780 },
    { name: 'Fiamma Burger', type: 'restaurant', lat: 48.7515, lng: -122.4775 },
    { name: "Anthony's at Squalicum Harbor", type: 'restaurant', lat: 48.7600, lng: -122.5010 },
  ],

  days: [
    {
      dayNum: 1, date: 'Apr 24', title: 'Drive from Vancouver & LFNW Day 1',
      activities: [
        { description: 'Drive from Vancouver BC to Bellingham (~1.5 hrs including Peace Arch border crossing)', mapUrl: 'https://www.google.com/maps/dir/Vancouver+BC/Bellingham+WA' },
        { description: 'Check in to hotel and settle in' },
        { description: 'LinuxFest Northwest Day 1 at Bellingham Technical College', url: 'https://linuxfestnorthwest.org/', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Bellingham+Technical+College+Bellingham+WA' },
        { description: 'Dinner at Boundary Bay Brewing (downtown brewpub, great burgers and pizza)', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Boundary+Bay+Brewing+Bellingham+WA' },
      ],
    },
    {
      dayNum: 2, date: 'Apr 25', title: 'LFNW Day 2',
      activities: [
        { description: 'LinuxFest Northwest Day 2 — talks, workshops, and expo hall', url: 'https://linuxfestnorthwest.org/', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Bellingham+Technical+College+Bellingham+WA' },
        { description: 'Family outing: Boulevard Park and Taylor Dock boardwalk walk along the bay', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Boulevard+Park+Bellingham+WA' },
        { description: 'Dinner at Rock and Rye Oyster House (fresh Pacific seafood)', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Rock+and+Rye+Oyster+House+Bellingham+WA' },
      ],
    },
    {
      dayNum: 3, date: 'Apr 26', title: 'LFNW Day 3 — Mariatta\'s Talk & Drive Home',
      activities: [
        { description: 'Attend LFNW morning sessions at Bellingham Technical College', url: 'https://linuxfestnorthwest.org/', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Bellingham+Technical+College+Bellingham+WA' },
        { description: 'Lunch at Colophon Cafe in Fairhaven (eclectic menu, great soups)', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Colophon+Cafe+Bellingham+WA' },
        { description: '3:00 PM — Mariatta\'s talk: "No More Spreadsheets" at LinuxFest Northwest', url: 'https://linuxfestnorthwest.org/', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Bellingham+Technical+College+Bellingham+WA' },
        { description: 'Drive back to Vancouver BC via Peace Arch or Pacific Highway crossing (~1.5 hrs)', mapUrl: 'https://www.google.com/maps/dir/Bellingham+WA/Vancouver+BC' },
      ],
    },
  ],

  hotels: [
    {
      name: 'Hotel Bellwether',
      rating: 4.6,
      ratingCount: '1.8k',
      price: '$$$',
      priceLabel: 'Splurge',
      tags: ['Waterfront', 'Squalicum Harbor', 'Luxury'],
      description: 'Bellingham\'s premier waterfront hotel on Squalicum Harbor with stunning bay views. Spacious rooms, fireplaces, and balconies overlooking the marina. Walking distance to the cruise terminal and close to downtown. Request a family room or 2 doubles for comfortable family stay.',
      tip: 'Best for: Families who want the most memorable Bellingham stay with waterfront views',
      website: 'https://hotelbellwether.com',
    },
    {
      name: 'Fairhaven Village Inn',
      rating: 4.5,
      ratingCount: '980',
      price: '$$',
      priceLabel: 'Mid-range',
      tags: ['Fairhaven District', 'Charming', 'Near shops'],
      description: 'Boutique inn in the heart of Fairhaven Historic District, steps from unique shops, cafes, and the waterfront. Comfortable rooms with a warm Pacific Northwest feel. Family rooms or 2 doubles available. Easy drive or bus to BTC for the conference.',
      tip: 'Best for: Families who want to be in walkable, charming Fairhaven',
      website: 'https://fairhavenvillageinn.com',
    },
    {
      name: 'Home2 Suites by Hilton Bellingham',
      rating: 4.4,
      ratingCount: '650',
      price: '$$',
      priceLabel: 'Mid-range',
      tags: ['Suite-style', 'Kitchen', 'Family-friendly'],
      description: 'Modern all-suite hotel with in-room kitchenettes — great for families who want to prepare some meals. Free breakfast, indoor pool, and laundry facilities. Located near the Bellingham airport area with easy freeway access. Family room or 2 doubles available.',
      tip: 'Best for: Families wanting suite-style rooms with kitchen to save on dining',
      website: 'https://www.hilton.com/en/hotels/blihsht-home2-suites-bellingham/',
    },
    {
      name: 'Hampton Inn Bellingham Airport',
      rating: 4.3,
      ratingCount: '520',
      price: '$',
      priceLabel: 'Budget-friendly',
      tags: ['Near I-5', 'Free breakfast', 'Reliable'],
      description: 'Reliable chain hotel near the airport and I-5, offering clean rooms, complimentary hot breakfast, and an indoor pool. A dependable, no-surprises option with Hilton Honors points. Family room or 2 doubles available. About 10 minutes drive to downtown and BTC.',
      tip: 'Best for: Families who want reliable comfort at a fair price',
      website: 'https://www.hilton.com/en/hotels/bliwa-hampton-bellingham-airport/',
    },
  ],

  restaurants: [
    {
      name: 'Boundary Bay Brewing',
      rating: 4.5,
      ratingCount: '4.2k',
      price: '$$',
      tags: ['Brewpub', 'Kid-friendly', 'Downtown'],
      description: 'Bellingham\'s beloved downtown brewpub in a converted warehouse. Award-winning craft beers brewed on-site, plus a full menu of burgers, pizza, salads, and pub fare. Spacious beer garden and indoor seating. Very welcoming to families with a dedicated kids menu.',
      mustTry: 'IPA flight + classic pub burger + kids pizza',
      hours: 'Daily 11am–11pm',
    },
    {
      name: 'Colophon Cafe',
      rating: 4.4,
      ratingCount: '1.1k',
      price: '$',
      tags: ['Fairhaven', 'Eclectic', 'Soups & sandwiches'],
      description: 'A Fairhaven institution tucked inside Village Books. Eclectic menu with excellent soups, sandwiches, and baked goods. Cozy, bookish atmosphere that kids love — grab a book from the shelves while you eat. A perfect lunch stop while exploring Fairhaven.',
      mustTry: 'Soup of the day + grilled sandwich + fresh-baked cookie',
      hours: 'Daily 9am–8pm',
    },
    {
      name: 'Rock and Rye Oyster House',
      rating: 4.5,
      ratingCount: '780',
      price: '$$',
      tags: ['Seafood', 'Craft cocktails', 'Downtown'],
      description: 'Fresh Pacific Northwest seafood in a stylish downtown setting. Locally sourced oysters, fish and chips, clam chowder, and seasonal catches. Great cocktail menu for the adults. More of an evening spot but has options that work for older kids.',
      mustTry: 'Fresh oysters on the half shell + fish and chips',
      hours: 'Tue–Sun 4pm–10pm. Closed Mon.',
    },
    {
      name: 'Fiamma Burger',
      rating: 4.4,
      ratingCount: '1.5k',
      price: '$',
      tags: ['Burgers', 'Casual', 'Quick & delicious'],
      description: 'Gourmet burgers made with local beef and creative toppings in a casual, fast-casual setting. The menu is simple and focused — burgers, fries, shakes. Kids love the straightforward options. One of the best burger spots in the PNW, no exaggeration.',
      mustTry: 'Classic Fiamma Burger + truffle fries + milkshake',
      hours: 'Daily 11am–9pm',
    },
    {
      name: "Anthony's at Squalicum Harbor",
      rating: 4.3,
      ratingCount: '2.1k',
      price: '$$',
      tags: ['Waterfront', 'Seafood', 'Sunset views'],
      description: "Pacific Northwest seafood chain with a fantastic waterfront location at Squalicum Harbor. Floor-to-ceiling windows with marina and bay views. Great for a family dinner with a wide menu — salmon, halibut, fish tacos, and a kids menu. Lovely at sunset.",
      mustTry: 'Wild salmon + clam chowder + key lime pie',
      hours: 'Daily 11:30am–9pm (Fri–Sat until 10pm)',
      bookAhead: true,
    },
  ],
};
