import type { CityData } from '../../data/types';

export const santaMonica: CityData = {
  name: 'Santa Monica',
  slug: 'santa-monica',
  dates: 'Oct 23 – 25, 2026',
  nights: 2,
  tagline: 'PyBeach 2026 — Python by the Pacific after SeaGL',
  accentColor: '#0096C7',
  mapCenter: { lat: 34.0145, lng: -118.4945 },
  mapZoom: 14,

  venue: {
    name: 'Illusion Magic Lounge',
    eventName: 'PyBeach 2026',
    address: '1418 Fourth Street, Santa Monica, CA 90401',
    neighbourhood: 'Downtown Santa Monica',
    dates: 'Saturday, Oct 24, 2026',
    hours: 'Single-day conference — typically ~9:00 AM – 6:00 PM. Confirm final schedule on the website.',
    website: 'https://2026.pybeach.org/',
    mapUrl: 'https://www.google.com/maps/search/?api=1&query=Illusion+Magic+Lounge+1418+Fourth+St+Santa+Monica',
    nearestTransit: 'Metro E Line — Downtown Santa Monica station (~4 blocks). Big Blue Bus serves the whole area.',
    accessNotes: 'Bring your PyBeach ticket (QR from ti.to). A community, volunteer-run conference — check in at the door for your badge. The venue is an intimate magic lounge, so seating is limited; arrive early.',
    contact: 'hello@pybeach.org · <a href="https://2026.pybeach.org/" target="_blank" rel="noopener">2026.pybeach.org</a>',
    lat: 34.0150,
    lng: -118.4957,
  },

  iceCreamSpots: [
    {
      name: "McConnell's Fine Ice Creams",
      address: '1456 Third Street Promenade, Santa Monica, CA 90401',
      signatureFlavors: 'Salted caramel chip, Eureka lemon & marionberries, Turkish coffee — made from scratch in Santa Barbara',
      photoWorthy: 'Right on the Third Street Promenade, ~4 blocks from the venue — the perfect post-conference ice cream selfie 🍦',
      mapUrl: 'https://www.google.com/maps/search/?api=1&query=McConnells+Fine+Ice+Creams+Third+Street+Promenade+Santa+Monica',
      website: 'https://mcconnells.com',
      lat: 34.0167,
      lng: -118.4969,
    },
    {
      name: 'Dolcenero Gelato',
      address: '2400 Main St, Ste A3, Santa Monica, CA 90405',
      signatureFlavors: 'Authentic Italian gelato & sorbetto — pistachio, stracciatella, dark chocolate; house-made waffle cones',
      photoWorthy: 'Charming Main Street gelateria with affogatos — sunny patio backdrop a short stroll from the beach',
      mapUrl: 'https://www.google.com/maps/search/?api=1&query=Dolcenero+Gelato+Main+St+Santa+Monica',
      website: 'http://www.dolcenerogelato.com',
      lat: 34.0078,
      lng: -118.4869,
    },
    {
      name: 'Sweet Rose Creamery',
      address: '225 26th St, Ste 51, Santa Monica, CA 90402 (Brentwood Country Mart)',
      signatureFlavors: 'Seasonal farmers-market flavours — salted caramel, mint chip, house-made cones',
      photoWorthy: 'Rustic Canyon Restaurant Group creamery sourcing from the Santa Monica Farmers Market — country-mart courtyard charm',
      mapUrl: 'https://www.google.com/maps/search/?api=1&query=Sweet+Rose+Creamery+26th+St+Santa+Monica',
      website: 'https://www.sweetrosecreamery.com',
      lat: 34.0335,
      lng: -118.4731,
    },
    {
      name: 'Salt & Straw (Venice)',
      address: '1357 Abbot Kinney Blvd, Venice, CA 90291',
      signatureFlavors: 'Sea salt with caramel ribbons, honey lavender, inventive monthly specials',
      photoWorthy: 'On hip Abbot Kinney — colourful scoops and Pacific-Northwest design, always Instagram-ready (combine with a Venice walk)',
      mapUrl: 'https://www.google.com/maps/search/?api=1&query=Salt+and+Straw+Abbot+Kinney+Venice',
      website: 'https://saltandstraw.com',
      lat: 33.9905,
      lng: -118.4655,
    },
  ],

  mapPoints: [
    { name: 'Illusion Magic Lounge (PyBeach)', type: 'attraction', lat: 34.0150, lng: -118.4957 },
    { name: 'Santa Monica Pier', type: 'attraction', lat: 34.0094, lng: -118.4973 },
    { name: 'Third Street Promenade', type: 'attraction', lat: 34.0167, lng: -118.4961 },
    { name: 'Palisades Park', type: 'attraction', lat: 34.0190, lng: -118.5045 },
    { name: 'Santa Monica State Beach', type: 'attraction', lat: 34.0094, lng: -118.5023 },
    { name: 'Tongva Park', type: 'attraction', lat: 34.0130, lng: -118.4920 },
    { name: 'Venice Beach Boardwalk', type: 'attraction', lat: 33.9850, lng: -118.4695 },
    { name: "McConnell's Fine Ice Creams", type: 'ice-cream', lat: 34.0167, lng: -118.4969 },
    { name: 'Dolcenero Gelato', type: 'ice-cream', lat: 34.0078, lng: -118.4869 },
    { name: 'Sweet Rose Creamery', type: 'ice-cream', lat: 34.0335, lng: -118.4731 },
    { name: 'Salt & Straw (Venice)', type: 'ice-cream', lat: 33.9905, lng: -118.4655 },
    { name: 'The Pierside Hotel', type: 'hotel', lat: 34.0107, lng: -118.4953 },
    { name: 'Hotel Carmel', type: 'hotel', lat: 34.0142, lng: -118.4965 },
    { name: 'Sea Blue Hotel', type: 'hotel', lat: 34.0133, lng: -118.4990 },
    { name: 'Huntley Santa Monica Beach', type: 'hotel', lat: 34.0185, lng: -118.4965 },
    { name: 'JINYA Ramen Bar', type: 'restaurant', lat: 34.0162, lng: -118.4958 },
    { name: 'Cassia', type: 'restaurant', lat: 34.0166, lng: -118.4922 },
    { name: "Teddy's Red Tacos (Venice)", type: 'restaurant', lat: 33.9905, lng: -118.4669 },
    { name: 'Tacos Por Favor', type: 'restaurant', lat: 34.0185, lng: -118.4855 },
    { name: 'Bay Cities Italian Deli', type: 'restaurant', lat: 34.0188, lng: -118.4894 },
  ],

  days: [
    {
      dayNum: 1, date: 'Oct 23 (Fri)', title: 'Late arrival from Seattle',
      activities: [
        { description: 'Land at LAX on the evening flight from SeaGL in Seattle', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Los+Angeles+International+Airport' },
        { description: 'Transfer to Santa Monica (~30–45 min by rideshare, or Metro from LAX)', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Downtown+Santa+Monica' },
        { description: 'Check in to hotel, settle in' },
        { description: 'Late-night birria & quesatacos at Teddy\'s Red Tacos (Venice) if still hungry 🌮', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Teddys+Red+Tacos+Venice' },
      ],
    },
    {
      dayNum: 2, date: 'Oct 24 (Sat)', title: 'PyBeach 2026 🐍🏖️',
      activities: [
        { description: 'PyBeach 2026 at Illusion Magic Lounge — full day of talks', url: 'https://2026.pybeach.org/', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Illusion+Magic+Lounge+Santa+Monica' },
        { description: 'Morning coffee near the Third Street Promenade before the first talk', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Third+Street+Promenade+Santa+Monica' },
        { description: 'Lunch break — quick ramen at JINYA Ramen Bar nearby', mapUrl: 'https://www.google.com/maps/search/?api=1&query=JINYA+Ramen+Bar+Santa+Monica' },
        { description: 'Post-conference ice cream selfie at McConnell\'s on the Promenade 🍦', mapUrl: 'https://www.google.com/maps/search/?api=1&query=McConnells+Fine+Ice+Creams+Third+Street+Promenade+Santa+Monica' },
        { description: 'Hallway track / dinner with the PyBeach community at Cassia', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Cassia+Santa+Monica' },
      ],
    },
    {
      dayNum: 3, date: 'Oct 25 (Sun)', title: 'Beach morning, tacos & departure',
      activities: [
        { description: 'Morning walk along Palisades Park bluffs + the pier', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Palisades+Park+Santa+Monica' },
        { description: 'Early lunch: tacos at Tacos Por Favor (Santa Monica institution) 🌮', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Tacos+Por+Favor+Santa+Monica' },
        { description: 'Last beach stroll on Santa Monica State Beach', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Santa+Monica+State+Beach' },
        { description: 'Head to LAX for the flight home to YVR', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Los+Angeles+International+Airport' },
      ],
    },
  ],

  hotels: [
    {
      name: 'Hotel Carmel',
      rating: 4.2,
      ratingCount: '1.1k',
      price: '$$',
      priceLabel: 'Mid-range',
      tags: ['Downtown', 'Near venue', 'Classic'],
      description: 'A classic 1920s hotel at Broadway & 2nd, about three blocks from the PyBeach venue and right by the Third Street Promenade and pier. Simple, comfortable rooms and an unbeatable walk-everywhere location for a solo conference trip.',
      tip: 'Best for: Walking distance to the venue without splurging',
      website: 'https://www.hotelcarmel.com',
    },
    {
      name: 'The Pierside Hotel',
      rating: 4.3,
      ratingCount: '2.0k',
      price: '$$$',
      priceLabel: 'Splurge',
      tags: ['One block to beach', 'Downtown', 'Renovated'],
      description: 'A freshly renovated hotel one block from the beach and the pier, deep in downtown Santa Monica. Bright coastal rooms, a buzzy lobby, and an easy stroll to the venue, restaurants, and the sand.',
      tip: 'Best for: Beach-and-conference combo with modern rooms',
      website: 'https://www.piersidesantamonica.com',
    },
    {
      name: 'Sea Blue Hotel',
      rating: 4.1,
      ratingCount: '700',
      price: '$',
      priceLabel: 'Budget-friendly',
      tags: ['Ocean Ave', 'Value', 'Solo-friendly'],
      description: 'A small, no-frills hotel on Ocean Avenue a few blocks from the pier. Clean rooms, friendly staff, and great value for downtown Santa Monica — perfect for a solo traveller who plans to be out exploring.',
      tip: 'Best for: Budget-conscious stay still walkable to the venue',
      website: 'https://www.seabluehotel.com',
    },
    {
      name: 'Huntley Santa Monica Beach',
      rating: 4.5,
      ratingCount: '2.6k',
      price: '$$$',
      priceLabel: 'Splurge',
      tags: ['Luxury', 'Rooftop views', 'Near venue'],
      description: 'A modern luxury hotel on 2nd Street with The Penthouse rooftop offering 360° views of the bay. Designer rooms, attentive service, and steps from the Promenade and the PyBeach venue when you feel like treating yourself.',
      tip: 'Best for: A splurge with the best sunset views in town',
      website: 'https://www.thehuntleyhotel.com',
    },
  ],

  restaurants: [
    {
      name: 'JINYA Ramen Bar',
      rating: 4.3,
      ratingCount: '1.5k',
      price: '$$',
      tags: ['Japanese', 'Ramen', 'Near venue'],
      description: 'Reliable, rich tonkotsu ramen minutes from the Third Street Promenade and the PyBeach venue — ideal for a quick, warming lunch break between talks. Plant-based bowls available too.',
      mustTry: 'Tonkotsu Black, spicy umami miso ramen, crispy chicken',
      hours: 'Daily 11am–10pm',
    },
    {
      name: 'Cassia',
      rating: 4.5,
      ratingCount: '2.2k',
      price: '$$$',
      tags: ['Southeast Asian', 'Vietnamese-inspired', 'Group-friendly'],
      description: 'An acclaimed modern Southeast-Asian brasserie in a 1937 Art Deco building — a perfect spot for a post-conference dinner with the PyBeach crowd. Vibrant, shareable Vietnamese- and Singaporean-influenced plates.',
      mustTry: 'Kaya toast, "sunbathing" prawns, Vietnamese pot-au-feu',
      hours: 'Tue–Sun 5pm–10pm. Closed Mon.',
      bookAhead: true,
    },
    {
      name: "Teddy's Red Tacos (Venice)",
      rating: 4.6,
      ratingCount: '3.1k',
      price: '$',
      tags: ['Mexican', 'Birria', 'Tacos'],
      description: 'The LA birria phenomenon — juicy stewed-beef birria tacos and quesatacos served with a cup of rich consomé for dipping. The Venice location is an easy ride from Santa Monica. Cash-friendly, casual, unmissable.',
      mustTry: 'Birria quesatacos with consomé, mulita, birria ramen',
      hours: 'Daily ~10am–9pm (hours vary)',
    },
    {
      name: 'Tacos Por Favor',
      rating: 4.5,
      ratingCount: '2.4k',
      price: '$',
      tags: ['Mexican', 'Tacos', 'Local institution'],
      description: 'A beloved no-frills Santa Monica taqueria serving big, fresh tacos and burritos since the 1990s. A local favourite for a fast, satisfying, wallet-friendly Mexican meal before heading to the airport.',
      mustTry: 'Carne asada tacos, chorizo & egg burrito, shrimp taco',
      hours: 'Mon–Sat 9am–8pm. Closed Sun.',
    },
    {
      name: 'Bay Cities Italian Deli & Bakery',
      rating: 4.6,
      ratingCount: '5.4k',
      price: '$',
      tags: ['Italian deli', 'Sandwiches', 'SM institution'],
      description: 'The legendary Santa Monica deli home of "The Godmother" — a loaded Italian sub on fresh-baked bread. Order ahead online to skip the famous queue. A quintessential Santa Monica lunch-to-go.',
      mustTry: 'The Godmother (with "the works" — hot peppers!), house bread',
      hours: 'Tue–Sun 9am–6pm. Closed Mon.',
    },
  ],
};