import type { CityData } from '../../data/types';

export const longBeach: CityData = {
  name: 'Long Beach',
  slug: 'long-beach',
  dates: 'May 14 – 19, 2026',
  nights: 5,
  tagline: 'PyCon US 2026 — SoCal sunshine, palm trees & Python',
  accentColor: '#3776AB',
  mapCenter: { lat: 33.7683, lng: -118.1956 },
  mapZoom: 13,

  venue: {
    name: 'Long Beach Convention & Entertainment Center',
    eventName: 'PyCon US 2026',
    address: '300 E Ocean Blvd, Long Beach, CA 90802, USA',
    neighbourhood: 'Downtown Long Beach / Waterfront',
    dates: 'May 14 – 19, 2026 (Thu tutorials · Fri–Sun conference · Mon–Tue sprints)',
    hours: 'Conference days typically 8:30 AM – 6:00 PM · keynote mornings start earlier · confirm schedule on the PyCon US site',
    website: 'https://us.pycon.org/2026/',
    mapUrl: 'https://www.google.com/maps/search/?api=1&query=Long+Beach+Convention+Center',
    nearestTransit: 'Metro A Line (Blue) — Downtown Long Beach Station, ~5 min walk · Passport shuttle is free downtown',
    accessNotes: 'Pick up badge at on-site registration. Bring government-issued photo ID. Speaker check-in is typically the day before your talk — confirm with PyCon programme team.',
    contact: 'Schedule, session list, and speaker info at <a href="https://us.pycon.org/2026/" target="_blank" rel="noopener">us.pycon.org/2026</a>',
    lat: 33.7627,
    lng: -118.1892,
  },

  iceCreamSpots: [
    {
      name: 'Long Beach Creamery',
      address: '4141 Long Beach Blvd, Long Beach, CA 90807',
      signatureFlavors: 'Small-batch organic flavours — honey lavender, salted caramel, Mexican chocolate, seasonal fruit scoops',
      photoWorthy: 'Long Beach\'s beloved indie creamery — murals out front and retro shop vibes make for a great selfie',
      mapUrl: 'https://www.google.com/maps/search/?api=1&query=Long+Beach+Creamery',
      website: 'https://longbeachcreamery.com',
      lat: 33.8157,
      lng: -118.1890,
    },
    {
      name: 'Handel\'s Homemade Ice Cream (Long Beach)',
      address: '5138 E 2nd St, Long Beach, CA 90803 (Belmont Shore)',
      signatureFlavors: 'Graham central station, banana cream pie, Guinness chocolate — rich, hand-dipped scoops made fresh daily',
      photoWorthy: 'Belmont Shore\'s buzziest ice cream spot — line out the door, bright pink-and-white sign, 2nd Street backdrop',
      mapUrl: 'https://www.google.com/maps/search/?api=1&query=Handel%27s+Ice+Cream+Long+Beach+2nd+Street',
      website: 'https://handelsicecream.com',
      lat: 33.7601,
      lng: -118.1293,
    },
    {
      name: 'Romeo Chocolates',
      address: '140 Linden Ave, Long Beach, CA 90802 (East Village)',
      signatureFlavors: 'Artisan gelato alongside handmade chocolates — pistachio, hazelnut, stracciatella',
      photoWorthy: 'Tiny, jewel-box chocolate shop tucked into East Village — walkable from the convention centre for a post-talk treat',
      mapUrl: 'https://www.google.com/maps/search/?api=1&query=Romeo+Chocolates+Long+Beach',
      website: 'https://romeochocolates.com',
      lat: 33.7697,
      lng: -118.1883,
    },
    {
      name: 'Afters Ice Cream (Long Beach)',
      address: '5305 E 2nd St, Long Beach, CA 90803',
      signatureFlavors: 'Milky bun (ice cream stuffed donut), cookie monster, milk & cereal — Instagram-bait Korean-American creations',
      photoWorthy: 'The milky bun is the shot — pastel walls, huge scoops in a warm donut. Purpose-built for the selfie.',
      mapUrl: 'https://www.google.com/maps/search/?api=1&query=Afters+Ice+Cream+Long+Beach',
      website: 'https://aftersicecream.com',
      lat: 33.7603,
      lng: -118.1280,
    },
  ],

  mapPoints: [
    { name: 'Long Beach Convention Center (PyCon venue)', type: 'attraction', lat: 33.7627, lng: -118.1892 },
    { name: 'Aquarium of the Pacific', type: 'attraction', lat: 33.7620, lng: -118.1973 },
    { name: 'The Queen Mary', type: 'attraction', lat: 33.7525, lng: -118.1903 },
    { name: 'Shoreline Village', type: 'attraction', lat: 33.7602, lng: -118.1915 },
    { name: 'Pine Avenue (dining)', type: 'attraction', lat: 33.7683, lng: -118.1925 },
    { name: 'Belmont Shore / 2nd Street', type: 'attraction', lat: 33.7610, lng: -118.1290 },
    { name: 'Naples Island Canals', type: 'attraction', lat: 33.7540, lng: -118.1190 },
    { name: 'East Village Arts District', type: 'attraction', lat: 33.7705, lng: -118.1870 },
    { name: 'Long Beach Creamery', type: 'ice-cream', lat: 33.8157, lng: -118.1890 },
    { name: 'Handel\'s Ice Cream (Belmont Shore)', type: 'ice-cream', lat: 33.7601, lng: -118.1293 },
    { name: 'Romeo Chocolates', type: 'ice-cream', lat: 33.7697, lng: -118.1883 },
    { name: 'Afters Ice Cream', type: 'ice-cream', lat: 33.7603, lng: -118.1280 },
    { name: 'Hyatt Regency Long Beach', type: 'hotel', lat: 33.7635, lng: -118.1928 },
    { name: 'Marriott Long Beach Downtown', type: 'hotel', lat: 33.7685, lng: -118.1920 },
    { name: 'The Westin Long Beach', type: 'hotel', lat: 33.7670, lng: -118.1945 },
    { name: 'Courtyard by Marriott Long Beach Downtown', type: 'hotel', lat: 33.7680, lng: -118.1937 },
    { name: 'The Breakfast Bar', type: 'restaurant', lat: 33.7865, lng: -118.1880 },
    { name: 'L\'Opera Ristorante', type: 'restaurant', lat: 33.7697, lng: -118.1923 },
    { name: 'James Republic', type: 'restaurant', lat: 33.7680, lng: -118.1937 },
    { name: 'George\'s Greek Cafe', type: 'restaurant', lat: 33.7690, lng: -118.1923 },
    { name: 'Roe Seafood', type: 'restaurant', lat: 33.7628, lng: -118.1923 },
  ],

  days: [
    {
      dayNum: 1, date: 'May 14 (Thu)', title: 'Arrival & PyCon Check-in',
      activities: [
        { description: 'Fly YVR to LAX (~3 hrs direct) — or LGB if schedule works', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Los+Angeles+International+Airport' },
        { description: 'Transfer to Long Beach — rideshare (~$45–60) or FlyAway bus + Metro', mapUrl: 'https://www.google.com/maps/dir/LAX/Long+Beach+CA' },
        { description: 'Check in to hotel near the convention centre' },
        { description: 'PyCon registration & badge pickup at Long Beach Convention Center (if open Thursday)', url: 'https://us.pycon.org/2026/', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Long+Beach+Convention+Center' },
        { description: 'Evening stroll along Shoreline Village and the waterfront', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Shoreline+Village+Long+Beach' },
        { description: 'Dinner on Pine Avenue — George\'s Greek Cafe or L\'Opera Ristorante', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Pine+Avenue+Long+Beach' },
      ],
    },
    {
      dayNum: 2, date: 'May 15 (Fri)', title: 'PyCon Day 1 — Opening Keynote',
      activities: [
        { description: 'Breakfast at the hotel or grab coffee at Rose Park Roasters', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Rose+Park+Roasters+Long+Beach' },
        { description: 'PyCon US 2026 Day 1 — opening keynote + conference talks', url: 'https://us.pycon.org/2026/schedule/', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Long+Beach+Convention+Center' },
        { description: 'Lunch at the convention centre or nearby East Village eateries' },
        { description: 'Afternoon talks + hallway track — connect with the Python community' },
        { description: 'Evening: PyLadies auction or opening reception (check PyCon schedule)' },
        { description: 'Late-night scoop at Romeo Chocolates gelato in East Village (ice cream selfie! 🍦)', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Romeo+Chocolates+Long+Beach' },
      ],
    },
    {
      dayNum: 3, date: 'May 16 (Sat)', title: 'PyCon Day 2 — Mariatta\'s Talk! 🎤',
      activities: [
        { description: 'Early breakfast — light, nothing heavy before the talk' },
        { description: 'Final run-through of talk slides and demo setup' },
        { description: 'Arrive early at the convention centre — speaker check-in + AV test', url: 'https://us.pycon.org/2026/', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Long+Beach+Convention+Center' },
        { description: '🎤 12:00–12:45 PM — Mariatta speaks: "No More Spreadsheets! Building PyLadiesCon Infrastructure with Python and Django" · Grand Ballroom A', url: 'https://us.pycon.org/2026/schedule/presentation/80/' },
        { description: 'Celebrate at Long Beach Creamery after the talk 🍦', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Long+Beach+Creamery' },
        { description: 'Afternoon talks + meet attendees who showed up to the session' },
        { description: 'Evening: PyCon conference dinner or Python community social' },
      ],
    },
    {
      dayNum: 4, date: 'May 17 (Sun)', title: 'PyCon Day 3 — Closing & Lightning Talks',
      activities: [
        { description: 'PyCon US 2026 Day 3 — closing keynote + final talks', url: 'https://us.pycon.org/2026/schedule/', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Long+Beach+Convention+Center' },
        { description: 'Lightning talks — always a PyCon highlight' },
        { description: 'Brunch break at The Breakfast Bar in Bixby Knolls', mapUrl: 'https://www.google.com/maps/search/?api=1&query=The+Breakfast+Bar+Long+Beach' },
        { description: 'Visit the Aquarium of the Pacific — walkable from the convention centre', url: 'https://www.aquariumofpacific.org/', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Aquarium+of+the+Pacific+Long+Beach' },
        { description: 'Closing reception / goodbye mixer with PyCon folks' },
      ],
    },
    {
      dayNum: 5, date: 'May 18 (Mon)', title: 'Sprint Day + Transfer to LAX Hotel',
      activities: [
        { description: 'Check out of Long Beach hotel after breakfast; store bags at the convention centre' },
        { description: 'PyCon Sprints — open-source contribution sessions at the convention centre', url: 'https://us.pycon.org/2026/events/sprints/', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Long+Beach+Convention+Center' },
        { description: 'Work on CPython issues, help first-time contributors', url: 'https://github.com/python/cpython/issues' },
        { description: 'Final goodbyes with the Python core + PyLadies crew' },
        { description: 'Late afternoon: Uber/Lyft from Long Beach to LAX-area hotel (~45 min with traffic)', mapUrl: 'https://www.google.com/maps/dir/Long+Beach+Convention+Center/LAX' },
        { description: 'Check in to airport hotel; unwind after a long conference' },
        { description: 'Dinner near LAX — hotel restaurant or walk to Century Blvd options' },
      ],
    },
    {
      dayNum: 6, date: 'May 19 (Tue)', title: 'Work from Hotel + Evening Flight Home',
      activities: [
        { description: 'Work-from-hotel day — catch up on email, async work, post-PyCon follow-ups' },
        { description: 'Use hotel workspace + coffee; grab lunch nearby on Century Blvd' },
        { description: 'Late afternoon: check out; hotel shuttle or short Uber to LAX terminal', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Los+Angeles+International+Airport' },
        { description: 'Evening flight YVR-bound — arrive home late (~3 hrs in the air + time zone home)' },
      ],
    },
  ],

  hotels: [
    {
      name: 'Hyatt Regency Long Beach',
      rating: 4.4,
      ratingCount: '4.2k',
      price: '$$$',
      priceLabel: 'Splurge',
      tags: ['Conference stay · Thu–Mon', 'Connected to convention centre', 'Waterfront', 'PyCon host hotel'],
      description: 'The official PyCon host hotel, directly connected to the Long Beach Convention Center via the Rainbow Lagoon walkway. Spacious rooms with bay or city views, outdoor pool, and on-site dining. Zero-commute to the venue — step out of your room and onto the conference floor. Book inside the PyCon room block for the conference rate.',
      tip: 'Best for: Speakers who want zero-minute commute on talk day',
      website: 'https://www.hyatt.com/en-US/hotel/california/hyatt-regency-long-beach/lgbrl',
    },
    {
      name: 'Marriott Long Beach Downtown',
      rating: 4.3,
      ratingCount: '1.5k',
      price: '$$$',
      priceLabel: 'Splurge',
      tags: ['Conference stay · Thu–Mon', 'PyCon block', 'Downtown', 'Walkable to venue'],
      description: 'Full-service Marriott in downtown Long Beach, part of the PyCon US 2026 room block. Short walk to the convention centre, close to Pine Avenue dining and the waterfront. Reliable Bonvoy option with a pool, on-site dining, and comfortable rooms. Book inside the PyCon block for the conference rate.',
      tip: 'Best for: Bonvoy loyalists who want a walkable downtown stay inside the PyCon block',
      website: 'https://www.marriott.com/',
    },
    {
      name: 'The Westin Long Beach',
      rating: 4.3,
      ratingCount: '3.6k',
      price: '$$$',
      priceLabel: 'Splurge',
      tags: ['Conference stay · Thu–Mon', '2 min walk to venue', 'Heavenly Bed', 'Reliable'],
      description: 'Reliable Westin right next to the convention centre — a classic conference pick. Heavenly Bed, heated pool, and a lobby Starbucks. Standard rooms are comfortable if not flashy; the location does the heavy lifting. Frequently in the PyCon room block.',
      tip: 'Best for: Bonvoy loyalists who want the convention rate',
      website: 'https://www.marriott.com/hotels/travel/lgbwi-the-westin-long-beach/',
    },
    {
      name: 'Courtyard by Marriott Long Beach Downtown',
      rating: 4.3,
      ratingCount: '1.9k',
      price: '$$',
      priceLabel: 'Mid-range',
      tags: ['Conference stay · Thu–Mon', '3 min walk to venue', 'Good value', 'Breakfast available'],
      description: 'Solid mid-range Marriott option 3 minutes on foot from the convention centre. Home to James Republic restaurant for breakfast and dinner. Clean rooms, smaller footprint than the Hyatt/Westin but a noticeably better price point. Great value for a solo traveller.',
      tip: 'Best for: Solo budget-conscious traveller who still wants to be steps from the venue',
      website: 'https://www.marriott.com/hotels/travel/lgbdt-courtyard-long-beach-downtown/',
    },
  ],

  restaurants: [
    {
      name: 'James Republic',
      rating: 4.3,
      ratingCount: '680',
      price: '$$',
      tags: ['American', 'Farm-to-table', 'Inside Courtyard Marriott'],
      description: 'Chef-driven American bistro inside the Courtyard Marriott, steps from the convention centre. Solid farm-to-table menu — great for a quick, reliable breakfast before a conference day or a sit-down dinner after. Solo-friendly bar seating.',
      mustTry: 'Short rib hash, avocado toast, bar burger',
      hours: 'Daily 6:30am–10pm',
    },
    {
      name: 'L\'Opera Ristorante',
      rating: 4.4,
      ratingCount: '1.1k',
      price: '$$$',
      tags: ['Italian', 'Pine Avenue', 'Date-night quality'],
      description: 'White-tablecloth Italian on Pine Avenue inside a historic brick building. Handmade pastas, proper risotto, and a serious wine list. A bit special-occasion — perfect for a celebratory post-talk dinner. Bar seating welcomes solo diners.',
      mustTry: 'Lobster ravioli, osso buco, tiramisu',
      hours: 'Daily 5pm–10pm',
      bookAhead: true,
    },
    {
      name: 'George\'s Greek Cafe',
      rating: 4.3,
      ratingCount: '2.4k',
      price: '$$',
      tags: ['Greek', 'Pine Avenue', 'Casual'],
      description: 'Long-running Pine Avenue staple serving solid Greek classics — gyros, souvlaki, moussaka, and big Greek salads. Patio seating is lovely in May. A safe, welcoming pick for a quick and hearty dinner between conference sessions.',
      mustTry: 'Lamb gyro, chicken souvlaki plate, spanakopita',
      hours: 'Daily 11am–10pm',
    },
    {
      name: 'The Breakfast Bar',
      rating: 4.5,
      ratingCount: '2.1k',
      price: '$$',
      tags: ['Brunch', 'Bixby Knolls', 'Long Beach icon'],
      description: 'Long Beach\'s go-to brunch spot, a short rideshare north in Bixby Knolls. Inventive takes on breakfast classics — chicken and waffles, crab cakes benedict, shrimp & grits. Worth the trip on a sprint break morning.',
      mustTry: 'Chicken & waffles, crab cakes benedict, PB&J French toast',
      hours: 'Daily 7am–3pm',
    },
    {
      name: 'Roe Seafood',
      rating: 4.4,
      ratingCount: '1.5k',
      price: '$$$',
      tags: ['Seafood', 'Waterfront', 'Shoreline Village'],
      description: 'Elevated seafood restaurant on the Shoreline Village waterfront with Queen Mary views across the bay. Oysters, cioppino, and seasonal catches. Sunset dinner here is a Long Beach essential. Bar seating is great for solo diners.',
      mustTry: 'Half-dozen oysters, cioppino, grilled local catch',
      hours: 'Daily 4pm–10pm (lunch Fri–Sun from 11am)',
      bookAhead: true,
    },
  ],
};