import type { ChecklistCategory } from '../../data/types';

export const checklistData: ChecklistCategory[] = [
  {
    id: 'flights',
    title: 'Flights & Transport',
    emoji: '✈️',
    items: [
      { id: 'flights-book', label: 'Book YVR to TPE round-trip flights (family of 4)', dueBy: 'ASAP' },
      { id: 'flights-tra-hualien', label: 'Book TRA train Taipei to Hualien (Aug 27)', dueBy: 'Jun 2026', url: 'https://www.railway.gov.tw/en/' },
      { id: 'flights-tra-taichung', label: 'Book TRA train Hualien to Taichung (Aug 29)', dueBy: 'Jun 2026' },
      { id: 'flights-thsr-tainan', label: 'Book THSR Taichung to Tainan (Aug 31)', dueBy: 'Jun 2026', url: 'https://www.thsrc.com.tw/en/' },
      { id: 'flights-thsr-kaohsiung', label: 'Book THSR Tainan to Kaohsiung (Sep 2)', dueBy: 'Jun 2026' },
      { id: 'flights-thsr-airport', label: 'Book THSR Kaohsiung to Taoyuan for departure (Sep 5)', dueBy: 'Jun 2026' },
    ],
  },
  {
    id: 'accommodation',
    title: 'Accommodation',
    emoji: '🏨',
    items: [
      { id: 'hotel-taipei', label: 'Book Taipei hotel (5 nights, Aug 22–27)', dueBy: 'May 2026' },
      { id: 'hotel-hualien', label: 'Book Hualien hotel (2 nights, Aug 27–29)', dueBy: 'May 2026' },
      { id: 'hotel-sunmoon', label: 'Book Sun Moon Lake accommodation (1 night, Aug 29–30)', dueBy: 'May 2026' },
      { id: 'hotel-taichung', label: 'Book Taichung hotel (1 night, Aug 30–31)', dueBy: 'May 2026' },
      { id: 'hotel-tainan', label: 'Book Tainan hotel (2 nights, Aug 31–Sep 2)', dueBy: 'May 2026' },
      { id: 'hotel-kaohsiung', label: 'Book Kaohsiung hotel (3 nights, Sep 2–5)', dueBy: 'May 2026' },
      { id: 'hotel-confirm', label: 'Confirm all hotel reservations 2 weeks before departure', dueBy: 'Aug 8' },
    ],
  },
  {
    id: 'documents',
    title: 'Documents & Insurance',
    emoji: '🛂',
    items: [
      { id: 'docs-passports', label: 'Check passport validity for all 4 family members', note: 'Must be valid 6+ months past Sep 5, 2026' },
      { id: 'docs-insurance', label: 'Arrange travel insurance (medical, trip cancellation)', dueBy: 'Jul 2026' },
      { id: 'docs-entry-reqs', label: 'Check Canada–Taiwan entry requirements', note: 'Canadians get 90-day visa-free entry. Verify before travel.' },
      { id: 'docs-hotel-pdfs', label: 'Print or save hotel confirmation PDFs' },
      { id: 'docs-train-pdfs', label: 'Print or save train ticket PDFs' },
      { id: 'docs-flight-pdfs', label: 'Print or save flight confirmation PDFs' },
      { id: 'docs-bank-notify', label: 'Notify bank and credit card company of Taiwan travel dates', dueBy: 'Aug 2026' },
    ],
  },
  {
    id: 'bookings',
    title: 'Activities & Bookings',
    emoji: '🎫',
    items: [
      { id: 'book-101', label: 'Book Taipei 101 Observatory tickets online', dueBy: 'Jul 2026', url: 'https://www.taipei-101.com.tw/en/' },
      { id: 'book-palace', label: 'Check National Palace Museum reservation requirements', url: 'https://www.npm.gov.tw/en/' },
      { id: 'book-taroko', label: 'Research Taroko Gorge tour/driver options', dueBy: 'Jul 2026' },
      { id: 'book-dintaifung', label: 'Reserve Din Tai Fung (Xinyi) — or plan to queue' },
      { id: 'book-sunmoon-bikes', label: 'Research Sun Moon Lake bike rental options' },
    ],
  },
  {
    id: 'money-tech',
    title: 'Money & Connectivity',
    emoji: '💳',
    items: [
      { id: 'tech-esim', label: 'Order or activate an eSIM or local SIM for data', dueBy: 'Aug 2026' },
      { id: 'tech-rideshare', label: 'Download Uber app (available in Taiwan)' },
      { id: 'money-twd', label: 'Plan TWD cash — withdraw from ATMs on arrival', note: 'Night markets and small vendors are cash-only. 7-Eleven ATMs work well.' },
      { id: 'money-easycard', label: 'Get EasyCard transit cards at airport MRT station', note: 'Works on MRT, buses, convenience stores, and some taxis' },
      { id: 'money-credit', label: 'Bring a no-FX-fee credit card for hotels and restaurants' },
    ],
  },
  {
    id: 'packing',
    title: 'Packing',
    emoji: '🧳',
    items: [
      { id: 'pack-shoes', label: 'Comfortable walking shoes (temples, gorges, night markets)' },
      { id: 'pack-rain', label: 'Rain jacket or compact umbrella (typhoon season)', note: 'August is peak typhoon/rain season in Taiwan' },
      { id: 'pack-sunscreen', label: 'Sunscreen SPF 50 — Taiwan is hot and humid in August' },
      { id: 'pack-hat', label: 'Sun hat and sunglasses' },
      { id: 'pack-swimwear', label: 'Swimwear (hot springs, beaches)' },
      { id: 'pack-light', label: 'Light, breathable clothing (30°C+ with high humidity)' },
      { id: 'pack-charger', label: 'Portable charger / power bank' },
      { id: 'pack-water', label: 'Refillable water bottles (tap water is NOT safe to drink — buy bottled)' },
      { id: 'pack-daypack', label: 'Day backpack' },
      { id: 'pack-kids-flight', label: 'Kids\' entertainment for flights (tablets, books, snacks)' },
      { id: 'pack-meds', label: 'Medications and first-aid kit' },
      { id: 'pack-adapter', label: 'Power adapter — Taiwan uses Type A/B (same as North America, 110V)', note: 'Canadian plugs work without adapter!' },
    ],
  },
  {
    id: 'before-departure',
    title: 'Before Departure',
    emoji: '🏠',
    items: [
      { id: 'pre-fish-fill', label: 'Fill both fish feeders 🐟' },
      { id: 'pre-fish-charge', label: 'Charge both fish feeders (or fresh batteries)' },
      { id: 'pre-fish-test', label: 'Test-fire both fish feeders before leaving' },
      { id: 'pre-fish-water', label: 'Top up tank water / run a water change' },
      { id: 'pre-lights', label: 'Set home lights on timers' },
      { id: 'pre-itinerary', label: 'Share itinerary with an emergency contact' },
      { id: 'pre-offline-maps', label: 'Download offline Google Maps for all cities in Taiwan' },
      { id: 'pre-translate', label: 'Download Google Translate offline for Mandarin Chinese' },
      { id: 'pre-confirm-48h', label: 'Confirm all bookings 48 hours before departure', dueBy: 'Aug 20' },
    ],
  },
];