import type { CityData } from '../../data/types';

export const hualienData: CityData = {
  name: 'Hualien',
  slug: 'hualien',
  dates: 'Aug 27–29',
  nights: 2,
  tagline: 'Taroko Gorge and Pacific coastline',
  accentColor: '#2E7D32',
  transport: 'Take the TRA train to Taichung (~3.5 hours), then bus to Sun Moon Lake',
  mapCenter: { lat: 23.991, lng: 121.601 },
  mapZoom: 12,
  mapPoints: [
    { name: 'Taroko Gorge', type: 'attraction', lat: 24.1585, lng: 121.4949 },
    { name: 'Qingshui Cliffs', type: 'attraction', lat: 24.1840, lng: 121.7217 },
    { name: 'Shakadang Trail', type: 'attraction', lat: 24.1590, lng: 121.4977 },
    { name: 'Eternal Spring Shrine', type: 'attraction', lat: 24.1685, lng: 121.5280 },
    { name: 'Dongdamen Night Market', type: 'attraction', lat: 23.9768, lng: 121.6070 },
    { name: 'Qixingtan Beach', type: 'attraction', lat: 24.0265, lng: 121.5985 },
    { name: 'Silks Place Taroko', type: 'hotel', lat: 24.1570, lng: 121.4985 },
    { name: 'Kadda Hotel', type: 'hotel', lat: 23.9785, lng: 121.6030 },
    { name: 'Lishiuan Hotel', type: 'hotel', lat: 23.9760, lng: 121.6010 },
    { name: 'Hualien Zhangjia BBQ', type: 'restaurant', lat: 23.9770, lng: 121.6045 },
    { name: 'Gongzheng Baozi', type: 'restaurant', lat: 23.9755, lng: 121.6023 },
    { name: 'Dai Ji Wonton', type: 'restaurant', lat: 23.9748, lng: 121.6038 },
  ],
  hotels: [
    {
      name: 'Silks Place Taroko',
      rating: 4.5,
      ratingCount: '3,000+',
      price: 'NT$$$',
      priceLabel: '~NT$8,000/night',
      tags: ['Luxury', 'Inside Taroko', 'Hot springs'],
      description: 'The only luxury hotel inside Taroko National Park. Stunning gorge views, hot spring pools, and indigenous-inspired decor.',
      tip: 'Book well in advance — it sells out in peak season.',
      website: 'https://taroko.silksplace.com/',
    },
    {
      name: 'Kadda Hotel',
      rating: 4.3,
      ratingCount: '1,800+',
      price: 'NT$$',
      priceLabel: '~NT$3,500/night',
      tags: ['Ocean view', 'Modern', 'Near night market'],
      description: 'Stylish hotel in downtown Hualien with ocean-view rooms. Walking distance to Dongdamen Night Market.',
      tip: 'Request an ocean-view room — worth the small upgrade.',
    },
    {
      name: 'Lishiuan Hotel',
      rating: 4.1,
      ratingCount: '2,200+',
      price: 'NT$',
      priceLabel: '~NT$2,500/night',
      tags: ['Budget', 'Central', 'Family rooms'],
      description: 'Reliable mid-range hotel in central Hualien. Clean rooms, friendly staff, good base for Taroko day trips.',
      tip: 'They can help arrange Taroko Gorge tours and drivers.',
    },
  ],
  restaurants: [
    {
      name: 'Hualien Zhangjia BBQ',
      rating: 4.2,
      ratingCount: '1,500+',
      price: 'NT$',
      tags: ['BBQ', 'Night market', 'Local favourite'],
      description: 'Famous BBQ stall at Dongdamen Night Market. Grilled corn, sausages, and squid are legendary.',
      mustTry: 'Grilled corn with special sauce and indigenous wild boar sausage',
      hours: '17:00–23:00 daily',
    },
    {
      name: 'Gongzheng Baozi',
      rating: 4.3,
      ratingCount: '2,000+',
      price: 'NT$',
      tags: ['Steamed buns', 'Breakfast', 'Queue-worthy'],
      description: 'Hualien\'s most famous steamed bun shop. Lines form early but move quickly.',
      mustTry: 'Pork xiaolongbao (soup buns) — juicy and cheap at ~NT$5 each',
      hours: '06:00–sold out (usually by noon)',
    },
    {
      name: 'Dai Ji Wonton',
      rating: 4.1,
      ratingCount: '800+',
      price: 'NT$',
      tags: ['Wonton', 'Noodles', 'Simple'],
      description: 'No-frills wonton noodle shop beloved by locals. Big portions, low prices.',
      mustTry: 'Wonton noodle soup — handmade wontons in clear broth',
      hours: '08:00–20:00, closed Tuesdays',
    },
  ],
  days: [
    {
      dayNum: 6,
      date: 'Aug 27 (Wed)',
      title: 'Taipei to Hualien & Taroko Gorge',
      activities: [
        { description: 'Early morning TRA Puyuma Express from Taipei to Hualien (~2.5 hours)', url: 'https://www.railway.gov.tw/en/' },
        { description: 'Check into hotel, drop bags' },
        { description: 'Afternoon Taroko Gorge visit — Shakadang Trail (easy, 2 hours round trip)', mapUrl: 'https://maps.google.com/?q=Shakadang+Trail+Taroko' },
        { description: 'Visit Eternal Spring Shrine — waterfall cascading over a cliffside temple', mapUrl: 'https://maps.google.com/?q=Eternal+Spring+Shrine+Taroko' },
        { description: 'Scenic drive through the gorge — marble canyon walls', url: 'https://www.taroko.gov.tw/en/' },
        { description: 'Evening at Dongdamen Night Market — BBQ, indigenous food, fresh fruit juices', mapUrl: 'https://maps.google.com/?q=Dongdamen+Night+Market+Hualien' },
      ],
    },
    {
      dayNum: 7,
      date: 'Aug 28 (Thu)',
      title: 'Qingshui Cliffs & Hualien Coast',
      activities: [
        { description: 'Breakfast at Gongzheng Baozi — arrive early for fresh soup buns' },
        { description: 'Morning drive or tour to Qingshui Cliffs — dramatic sea cliffs on the Pacific coast', mapUrl: 'https://maps.google.com/?q=Qingshui+Cliffs+Taiwan' },
        { description: 'Visit Qixingtan Beach — a crescent-shaped pebble beach with mountain backdrop', mapUrl: 'https://maps.google.com/?q=Qixingtan+Beach+Hualien' },
        { description: 'Lunch at Dai Ji Wonton in town' },
        { description: 'Free afternoon — optional whale watching tour or cycling along the coast' },
        { description: 'Pack for morning departure to Sun Moon Lake / Taichung' },
      ],
    },
  ],
};