import type { CityData } from '../../data/types';

export const kaohsiungData: CityData = {
  name: 'Kaohsiung',
  slug: 'kaohsiung',
  dates: 'Sep 2–5',
  nights: 3,
  tagline: 'Harbour city with art, nature, and night markets',
  accentColor: '#6A1B9A',
  mapCenter: { lat: 22.627, lng: 120.301 },
  mapZoom: 13,
  mapPoints: [
    { name: 'Lotus Pond', type: 'attraction', lat: 22.6815, lng: 120.2945 },
    { name: 'Dragon Tiger Tower', type: 'attraction', lat: 22.6800, lng: 120.2925 },
    { name: 'Cijin Island', type: 'attraction', lat: 22.6145, lng: 120.2670 },
    { name: 'Pier-2 Art Center', type: 'attraction', lat: 22.6190, lng: 120.2815 },
    { name: 'Liuhe Night Market', type: 'attraction', lat: 22.6305, lng: 120.2980 },
    { name: 'Fo Guang Shan Monastery', type: 'attraction', lat: 22.7518, lng: 120.4420 },
    { name: 'Kaohsiung 85 Sky Tower', type: 'attraction', lat: 22.6120, lng: 120.2995 },
    { name: 'Sizihwan Bay', type: 'attraction', lat: 22.6245, lng: 120.2635 },
    { name: 'Ruifeng Night Market', type: 'attraction', lat: 22.6625, lng: 120.3115 },
    { name: 'Hotel Dua', type: 'hotel', lat: 22.6310, lng: 120.2990 },
    { name: 'Chateau de Chine Kaohsiung', type: 'hotel', lat: 22.6275, lng: 120.2985 },
    { name: 'Just Sleep Kaohsiung Zhongzheng', type: 'hotel', lat: 22.6325, lng: 120.3015 },
    { name: 'Old New Taiwanese Cuisine', type: 'restaurant', lat: 22.6260, lng: 120.2930 },
    { name: 'Wufu Seafood Restaurant', type: 'restaurant', lat: 22.6290, lng: 120.2960 },
    { name: 'Kaohsiung Papaya Milk', type: 'restaurant', lat: 22.6305, lng: 120.2985 },
  ],
  hotels: [
    {
      name: 'Hotel Dua',
      rating: 4.4,
      ratingCount: '2,500+',
      price: 'NT$$',
      priceLabel: '~NT$4,000/night',
      tags: ['Design hotel', 'Central', 'Rooftop pool'],
      description: 'Stylish design hotel in the heart of Kaohsiung. The rooftop pool has city views and is perfect for cooling off.',
      tip: 'Steps from Liuhe Night Market. The rooftop bar is a great sunset spot.',
      website: 'https://www.hoteldua.com/',
    },
    {
      name: 'Chateau de Chine Kaohsiung',
      rating: 4.3,
      ratingCount: '1,500+',
      price: 'NT$$',
      priceLabel: '~NT$3,800/night',
      tags: ['Near MRT', 'Family-friendly', 'Harbour views'],
      description: 'Well-appointed hotel near the harbour with good family room options. Close to Pier-2 Art Center.',
      tip: 'Ask for a harbour-facing room for views of the port and 85 Sky Tower.',
    },
    {
      name: 'Just Sleep Kaohsiung Zhongzheng',
      rating: 4.1,
      ratingCount: '1,800+',
      price: 'NT$',
      priceLabel: '~NT$2,500/night',
      tags: ['Budget', 'MRT accessible', 'Clean'],
      description: 'Reliable budget option from the Just Sleep chain. Modern, clean, and well-connected by MRT.',
      tip: 'Good value for families — book connecting rooms if available.',
      website: 'https://www.justsleep.com.tw/',
    },
  ],
  restaurants: [
    {
      name: 'Old New Taiwanese Cuisine',
      rating: 4.4,
      ratingCount: '1,200+',
      price: 'NT$$',
      tags: ['Taiwanese', 'Refined', 'Family-friendly'],
      description: 'Traditional Taiwanese dishes elevated with modern presentation. A great family dinner spot.',
      mustTry: 'Three-cup chicken, pan-fried pork liver, and fried rice with dried shrimp',
      hours: '11:30–14:00, 17:30–21:00',
      bookAhead: true,
    },
    {
      name: 'Wufu Seafood Restaurant',
      rating: 4.2,
      ratingCount: '800+',
      price: 'NT$$',
      tags: ['Seafood', 'Fresh', 'Local'],
      description: 'Fresh seafood restaurant popular with locals. Pick your fish from the tanks and they cook it to order.',
      mustTry: 'Steamed grouper with ginger and soy, salt-and-pepper squid',
      hours: '11:00–14:00, 17:00–22:00',
    },
    {
      name: 'Kaohsiung Papaya Milk Stand',
      rating: 4.5,
      ratingCount: '3,000+',
      price: 'NT$',
      tags: ['Drinks', 'Night market', 'Iconic'],
      description: 'The legendary papaya milk stand near Liuhe Night Market. Rich, creamy, and refreshing.',
      mustTry: 'Fresh papaya milk — blended to order with local papayas and whole milk',
      hours: '12:00–23:00 daily',
    },
    {
      name: 'Cijin Seafood Street',
      rating: 4.2,
      ratingCount: '2,000+',
      price: 'NT$',
      tags: ['Seafood', 'Island', 'Casual'],
      description: 'A whole street of seafood restaurants on Cijin Island. Ultra-fresh catches grilled and fried to order.',
      mustTry: 'Grilled squid on a stick, fried fish cakes, and seafood congee',
      hours: '10:00–20:00 daily',
    },
  ],
  days: [
    {
      dayNum: 12,
      date: 'Sep 2 (Tue)',
      title: 'Tainan to Kaohsiung & Harbour',
      activities: [
        { description: 'THSR from Tainan to Zuoying Station (Kaohsiung) — just 15 minutes', url: 'https://www.thsrc.com.tw/en/' },
        { description: 'MRT from Zuoying to hotel, check in' },
        { description: 'Afternoon at Pier-2 Art Center — converted warehouses filled with street art and installations', url: 'https://pier2.org/en/', mapUrl: 'https://maps.google.com/?q=Pier-2+Art+Center+Kaohsiung' },
        { description: 'Walk along the Love River harbourfront' },
        { description: 'Sunset at Sizihwan Bay — beach and old British consulate with harbour views', mapUrl: 'https://maps.google.com/?q=Sizihwan+Bay+Kaohsiung' },
        { description: 'Dinner and evening at Liuhe Night Market — seafood, papaya milk, steak', mapUrl: 'https://maps.google.com/?q=Liuhe+Night+Market' },
      ],
    },
    {
      dayNum: 13,
      date: 'Sep 3 (Wed)',
      title: 'Lotus Pond & Cijin Island',
      activities: [
        { description: 'Morning at Lotus Pond — walk through the Dragon Tiger Tower (enter dragon, exit tiger for good luck)', mapUrl: 'https://maps.google.com/?q=Dragon+Tiger+Tower+Kaohsiung' },
        { description: 'Visit the Spring and Autumn Pavilions and Confucius Temple on the lake', mapUrl: 'https://maps.google.com/?q=Lotus+Pond+Kaohsiung' },
        { description: 'Take the ferry to Cijin Island from Gushan Ferry Pier (~5 min, NT$40)', mapUrl: 'https://maps.google.com/?q=Cijin+Island+Kaohsiung' },
        { description: 'Explore Cijin Old Street — seafood, temples, and the Cijin Lighthouse' },
        { description: 'Lunch at Cijin Seafood Street — fresh catch from the harbour' },
        { description: 'Rent bikes on Cijin and ride along the coastal path' },
        { description: 'Ferry back, dinner at Old New Taiwanese Cuisine (book ahead)' },
      ],
    },
    {
      dayNum: 14,
      date: 'Sep 4 (Thu)',
      title: 'Fo Guang Shan & Last Night',
      activities: [
        { description: 'Half-day trip to Fo Guang Shan Buddha Museum — one of the largest Buddhist monasteries in the world', url: 'https://www.fgsbmc.org.tw/en/', mapUrl: 'https://maps.google.com/?q=Fo+Guang+Shan+Buddha+Museum' },
        { description: 'Walk through the Eight Pagodas and see the 36-metre seated Buddha statue' },
        { description: 'Free vegetarian lunch at the monastery (donations welcome)' },
        { description: 'Afternoon back in Kaohsiung — last-minute shopping or relaxing' },
        { description: 'Evening at Ruifeng Night Market — a local favourite with less tourists than Liuhe', mapUrl: 'https://maps.google.com/?q=Ruifeng+Night+Market+Kaohsiung' },
        { description: 'Pack for departure tomorrow' },
      ],
    },
    {
      dayNum: 15,
      date: 'Sep 5 (Fri)',
      title: 'Departure Day',
      activities: [
        { description: 'Check out of hotel' },
        { description: 'THSR from Zuoying to Taoyuan (~1.5 hours)', url: 'https://www.thsrc.com.tw/en/' },
        { description: 'Airport MRT from THSR Taoyuan to TPE Airport (~20 min)' },
        { description: 'Depart from Taiwan Taoyuan International Airport (TPE) to YVR' },
      ],
    },
  ],
};