import type { PhraseBook } from '../../data/types';

export const phrases: PhraseBook = {
  language: 'Mandarin Chinese (Taiwan)',
  nativeName: '中文',
  speechLang: 'zh-TW',
  intro:
    'Taiwan writes in traditional characters and speaks Mandarin with a softer, less retroflex accent than the mainland. Pinyin is the romanization below; the respelling next to it is written for an English speaker, with CAPITALS on the stress.',
  englishNote:
    'Signage and MRT announcements are bilingual in Taipei and Kaohsiung, and younger staff often speak some English. Night markets, taxis, and smaller towns are Mandarin-first — pointing plus 這個 (this one) covers a lot.',
  pronunciationKey: [
    { sound: 'tones', as: 'ā flat and high · á rising like a question · ǎ dipping down then up · à falling sharply', example: 'mā (mother) vs mà (to scold)' },
    { sound: 'q', as: '"ch" with the tongue flat and lips spread', example: 'qǐng → "ching"' },
    { sound: 'x', as: 'a soft "sh", almost a hiss', example: 'xièxie → "SYEH-syeh"' },
    { sound: 'zh', as: '"j" as in jam', example: 'zhège → "JUH-guh"' },
    { sound: 'c / z', as: '"ts" / "dz"', example: 'cèsuǒ → "TSUH-swor"' },
    { sound: 'e', as: '"uh"', example: 'shénme → "SHUN-muh"' },
    { sound: 'ian', as: '"yen"', example: 'qián → "chyen"' },
    { sound: 'ong', as: '"oong"', example: 'zǒnggòng → "DZOONG-goong"' },
    { sound: 'ü', as: '"ee" with rounded lips', example: 'jiéyùn → "JYEH-yun"' },
    { sound: '-i after zh/ch/sh/r', as: 'no real vowel, just a buzz', example: 'shí → "shr"' },
  ],
  categories: [
    {
      id: 'greetings',
      title: 'Hello & goodbye',
      emoji: '👋',
      phrases: [
        { en: 'Hello', native: '你好', romanized: 'nǐ hǎo', pronunciation: 'nee HOW' },
        { en: 'Good morning', native: '早安', romanized: 'zǎo ān', pronunciation: 'dzow AHN' },
        { en: 'How are you?', native: '你好嗎？', romanized: 'nǐ hǎo ma', pronunciation: 'nee how MAH' },
        { en: 'Goodbye', native: '再見', romanized: 'zàijiàn', pronunciation: 'dzye-JYEN' },
        { en: 'Bye bye (casual)', native: '掰掰', romanized: 'bāibāi', pronunciation: 'bye-BYE', note: 'What people actually say in Taiwan on the way out of a shop.' },
        { en: 'Thank you', native: '謝謝', romanized: 'xièxie', pronunciation: 'SYEH-syeh' },
        { en: "You're welcome", native: '不客氣', romanized: 'bú kèqì', pronunciation: 'boo KUH-chee' },
        { en: 'Sorry', native: '對不起', romanized: 'duìbùqǐ', pronunciation: 'dway-boo-CHEE' },
        { en: 'Excuse me / sorry to bother you', native: '不好意思', romanized: 'bù hǎoyìsi', pronunciation: 'boo how-EE-suh', note: 'The most-used phrase in Taiwan. Flagging a server, squeezing past, apologising — all of it.' },
        { en: 'May I ask… (before a question)', native: '請問', romanized: 'qǐngwèn', pronunciation: 'ching-WUN', note: 'Put it in front of any question to sound polite.' },
      ],
    },
    {
      id: 'basics',
      title: 'Yes, no & not understanding',
      emoji: '🗣️',
      phrases: [
        { en: 'Yes / no', native: '是 / 不是', romanized: 'shì / bú shì', pronunciation: 'shr / boo shr', note: 'Mandarin has no all-purpose yes — you echo the verb. 對 (duì, "dway") works as "right / correct".' },
        { en: 'Do you speak English?', native: '你會說英文嗎？', romanized: 'nǐ huì shuō yīngwén ma', pronunciation: 'nee hway shwor YING-wun mah' },
        { en: "I don't understand", native: '我聽不懂', romanized: 'wǒ tīng bù dǒng', pronunciation: 'wor ting boo DUNG' },
        { en: 'Please say that again', native: '請再說一次', romanized: 'qǐng zài shuō yí cì', pronunciation: 'ching dzye shwor ee TSUH' },
        { en: 'Please speak a bit slower', native: '請說慢一點', romanized: 'qǐng shuō màn yìdiǎn', pronunciation: 'ching shwor mahn ee-DYEN' },
        { en: 'I only speak a little Chinese', native: '我只會說一點中文', romanized: 'wǒ zhǐ huì shuō yìdiǎn zhōngwén', pronunciation: 'wor jr hway shwor ee-dyen JOONG-wun' },
      ],
    },
    {
      id: 'directions',
      title: 'Where is…? What is…?',
      emoji: '🧭',
      phrases: [
        { en: 'Where is…?', native: '……在哪裡？', romanized: 'zài nǎlǐ', pronunciation: 'dzye NAH-lee', note: 'Name the place first: 廁所在哪裡？ — toilet, where is it?', speak: '在哪裡？' },
        { en: 'Where is the toilet?', native: '廁所在哪裡？', romanized: 'cèsuǒ zài nǎlǐ', pronunciation: 'TSUH-swor dzye NAH-lee' },
        { en: 'Where is the MRT station?', native: '捷運站在哪裡？', romanized: 'jiéyùn zhàn zài nǎlǐ', pronunciation: 'JYEH-yun jahn dzye NAH-lee' },
        { en: 'What is this?', native: '這是什麼？', romanized: 'zhè shì shénme', pronunciation: 'jur shr SHUN-muh', note: 'Night-market workhorse. Point, ask, eat.' },
        { en: 'This one, please', native: '我要這個', romanized: 'wǒ yào zhège', pronunciation: 'wor yow JUH-guh', literal: 'I want this one' },
        { en: 'How far is it?', native: '多遠？', romanized: 'duō yuǎn', pronunciation: 'dwor YWEN' },
        { en: 'Straight / left / right', native: '直走 / 左轉 / 右轉', romanized: 'zhí zǒu / zuǒ zhuǎn / yòu zhuǎn', pronunciation: 'jr dzoh / dzwor jwan / yoh jwan', note: 'What comes back at you when you ask for directions.' },
        { en: "I'm lost", native: '我迷路了', romanized: 'wǒ mílù le', pronunciation: 'wor MEE-loo luh' },
        { en: 'I want to go to…', native: '我要去……', romanized: 'wǒ yào qù', pronunciation: 'wor yow CHU', note: 'Show the address on your phone and say this. Taxi solved.', speak: '我要去這裡' },
      ],
    },
    {
      id: 'food',
      title: 'Eating out',
      emoji: '🍜',
      phrases: [
        { en: 'Table for four', native: '四位', romanized: 'sì wèi', pronunciation: 'suh WAY', literal: 'four people' },
        { en: 'Menu', native: '菜單', romanized: 'càidān', pronunciation: 'tsye-DAN' },
        { en: 'For here / to go', native: '內用 / 外帶', romanized: 'nèiyòng / wàidài', pronunciation: 'nay-YOONG / why-DYE', note: 'The first question at every counter and bubble tea shop. Learn both.' },
        { en: 'Not spicy, please', native: '不要辣', romanized: 'bú yào là', pronunciation: 'boo yow LAH' },
        { en: 'No cilantro', native: '不要香菜', romanized: 'bú yào xiāngcài', pronunciation: 'boo yow SYAHNG-tsye' },
        { en: "I'm allergic to…", native: '我對……過敏', romanized: 'wǒ duì … guòmǐn', pronunciation: 'wor dway … gwor-MEEN', speak: '我對花生過敏' },
        { en: 'Vegetarian', native: '素食', romanized: 'sùshí', pronunciation: 'soo-SHR' },
        { en: 'Less sugar, less ice', native: '少糖少冰', romanized: 'shǎo táng shǎo bīng', pronunciation: 'shaow TAHNG shaow BING', note: 'The standard bubble tea order adjustment.' },
        { en: 'Delicious!', native: '好吃', romanized: 'hǎochī', pronunciation: 'HOW-chr' },
        { en: 'The bill, please', native: '買單', romanized: 'mǎidān', pronunciation: 'my-DAN', note: '結帳 (jiézhàng, "jyeh-JAHNG") works too — many places have you pay at the counter.' },
      ],
    },
    {
      id: 'money',
      title: 'Shopping & prices',
      emoji: '💰',
      intro: 'Prices are written 元 (NT$) but spoken 塊 (kuài). NT$150 is 一百五十塊.',
      phrases: [
        { en: 'How much is it?', native: '多少錢？', romanized: 'duōshǎo qián', pronunciation: 'dwor-shaow CHYEN' },
        { en: 'How much altogether?', native: '總共多少？', romanized: 'zǒnggòng duōshǎo', pronunciation: 'DZOONG-goong dwor-SHAOW' },
        { en: 'Too expensive', native: '太貴了', romanized: 'tài guì le', pronunciation: 'tye GWAY luh' },
        { en: 'Can it be a bit cheaper?', native: '可以便宜一點嗎？', romanized: 'kěyǐ piányí yìdiǎn ma', pronunciation: 'kuh-ee pyen-EE ee-dyen mah', note: 'Fair game at markets, not in shops.' },
        { en: 'Can I pay by card?', native: '可以刷卡嗎？', romanized: 'kěyǐ shuākǎ ma', pronunciation: 'kuh-ee shwah-KAH mah', note: 'Night markets and small shops are cash-only. Carry NT$1000 in small notes.' },
        { en: "I'm just looking", native: '我只是看看', romanized: 'wǒ zhǐshì kànkan', pronunciation: 'wor jr-shr KAN-kan' },
        { en: 'No bag needed', native: '不用袋子', romanized: 'búyòng dàizi', pronunciation: 'boo-YOONG DYE-dzuh', note: 'Bags cost extra in Taiwan, so you will be asked.' },
        { en: 'EasyCard (transit card)', native: '悠遊卡', romanized: 'yōuyóukǎ', pronunciation: 'yoh-yoh-KAH', note: 'Works on the MRT, buses, trains, and in every convenience store.' },
        { en: 'NT$150 — a hundred fifty', native: '一百五十塊', romanized: 'yìbǎi wǔshí kuài', pronunciation: 'ee-bye WOO-shr kwye' },
        { en: 'NT$1200 — twelve hundred', native: '一千二百塊', romanized: 'yìqiān èrbǎi kuài', pronunciation: 'ee-chyen AR-bye kwye' },
      ],
    },
    {
      id: 'numbers',
      title: 'Numbers',
      emoji: '🔢',
      intro: 'Mandarin numbers stack: 15 is "ten five", 20 is "two ten", 45 is "four ten five". Use 兩 (liǎng) rather than 二 when counting things — 兩個 is two of something.',
      layout: 'grid',
      phrases: [
        { en: '0', native: '零', romanized: 'líng', pronunciation: 'ling' },
        { en: '1', native: '一', romanized: 'yī', pronunciation: 'ee' },
        { en: '2', native: '二 / 兩', romanized: 'èr / liǎng', pronunciation: 'ar / lyahng', speak: '二' },
        { en: '3', native: '三', romanized: 'sān', pronunciation: 'sahn' },
        { en: '4', native: '四', romanized: 'sì', pronunciation: 'suh' },
        { en: '5', native: '五', romanized: 'wǔ', pronunciation: 'woo' },
        { en: '6', native: '六', romanized: 'liù', pronunciation: 'lyoh' },
        { en: '7', native: '七', romanized: 'qī', pronunciation: 'chee' },
        { en: '8', native: '八', romanized: 'bā', pronunciation: 'bah' },
        { en: '9', native: '九', romanized: 'jiǔ', pronunciation: 'jyoh' },
        { en: '10', native: '十', romanized: 'shí', pronunciation: 'shr' },
        { en: '11', native: '十一', romanized: 'shíyī', pronunciation: 'shr-EE' },
        { en: '15', native: '十五', romanized: 'shíwǔ', pronunciation: 'shr-WOO' },
        { en: '20', native: '二十', romanized: 'èrshí', pronunciation: 'ar-SHR' },
        { en: '30', native: '三十', romanized: 'sānshí', pronunciation: 'sahn-SHR' },
        { en: '50', native: '五十', romanized: 'wǔshí', pronunciation: 'woo-SHR' },
        { en: '100', native: '一百', romanized: 'yìbǎi', pronunciation: 'ee-BYE' },
        { en: '500', native: '五百', romanized: 'wǔbǎi', pronunciation: 'woo-BYE' },
        { en: '1000', native: '一千', romanized: 'yìqiān', pronunciation: 'ee-CHYEN' },
        { en: '10,000', native: '一萬', romanized: 'yíwàn', pronunciation: 'ee-WAHN', note: 'Chinese counts in units of 10,000, so 50,000 is 五萬 — "five wàn".' },
      ],
    },
    {
      id: 'family',
      title: 'With the kids',
      emoji: '👨‍👩‍👧‍👦',
      phrases: [
        { en: 'We have two children', native: '我有兩個小孩', romanized: 'wǒ yǒu liǎng ge xiǎohái', pronunciation: 'wor yoh lyahng guh SYAOW-hi' },
        { en: 'Do you have a high chair?', native: '有兒童椅嗎？', romanized: 'yǒu értóng yǐ ma', pronunciation: 'yoh ar-TOONG ee mah' },
        { en: 'Is there a children\'s ticket?', native: '有兒童票嗎？', romanized: 'yǒu értóng piào ma', pronunciation: 'yoh ar-TOONG pyow mah' },
        { en: 'Where can I warm this up?', native: '哪裡可以加熱？', romanized: 'nǎlǐ kěyǐ jiārè', pronunciation: 'NAH-lee kuh-ee jyah-RUH', note: 'Any 7-Eleven or FamilyMart will do it.' },
      ],
    },
    {
      id: 'help',
      title: 'If something goes wrong',
      emoji: '🆘',
      intro: 'Police is 110, fire and ambulance 119. Taiwan also runs an English travel hotline on 0800-011-765.',
      phrases: [
        { en: 'Help!', native: '救命', romanized: 'jiùmìng', pronunciation: 'jyoh-MING' },
        { en: 'I need a doctor', native: '我需要醫生', romanized: 'wǒ xūyào yīshēng', pronunciation: 'wor syu-yow EE-shung' },
        { en: 'Where is the pharmacy?', native: '藥局在哪裡？', romanized: 'yàojú zài nǎlǐ', pronunciation: 'yow-JYU dzye NAH-lee' },
        { en: 'Call the police', native: '請叫警察', romanized: 'qǐng jiào jǐngchá', pronunciation: 'ching jyow JING-chah' },
        { en: 'I lost my passport', native: '我的護照掉了', romanized: 'wǒ de hùzhào diào le', pronunciation: 'wor duh HOO-jow dyow luh' },
        { en: "I don't feel well", native: '我不舒服', romanized: 'wǒ bù shūfú', pronunciation: 'wor boo SHOO-foo' },
      ],
    },
  ],
};
