import type { CityData } from '../../data/types';

export const taichungData: CityData = {
  name: 'Sun Moon Lake & Taichung',
  slug: 'taichung',
  dates: 'Aug 29–31',
  nights: 2,
  tagline: 'Mountain lake serenity and creative culture',
  accentColor: '#1565C0',
  transport: 'Take the THSR (High Speed Rail) from Taichung to Tainan (~45 min)',
  mapCenter: { lat: 23.865, lng: 120.920 },
  mapZoom: 11,
  mapPoints: [
    { name: 'Sun Moon Lake', type: 'attraction', lat: 23.8490, lng: 120.9175 },
    { name: 'Wenwu Temple', type: 'attraction', lat: 23.8618, lng: 120.9270 },
    { name: 'Ci En Pagoda', type: 'attraction', lat: 23.8530, lng: 120.9320 },
    { name: 'Ita Thao Village', type: 'attraction', lat: 23.8435, lng: 120.9345 },
    { name: 'Rainbow Village', type: 'attraction', lat: 24.1340, lng: 120.6085 },
    { name: 'Miyahara', type: 'attraction', lat: 24.1380, lng: 120.6835 },
    { name: 'National Taichung Theater', type: 'attraction', lat: 24.1625, lng: 120.6405 },
    { name: 'Feng Chia Night Market', type: 'attraction', lat: 24.1790, lng: 120.6465 },
    { name: 'Fleur de Chine Hotel', type: 'hotel', lat: 23.8575, lng: 120.9260 },
    { name: 'Shuei She Homestay', type: 'hotel', lat: 23.8630, lng: 120.9090 },
    { name: 'Hotel National Taichung', type: 'hotel', lat: 24.1500, lng: 120.6630 },
    { name: 'Chun Shui Tang', type: 'restaurant', lat: 24.1465, lng: 120.6830 },
    { name: 'Miyahara Ice Cream', type: 'restaurant', lat: 24.1380, lng: 120.6835 },
  ],
  hotels: [
    {
      name: 'Fleur de Chine Hotel',
      rating: 4.4,
      ratingCount: '2,500+',
      price: 'NT$$$',
      priceLabel: '~NT$7,000/night',
      tags: ['Lakeside', 'Luxury', 'Views'],
      description: 'Elegant lakeside hotel with panoramic Sun Moon Lake views. Infinity pool, spa, and fine dining.',
      tip: 'Book a lake-view room — the sunrise over the lake is unforgettable.',
      website: 'https://www.fleurdechinehotel.com/',
    },
    {
      name: 'Shuei She Homestay Area',
      rating: 4.0,
      ratingCount: '500+',
      price: 'NT$',
      priceLabel: '~NT$2,500/night',
      tags: ['Budget', 'Near lake', 'Local feel'],
      description: 'Various family-run guesthouses near Shuei She Visitor Center. Simple but cozy, with local hospitality.',
      tip: 'Many include breakfast with local specialties. Book ahead in peak season.',
    },
    {
      name: 'Hotel National Taichung',
      rating: 4.2,
      ratingCount: '1,800+',
      price: 'NT$$',
      priceLabel: '~NT$3,500/night',
      tags: ['City centre', 'Modern', 'THSR accessible'],
      description: 'Well-located hotel in Taichung city centre. Clean, modern rooms and good transport links.',
      tip: 'If spending a night in Taichung city before heading south.',
    },
  ],
  restaurants: [
    {
      name: 'Chun Shui Tang',
      rating: 4.3,
      ratingCount: '3,000+',
      price: 'NT$',
      tags: ['Bubble tea', 'Originator', 'Taiwanese tea'],
      description: 'The tea house that claims to have invented bubble tea in 1983. The original Taichung location.',
      mustTry: 'Pearl milk tea (the original!) and their sun cake set',
      hours: '09:00–22:00 daily',
      website: 'https://chunshuitang.com.tw/',
    },
    {
      name: 'Miyahara',
      rating: 4.4,
      ratingCount: '5,000+',
      price: 'NT$$',
      tags: ['Ice cream', 'Pastries', 'Historic building'],
      description: 'A former eye hospital transformed into a jaw-dropping ice cream and pastry shop. The architecture alone is worth the visit.',
      mustTry: 'Ice cream in a waffle cone with toppings — try taro, sun cake, or oolong flavours',
      hours: '10:00–21:00 daily',
    },
  ],
  days: [
    {
      dayNum: 8,
      date: 'Aug 29 (Fri)',
      title: 'Hualien to Sun Moon Lake',
      activities: [
        { description: 'Morning TRA train from Hualien to Taichung (~3.5 hours)' },
        { description: 'Bus from Taichung to Sun Moon Lake (~1.5 hours)', url: 'https://www.sunmoonlake.gov.tw/en/' },
        { description: 'Check into lakeside accommodation' },
        { description: 'Afternoon cycling around Sun Moon Lake — rent bikes near Shuei She pier (~30 km loop or partial)', mapUrl: 'https://maps.google.com/?q=Sun+Moon+Lake+Cycling+Path' },
        { description: 'Visit Wenwu Temple — grand lakeside temple dedicated to Confucius and Guan Yu', mapUrl: 'https://maps.google.com/?q=Wenwu+Temple+Sun+Moon+Lake' },
        { description: 'Evening stroll and dinner at Ita Thao Village — indigenous Thao street food', mapUrl: 'https://maps.google.com/?q=Ita+Thao+Sun+Moon+Lake' },
      ],
    },
    {
      dayNum: 9,
      date: 'Aug 30 (Sat)',
      title: 'Sun Moon Lake & Taichung',
      activities: [
        { description: 'Early morning walk to Ci En Pagoda for panoramic lake views', mapUrl: 'https://maps.google.com/?q=Ci+En+Pagoda+Sun+Moon+Lake' },
        { description: 'Take the Sun Moon Lake ferry — hop between piers and enjoy the scenery' },
        { description: 'Bus back to Taichung city (~1.5 hours)' },
        { description: 'Visit Miyahara for ice cream in the stunning restored building', mapUrl: 'https://maps.google.com/?q=Miyahara+Taichung' },
        { description: 'Optional: Rainbow Village — a former military village painted by a 96-year-old veteran', mapUrl: 'https://maps.google.com/?q=Rainbow+Village+Taichung' },
        { description: 'Bubble tea at Chun Shui Tang — the birthplace of bubble tea' },
        { description: 'Evening at Feng Chia Night Market — the largest night market in Taiwan', mapUrl: 'https://maps.google.com/?q=Feng+Chia+Night+Market' },
      ],
    },
  ],
};