import type { CityData } from '../../data/types';

export const tainanData: CityData = {
  name: 'Tainan',
  slug: 'tainan',
  dates: 'Aug 31 – Sep 2',
  nights: 2,
  tagline: 'Ancient capital and street food paradise',
  accentColor: '#E65100',
  transport: 'Take the THSR (High Speed Rail) from Tainan to Zuoying/Kaohsiung (~15 min)',
  mapCenter: { lat: 22.997, lng: 120.212 },
  mapZoom: 14,
  mapPoints: [
    { name: 'Anping Fort', type: 'attraction', lat: 23.0015, lng: 120.1610 },
    { name: 'Anping Tree House', type: 'attraction', lat: 23.0038, lng: 120.1620 },
    { name: 'Chihkan Tower', type: 'attraction', lat: 22.9978, lng: 120.2036 },
    { name: 'Confucius Temple', type: 'attraction', lat: 22.9904, lng: 120.2045 },
    { name: 'Hayashi Department Store', type: 'attraction', lat: 22.9928, lng: 120.2005 },
    { name: 'Shennong Street', type: 'attraction', lat: 22.9963, lng: 120.1970 },
    { name: 'Garden Night Market', type: 'attraction', lat: 23.0005, lng: 120.2280 },
    { name: 'Silks Place Tainan', type: 'hotel', lat: 22.9932, lng: 120.2035 },
    { name: 'U.I.J Hotel & Hostel', type: 'hotel', lat: 22.9915, lng: 120.2030 },
    { name: 'Tainan Danshui Fish Shop', type: 'restaurant', lat: 22.9958, lng: 120.2042 },
    { name: 'Du Hsiao Yueh', type: 'restaurant', lat: 22.9925, lng: 120.2035 },
    { name: 'Tai\'s Meat Rice', type: 'restaurant', lat: 22.9950, lng: 120.1995 },
  ],
  hotels: [
    {
      name: 'Silks Place Tainan',
      rating: 4.5,
      ratingCount: '2,000+',
      price: 'NT$$$',
      priceLabel: '~NT$6,000/night',
      tags: ['Luxury', 'Historic area', 'Pool'],
      description: 'Upscale hotel near Chihkan Tower in the heart of Tainan\'s historic district. Beautiful pool and excellent service.',
      tip: 'Walking distance to all major historic sites and food streets.',
      website: 'https://tainan.silksplace.com/',
    },
    {
      name: 'U.I.J Hotel & Hostel',
      rating: 4.3,
      ratingCount: '1,200+',
      price: 'NT$$',
      priceLabel: '~NT$3,000/night',
      tags: ['Boutique', 'Design', 'Rooftop'],
      description: 'Stylish boutique hotel with a great rooftop terrace. Right in the historic food district.',
      tip: 'The rooftop is perfect for evening drinks after a day of temple hopping.',
    },
  ],
  restaurants: [
    {
      name: 'Du Hsiao Yueh',
      rating: 4.3,
      ratingCount: '4,000+',
      price: 'NT$',
      tags: ['Dan zai noodles', 'Historic', 'Iconic'],
      description: 'The most famous dan zai noodle shop in Tainan, operating since 1895. A must-visit.',
      mustTry: 'Dan zai noodles — small bowl of shrimp-pork noodles with a rich savoury broth',
      hours: '11:00–21:00 daily',
      website: 'https://www.iddi.com.tw/',
    },
    {
      name: 'Tainan Danshui Fish Shop',
      rating: 4.2,
      ratingCount: '1,500+',
      price: 'NT$',
      tags: ['Milkfish', 'Breakfast', 'Local staple'],
      description: 'Tainan is the milkfish capital of Taiwan, and this is one of the best places to try it.',
      mustTry: 'Milkfish congee with fish belly — a classic Tainan breakfast',
      hours: '06:00–14:00, closed Mondays',
    },
    {
      name: 'Tai\'s Meat Rice',
      rating: 4.1,
      ratingCount: '800+',
      price: 'NT$',
      tags: ['Rice bowl', 'Comfort food', 'Local'],
      description: 'Simple, soulful meat rice (rou fan) — braised pork over rice, Tainan style.',
      mustTry: 'Pork rice bowl with a side of fishball soup',
      hours: '10:00–20:00, closed Tuesdays',
    },
  ],
  days: [
    {
      dayNum: 10,
      date: 'Aug 31 (Sun)',
      title: 'Taichung to Tainan & Historic District',
      activities: [
        { description: 'THSR from Taichung to Tainan (~45 min)', url: 'https://www.thsrc.com.tw/en/' },
        { description: 'Shuttle bus from THSR Tainan station to city centre (~30 min)' },
        { description: 'Check into hotel' },
        { description: 'Lunch at Du Hsiao Yueh — the iconic dan zai noodle shop since 1895' },
        { description: 'Walk to Chihkan Tower — a 17th-century Dutch fort', url: 'https://www.twtainan.net/en/attractions/detail/738', mapUrl: 'https://maps.google.com/?q=Chihkan+Tower+Tainan' },
        { description: 'Visit Confucius Temple — the oldest in Taiwan, built in 1665', mapUrl: 'https://maps.google.com/?q=Confucius+Temple+Tainan' },
        { description: 'Evening stroll along Shennong Street — beautifully lit historic lane', mapUrl: 'https://maps.google.com/?q=Shennong+Street+Tainan' },
        { description: 'Dinner at Garden Night Market (open Thu, Sat, Sun)', mapUrl: 'https://maps.google.com/?q=Garden+Night+Market+Tainan' },
      ],
    },
    {
      dayNum: 11,
      date: 'Sep 1 (Mon)',
      title: 'Anping & Tainan Food Tour',
      activities: [
        { description: 'Breakfast: milkfish congee at Tainan Danshui Fish Shop' },
        { description: 'Morning trip to Anping district — historic port area' },
        { description: 'Visit Anping Fort — Taiwan\'s oldest fortress, built by the Dutch in 1624', url: 'https://www.twtainan.net/en/attractions/detail/705', mapUrl: 'https://maps.google.com/?q=Anping+Fort+Tainan' },
        { description: 'Explore Anping Tree House — a warehouse overtaken by banyan tree roots', mapUrl: 'https://maps.google.com/?q=Anping+Tree+House+Tainan' },
        { description: 'Try Anping specialties: shrimp rolls, tofu pudding, candied fruits' },
        { description: 'Afternoon at Hayashi Department Store — restored 1930s Japanese-era department store', mapUrl: 'https://maps.google.com/?q=Hayashi+Department+Store+Tainan' },
        { description: 'Lunch/snack at Tai\'s Meat Rice' },
        { description: 'Prepare for transfer to Kaohsiung tomorrow' },
      ],
    },
  ],
};