import type { CityData } from '../../data/types';

export const taipeiData: CityData = {
  name: 'Taipei',
  slug: 'taipei',
  dates: 'Aug 22–27',
  nights: 5,
  tagline: 'Night markets, temples, and mountain views',
  accentColor: '#C62828',
  transport: 'Take the TRA Puyuma/Taroko Express to Hualien (~2.5 hours)',
  mapCenter: { lat: 25.033, lng: 121.565 },
  mapZoom: 13,
  mapPoints: [
    { name: 'Taipei 101', type: 'attraction', lat: 25.0340, lng: 121.5645 },
    { name: 'Shilin Night Market', type: 'attraction', lat: 25.0877, lng: 121.5241 },
    { name: 'Longshan Temple', type: 'attraction', lat: 25.0372, lng: 121.4998 },
    { name: 'National Palace Museum', type: 'attraction', lat: 25.1024, lng: 121.5485 },
    { name: 'Chiang Kai-shek Memorial', type: 'attraction', lat: 25.0349, lng: 121.5219 },
    { name: 'Elephant Mountain', type: 'attraction', lat: 25.0275, lng: 121.5728 },
    { name: 'Jiufen Old Street', type: 'attraction', lat: 25.1094, lng: 121.8443 },
    { name: 'Beitou Hot Springs', type: 'attraction', lat: 25.1365, lng: 121.5068 },
    { name: 'Raohe Night Market', type: 'attraction', lat: 25.0505, lng: 121.5774 },
    { name: 'Dadaocheng / Dihua Street', type: 'attraction', lat: 25.0558, lng: 121.5095 },
    { name: 'Amba Taipei Songshan', type: 'hotel', lat: 25.0495, lng: 121.5780 },
    { name: 'Hotel Cozzi Zhongxiao', type: 'hotel', lat: 25.0415, lng: 121.5440 },
    { name: 'Just Sleep Ximending', type: 'hotel', lat: 25.0430, lng: 121.5075 },
    { name: 'Citizen M Taipei North Gate', type: 'hotel', lat: 25.0470, lng: 121.5125 },
    { name: 'Din Tai Fung (Xinyi)', type: 'restaurant', lat: 25.0339, lng: 121.5620 },
    { name: 'Addiction Aquatic Development', type: 'restaurant', lat: 25.0630, lng: 121.5555 },
    { name: 'Yongkang Beef Noodle', type: 'restaurant', lat: 25.0310, lng: 121.5292 },
    { name: 'Ay-Chung Flour Rice Noodle', type: 'restaurant', lat: 25.0427, lng: 121.5078 },
    { name: 'Mala Hotpot', type: 'restaurant', lat: 25.0445, lng: 121.5310 },
  ],
  hotels: [
    {
      name: 'Amba Taipei Songshan',
      rating: 4.3,
      ratingCount: '2,800+',
      price: 'NT$$',
      priceLabel: '~NT$4,500/night',
      tags: ['Design hotel', 'Near Raohe Night Market', 'MRT accessible'],
      description: 'Trendy design hotel right next to Songshan MRT and Raohe Night Market. Modern rooms with city views.',
      tip: 'Ask for a room on a higher floor for better city views.',
      website: 'https://www.amba-hotels.com/songshan/',
    },
    {
      name: 'Hotel Cozzi Zhongxiao',
      rating: 4.2,
      ratingCount: '1,500+',
      price: 'NT$$',
      priceLabel: '~NT$4,000/night',
      tags: ['Central location', 'Family-friendly', 'Near Zhongxiao Dunhua'],
      description: 'Well-located hotel in the eastern Taipei shopping district. Clean, modern rooms with good amenities.',
      tip: 'Walking distance to many restaurants and the Zhongxiao shopping area.',
    },
    {
      name: 'Just Sleep Ximending',
      rating: 4.1,
      ratingCount: '3,000+',
      price: 'NT$',
      priceLabel: '~NT$3,000/night',
      tags: ['Budget-friendly', 'Ximending district', 'Near MRT'],
      description: 'Affordable and cheerful hotel in the heart of Ximending, Taipei\'s youth and entertainment district.',
      tip: 'Great base for night market hopping. Book a family room early.',
      website: 'https://www.justsleep.com.tw/',
    },
    {
      name: 'citizenM Taipei North Gate',
      rating: 4.5,
      ratingCount: '1,200+',
      price: 'NT$$',
      priceLabel: '~NT$4,200/night',
      tags: ['Modern', 'Near Taipei Main Station', 'Great rooftop'],
      description: 'Stylish international chain hotel near Taipei Main Station. Known for its self-check-in and rooftop bar.',
      tip: 'The rooftop has great views of Taipei. Rooms are compact but well-designed.',
    },
  ],
  restaurants: [
    {
      name: 'Din Tai Fung (Xinyi)',
      rating: 4.5,
      ratingCount: '15,000+',
      price: 'NT$$',
      tags: ['Xiaolongbao', 'Iconic', 'Family-friendly'],
      description: 'The world-famous dumpling house. The Xinyi flagship location in Taipei 101 mall has the shortest waits.',
      mustTry: 'Xiaolongbao (soup dumplings) — watch them being made through the kitchen window',
      hours: '11:00–21:00 daily',
      bookAhead: true,
    },
    {
      name: 'Addiction Aquatic Development',
      rating: 4.3,
      ratingCount: '5,000+',
      price: 'NT$$',
      tags: ['Seafood', 'Market', 'Sashimi'],
      description: 'Part fish market, part food court, part upscale seafood restaurant. An incredible seafood experience.',
      mustTry: 'Fresh sashimi platter and grilled seafood from the standing bar',
      hours: '06:00–00:00 daily',
    },
    {
      name: 'Yongkang Beef Noodle',
      rating: 4.4,
      ratingCount: '8,000+',
      price: 'NT$',
      tags: ['Beef noodle soup', 'Classic', 'Local favourite'],
      description: 'Arguably the most famous beef noodle soup in Taipei, on the iconic Yongkang Street.',
      mustTry: 'Half-tendon half-meat beef noodle soup — rich, beefy broth with hand-pulled noodles',
      hours: '11:00–21:00, closed Wednesdays',
    },
    {
      name: 'Ay-Chung Flour Rice Noodle',
      rating: 4.2,
      ratingCount: '6,000+',
      price: 'NT$',
      tags: ['Street food', 'Ximending', 'Quick'],
      description: 'Legendary street food stall in Ximending. Always a long queue but moves fast.',
      mustTry: 'Large bowl of thick rice noodles in savoury pork intestine broth',
      hours: '11:00–22:30 daily',
    },
    {
      name: 'Mala Hotpot',
      rating: 4.1,
      ratingCount: '2,000+',
      price: 'NT$$',
      tags: ['Hot pot', 'Spicy', 'Interactive'],
      description: 'DIY hot pot where you pick your ingredients buffet-style and cook at your table.',
      mustTry: 'Mala (spicy numbing) broth with thinly sliced beef and handmade dumplings',
      hours: '11:30–01:00 daily',
    },
  ],
  days: [
    {
      dayNum: 1,
      date: 'Aug 22 (Fri)',
      title: 'Arrival & Ximending',
      activities: [
        { description: 'Arrive at Taiwan Taoyuan International Airport (TPE)' },
        { description: 'Take airport MRT to Taipei Main Station (~35 min)', url: 'https://www.taoyuan-airport.com/en/mrt' },
        { description: 'Check into hotel, rest and freshen up' },
        { description: 'Evening walk through Ximending pedestrian area', mapUrl: 'https://maps.google.com/?q=Ximending,Taipei' },
        { description: 'Dinner at Ay-Chung Flour Rice Noodle + explore night market stalls' },
      ],
    },
    {
      dayNum: 2,
      date: 'Aug 23 (Sat)',
      title: 'Taipei Icons',
      activities: [
        { description: 'Morning visit to Chiang Kai-shek Memorial Hall — watch the guard changing ceremony', url: 'https://www.cksmh.gov.tw/en/', mapUrl: 'https://maps.google.com/?q=Chiang+Kai-shek+Memorial+Hall' },
        { description: 'Lunch at Din Tai Fung (Xinyi) — book ahead to avoid the queue', url: 'https://www.dintaifung.com.tw/' },
        { description: 'Afternoon at Taipei 101 — observatory on the 89th floor', url: 'https://www.taipei-101.com.tw/en/', mapUrl: 'https://maps.google.com/?q=Taipei+101' },
        { description: 'Sunset hike up Elephant Mountain (Xiangshan) for iconic Taipei 101 views (~20 min climb)', mapUrl: 'https://maps.google.com/?q=Elephant+Mountain+Taipei' },
        { description: 'Evening at Raohe Night Market — pepper buns, stinky tofu, bubble tea', mapUrl: 'https://maps.google.com/?q=Raohe+Night+Market' },
      ],
    },
    {
      dayNum: 3,
      date: 'Aug 24 (Sun)',
      title: 'Temples & Culture',
      activities: [
        { description: 'Morning visit to Longshan Temple — one of Taipei\'s oldest and most important temples', url: 'https://www.lungshan.org.tw/', mapUrl: 'https://maps.google.com/?q=Longshan+Temple+Taipei' },
        { description: 'Walk through Bopiliao Historic Block — preserved Qing dynasty street', mapUrl: 'https://maps.google.com/?q=Bopiliao+Historic+Block' },
        { description: 'Lunch at Yongkang Beef Noodle on Yongkang Street' },
        { description: 'Afternoon at National Palace Museum — world\'s largest collection of Chinese art', url: 'https://www.npm.gov.tw/en/', mapUrl: 'https://maps.google.com/?q=National+Palace+Museum+Taipei' },
        { description: 'Evening at Shilin Night Market — the largest and most famous night market', mapUrl: 'https://maps.google.com/?q=Shilin+Night+Market' },
      ],
    },
    {
      dayNum: 4,
      date: 'Aug 25 (Mon)',
      title: 'Day Trip: Jiufen & Northeast Coast',
      activities: [
        { description: 'Take bus 1062 from Zhongxiao Fuxing MRT to Jiufen (~1.5 hours)' },
        { description: 'Explore Jiufen Old Street — the inspiration for Spirited Away', mapUrl: 'https://maps.google.com/?q=Jiufen+Old+Street' },
        { description: 'Try taro balls, fish ball soup, and peanut ice cream rolls' },
        { description: 'Visit A-Mei Tea House for mountain views and oolong tea', mapUrl: 'https://maps.google.com/?q=A-Mei+Tea+House+Jiufen' },
        { description: 'Optional: continue to Shifen for sky lanterns and the waterfall', mapUrl: 'https://maps.google.com/?q=Shifen+Old+Street' },
        { description: 'Return to Taipei, dinner at Addiction Aquatic Development' },
      ],
    },
    {
      dayNum: 5,
      date: 'Aug 26 (Tue)',
      title: 'Beitou & Dadaocheng',
      activities: [
        { description: 'Morning trip to Beitou Hot Springs — take MRT Red Line to Xinbeitou', mapUrl: 'https://maps.google.com/?q=Beitou+Hot+Springs' },
        { description: 'Visit Beitou Hot Spring Museum and the thermal valley', url: 'https://hotspringmuseum.taipei/' },
        { description: 'Optional: soak at a public hot spring (Millennium Hot Spring or hotel spa)' },
        { description: 'Afternoon explore Dadaocheng / Dihua Street — tea shops, traditional goods, historic architecture', mapUrl: 'https://maps.google.com/?q=Dihua+Street+Taipei' },
        { description: 'Dinner at Mala Hotpot — interactive DIY hot pot experience' },
        { description: 'Pack and prepare for early train to Hualien tomorrow' },
      ],
    },
  ],
};