import type { CityData } from '../../data/types';

export const sanFrancisco: CityData = {
  name: 'San Francisco',
  slug: 'san-francisco',
  dates: 'Oct 18 – 23, 2026',
  nights: 5,
  tagline: 'Python Core Dev Sprint at OpenAI — fog, code & sourdough',
  accentColor: '#002868',
  mapCenter: { lat: 37.7620, lng: -122.4190 },
  mapZoom: 13,

  venue: {
    name: 'OpenAI Office',
    eventName: 'Python Core Dev Sprint 2026',
    address: 'Mission District, San Francisco, CA — full address TBD (confirm with sprint organizers)',
    neighbourhood: 'Mission District',
    dates: 'Oct 19 – 23, 2026 (Mon – Fri)',
    hours: 'Typically 9:30 AM – 5:30 PM daily — confirm schedule with organizers',
    website: 'https://openai.com',
    mapUrl: 'https://www.google.com/maps/search/?api=1&query=OpenAI+San+Francisco',
    nearestTransit: '16th St Mission BART (~5 min walk) · Muni lines 22, 33, 49',
    accessNotes: 'Bring government-issued photo ID for building check-in. Badge or access list confirmed by organizers ahead of time. Bring your laptop fully set up.',
    contact: 'Sprint coordination on <a href="https://discuss.python.org" target="_blank" rel="noopener">Python Discourse</a> and the Python core devs Discord #sprint channel',
    lat: 37.7631,
    lng: -122.4200,
  },

  iceCreamSpots: [
    {
      name: 'Bi-Rite Creamery',
      address: '3692 18th St, San Francisco, CA 94110',
      signatureFlavors: 'Salted caramel, honey lavender, malted vanilla with peanut brittle & chocolate — legendary SF scoops',
      photoWorthy: 'Queue down the block, Dolores Park across the way — classic Mission backdrop for a sprint-week selfie',
      mapUrl: 'https://www.google.com/maps/search/?api=1&query=Bi-Rite+Creamery+San+Francisco',
      website: 'https://biritemarket.com/creamery',
      lat: 37.7618,
      lng: -122.4256,
    },
    {
      name: 'Humphry Slocombe',
      address: '2790 Harrison St, San Francisco, CA 94110 (Mission)',
      signatureFlavors: 'Secret Breakfast (bourbon & cornflakes), Blue Bottle Vietnamese coffee, Tahitian vanilla',
      photoWorthy: 'Dark, witty branding with skull-and-crossbones logo — photogenic scoops on display',
      mapUrl: 'https://www.google.com/maps/search/?api=1&query=Humphry+Slocombe+Mission+San+Francisco',
      website: 'https://humphryslocombe.com',
      lat: 37.7570,
      lng: -122.4126,
    },
    {
      name: 'Smitten Ice Cream',
      address: '432 Octavia St, San Francisco, CA 94102 (Hayes Valley)',
      signatureFlavors: 'TCHO chocolate, salted caramel — churned to order with liquid nitrogen',
      photoWorthy: 'Billowing clouds of nitrogen vapor while your scoop is made — made for video, not just stills',
      mapUrl: 'https://www.google.com/maps/search/?api=1&query=Smitten+Ice+Cream+Hayes+Valley',
      website: 'https://smittenicecream.com',
      lat: 37.7762,
      lng: -122.4240,
    },
    {
      name: 'Salt & Straw (Fillmore)',
      address: '2201 Fillmore St, San Francisco, CA 94115',
      signatureFlavors: 'Sea salt with caramel ribbons, honey lavender, inventive monthly specials',
      photoWorthy: 'Clean Pacific-Northwest design, colourful scoops lined up under glass — always Instagram-ready',
      mapUrl: 'https://www.google.com/maps/search/?api=1&query=Salt+and+Straw+Fillmore+San+Francisco',
      website: 'https://saltandstraw.com',
      lat: 37.7897,
      lng: -122.4344,
    },
  ],

  mapPoints: [
    { name: 'OpenAI Office', type: 'attraction', lat: 37.7631, lng: -122.4200 },
    { name: 'Golden Gate Bridge', type: 'attraction', lat: 37.8199, lng: -122.4783 },
    { name: 'Dolores Park', type: 'attraction', lat: 37.7596, lng: -122.4269 },
    { name: 'Ferry Building Marketplace', type: 'attraction', lat: 37.7956, lng: -122.3935 },
    { name: 'Bi-Rite Creamery', type: 'ice-cream', lat: 37.7618, lng: -122.4256 },
    { name: 'Humphry Slocombe', type: 'ice-cream', lat: 37.7570, lng: -122.4126 },
    { name: 'Smitten Ice Cream', type: 'ice-cream', lat: 37.7762, lng: -122.4240 },
    { name: 'Salt & Straw (Fillmore)', type: 'ice-cream', lat: 37.7897, lng: -122.4344 },
    { name: 'Fisherman\'s Wharf', type: 'attraction', lat: 37.8080, lng: -122.4177 },
    { name: 'Chinatown', type: 'attraction', lat: 37.7941, lng: -122.4078 },
    { name: 'Twin Peaks', type: 'attraction', lat: 37.7544, lng: -122.4477 },
    { name: 'Hotel Zephyr', type: 'hotel', lat: 37.8073, lng: -122.4150 },
    { name: 'The Parker Guest House', type: 'hotel', lat: 37.7618, lng: -122.4348 },
    { name: 'Hotel VIA', type: 'hotel', lat: 37.7812, lng: -122.3915 },
    { name: 'HI San Francisco Downtown Hostel', type: 'hotel', lat: 37.7867, lng: -122.4111 },
    { name: 'Tartine Bakery', type: 'restaurant', lat: 37.7614, lng: -122.4241 },
    { name: 'La Taqueria', type: 'restaurant', lat: 37.7509, lng: -122.4180 },
    { name: 'Swan Oyster Depot', type: 'restaurant', lat: 37.7867, lng: -122.4215 },
    { name: 'Zazie', type: 'restaurant', lat: 37.7693, lng: -122.4516 },
    { name: 'Burma Superstar', type: 'restaurant', lat: 37.7830, lng: -122.4619 },
  ],

  days: [
    {
      dayNum: 1, date: 'Oct 18 (Sun)', title: 'Arrival & Explore',
      activities: [
        { description: 'Fly YVR to SFO (~2.5 hrs direct)', mapUrl: 'https://www.google.com/maps/search/?api=1&query=San+Francisco+International+Airport' },
        { description: 'Check in to hotel, settle in, rest' },
        { description: 'Afternoon walk around the Mission District', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Mission+District+San+Francisco' },
        { description: 'Ice cream at Bi-Rite Creamery (ice cream selfie!)', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Bi-Rite+Creamery+San+Francisco' },
        { description: 'Dinner at La Taqueria — famous Mission burrito', mapUrl: 'https://www.google.com/maps/search/?api=1&query=La+Taqueria+San+Francisco' },
      ],
    },
    {
      dayNum: 2, date: 'Oct 19 (Mon)', title: 'Sprint Day 1',
      activities: [
        { description: 'Python Core Dev Sprint at OpenAI — Day 1', mapUrl: 'https://www.google.com/maps/search/?api=1&query=OpenAI+San+Francisco' },
        { description: 'Morning pastry at Tartine Bakery (near OpenAI)', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Tartine+Bakery+San+Francisco' },
        { description: 'Lunch provided at sprint (typically)', },
        { description: 'Evening: explore nearby Valencia Street shops and cafés', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Valencia+Street+San+Francisco' },
      ],
    },
    {
      dayNum: 3, date: 'Oct 20 (Tue)', title: 'Sprint Day 2',
      activities: [
        { description: 'Python Core Dev Sprint at OpenAI — Day 2', mapUrl: 'https://www.google.com/maps/search/?api=1&query=OpenAI+San+Francisco' },
        { description: 'Lunch provided at sprint' },
        { description: 'Evening: dinner at Burma Superstar (arrive early — long queues)', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Burma+Superstar+San+Francisco' },
      ],
    },
    {
      dayNum: 4, date: 'Oct 21 (Wed)', title: 'Sprint Day 3',
      activities: [
        { description: 'Python Core Dev Sprint at OpenAI — Day 3', mapUrl: 'https://www.google.com/maps/search/?api=1&query=OpenAI+San+Francisco' },
        { description: 'Lunch provided at sprint' },
        { description: 'Evening: walk to Dolores Park for city views', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Dolores+Park+San+Francisco' },
        { description: 'Dinner at Zazie (French bistro, Cole Valley)', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Zazie+San+Francisco' },
      ],
    },
    {
      dayNum: 5, date: 'Oct 22 (Thu)', title: 'Sprint Day 4',
      activities: [
        { description: 'Python Core Dev Sprint at OpenAI — Day 4', mapUrl: 'https://www.google.com/maps/search/?api=1&query=OpenAI+San+Francisco' },
        { description: 'Lunch provided at sprint' },
        { description: 'Evening: Ferry Building Marketplace — browse artisan vendors and grab dinner', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Ferry+Building+Marketplace+San+Francisco', url: 'https://www.ferrybuildingmarketplace.com/' },
      ],
    },
    {
      dayNum: 6, date: 'Oct 23 (Fri)', title: 'Last Sprint Day & Departure',
      activities: [
        { description: 'Python Core Dev Sprint at OpenAI — Day 5 (last day)', mapUrl: 'https://www.google.com/maps/search/?api=1&query=OpenAI+San+Francisco' },
        { description: 'Quick lunch at Swan Oyster Depot if time allows', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Swan+Oyster+Depot+San+Francisco' },
        { description: 'Head to SFO for evening flight back to YVR', mapUrl: 'https://www.google.com/maps/search/?api=1&query=San+Francisco+International+Airport' },
      ],
    },
  ],

  hotels: [
    {
      name: 'The Parker Guest House',
      rating: 4.7,
      ratingCount: '1.2k',
      price: '$$',
      priceLabel: 'Mid-range',
      tags: ['Mission/Castro', 'Near OpenAI', 'Charming Victorian'],
      description: 'A beautifully restored Victorian mansion in the Castro/Mission area, walking distance to the OpenAI office. Quiet rooms, lovely garden, and excellent breakfast included. Perfect for a solo work trip — boutique feel without the boutique price.',
      tip: 'Best for: Walking distance to the sprint venue with character',
      website: 'https://www.parkerguesthouse.com',
    },
    {
      name: 'Hotel VIA',
      rating: 4.5,
      ratingCount: '2.1k',
      price: '$$$',
      priceLabel: 'Splurge',
      tags: ['SoMa/South Beach', 'Modern', 'Rooftop bar'],
      description: 'A sleek modern hotel in SoMa with a stunning rooftop bar. Close to BART and Muni for an easy commute to the Mission. Great for unwinding after a long sprint day. The rooms are compact but well-designed.',
      tip: 'Best for: Modern comfort with great evening views',
      website: 'https://www.hotelviasf.com',
    },
    {
      name: 'Hotel Zephyr',
      rating: 4.3,
      ratingCount: '3.4k',
      price: '$$',
      priceLabel: 'Mid-range',
      tags: ['Fisherman\'s Wharf', 'Fun vibe', 'Game room'],
      description: 'A playful, nautical-themed hotel near Fisherman\'s Wharf with a game room, outdoor fire pits, and a fun atmosphere. A bit further from the sprint venue but close to sightseeing. Good Muni/cable car access.',
      tip: 'Best for: Combining the sprint with sightseeing in North Beach',
      website: 'https://www.hotelzephyrsf.com',
    },
    {
      name: 'HI San Francisco Downtown Hostel',
      rating: 4.4,
      ratingCount: '1.8k',
      price: '$',
      priceLabel: 'Budget-friendly',
      tags: ['Union Square', 'Private rooms available', 'Great value'],
      description: 'A well-run hostel right in Union Square with both dorm and private room options. Includes breakfast, has a kitchen, and is centrally located with excellent transit access. Private rooms are a great value for solo travelers on a budget.',
      tip: 'Best for: Budget-conscious solo traveler — book a private room',
      website: 'https://www.hiusa.org/hostels/california/san-francisco/downtown',
    },
  ],

  restaurants: [
    {
      name: 'Tartine Bakery',
      rating: 4.6,
      ratingCount: '8.2k',
      price: '$$',
      tags: ['Bakery', 'Mission District', 'Near OpenAI'],
      description: 'The iconic SF bakery just steps from the OpenAI office. Perfect for grabbing a morning pastry before the sprint. Their croissants and morning buns are legendary. Expect a queue but it moves fast.',
      mustTry: 'Morning bun, country bread, croque monsieur',
      hours: 'Mon–Sun 7:30am–5pm',
    },
    {
      name: 'La Taqueria',
      rating: 4.5,
      ratingCount: '6.1k',
      price: '$',
      tags: ['Mexican', 'Mission burrito', 'Cash only'],
      description: 'The best burrito in San Francisco, and many say in all of California. No-frills counter service with incredible carne asada and carnitas burritos. Order "no rice" for the authentic La Taqueria experience — it\'s all about the meat and beans.',
      mustTry: 'Carne asada burrito (no rice), carnitas super taco',
      hours: 'Wed–Mon 11am–9pm. Closed Tue.',
    },
    {
      name: 'Burma Superstar',
      rating: 4.4,
      ratingCount: '5.8k',
      price: '$$',
      tags: ['Burmese', 'Richmond District', 'Unique cuisine'],
      description: 'One of SF\'s most beloved restaurants serving Burmese cuisine — a rare find anywhere. The tea leaf salad is a must. Arrive early or put your name on the waitlist via Yelp — the queue can be over an hour at peak times.',
      mustTry: 'Tea leaf salad, rainbow salad, coconut chicken noodle soup',
      hours: 'Sun–Thu 11:30am–9pm, Fri–Sat 11:30am–9:30pm',
      bookAhead: true,
    },
    {
      name: 'Swan Oyster Depot',
      rating: 4.6,
      ratingCount: '3.9k',
      price: '$$',
      tags: ['Seafood', 'Counter only', 'SF institution'],
      description: 'A tiny 18-seat counter serving the freshest seafood in the city since 1912. Cash only, no reservations, and the queue starts before they open. Worth every minute of the wait. The combination plate and Dungeness crab are exceptional.',
      mustTry: 'Combination seafood plate, clam chowder, Dungeness crab',
      hours: 'Mon–Sat 10:30am–5:30pm. Closed Sun.',
    },
    {
      name: 'Zazie',
      rating: 4.6,
      ratingCount: '2.4k',
      price: '$$',
      tags: ['French bistro', 'Cole Valley', 'No-tipping policy'],
      description: 'A charming French bistro in Cole Valley known for its excellent brunch and progressive no-tipping policy (all staff receive a living wage). The garden patio is lovely. Great for a relaxed solo dinner after a sprint day.',
      mustTry: 'Duck confit, gougères, lavender crème brûlée',
      hours: 'Wed–Mon 9am–2pm, 5pm–9pm. Closed Tue.',
      bookAhead: true,
    },
  ],
};